### ISSUE TITLE
Cover Editor Does Not Read book-docinfo.xml File

### ISSUE THREAD

**Issue by ehewitt** [MakerPress/atlas-public-feedback#107]
After including a book-docinfo.xml file, maybe the cover editor should read the author list from that file to prepopulate, given that it prepopulates the title? It just says  the literal "Author list".

**Comment by MakerPress** [comment]
We thought about this, but authors sometimes want something different to appear on the title page than in the copyright page.  For example, you might want the title page to say "The Editors of O'Reilly Media" but the copyright page might say "O'Reilly Media, Inc".   So, we tried to make something that's a balance.
