### ISSUE TITLE
Cover Editor Purpose Unclear

### ISSUE THREAD

**Issue by ehewitt** [MakerPress/atlas-public-feedback#108]
I imagine this just hasn't been implemented yet, but it's not clear what is happening with the cover creator. It has very prominent real estate in Atlas, even though it presumably changes very infrequently, and it seems like it is doing a lot of work while it is "Processing Cover", but then the changes are not all saved, and I can't tell what relation it has to my book because the cover is not included in the build. 

I just don't know why I'm editing the cover because I don't know what happens to it once I've done that. It doesn't seem to matter to have changed it.

**Comment by odewahn** [comment]
This is fixed now.

Andrew

----- Original Message -----
