### ISSUE TITLE
Metadata Tab / book-docinfo.xml Split Brain

### ISSUE THREAD

**Issue by ehewitt** [MakerPress/atlas-public-feedback#109]
As reported in issue #66, there is some meta data controlled by the metadata tab in the web UI, and some in the book-docinfo.xml file. I got the same double title effect because I had my title in the Metadat and in the XML element. 

Are there plans to completely do away with the book-docinfo file? That would make sense to me, and just front all of those elements in the Metadata tab in the UI. Right now, it's split-brain, and writing that file seems arcane and unnecessary. Seems like it should be one or the other at least.

**Comment by runemadsen** [comment]
Thanks. We are working (and deploying this week) a feature that unites
these 2. So the metata tab will save changes to the book-docinfo.xml file,
and load them into the metadata form in Atlas. This should solve this
problem.

**Comment by sandersk** [comment]
Hi Eben,

Just FYI, the new metadata functionality Rune described is now in place. You can go to the Admin tab, go to the Metadata pane, and enter metadata there, which will be kept synced with the book-docinfo.xml file in the repo. Give it a shot if you like, and see what you think. And please let us know if you have any further feedback.

Thanks,
Sanders
