### ISSUE TITLE
Sub directories in Image directory

### ISSUE THREAD

**Issue by mikehatora** [MakerPress/atlas-public-feedback#11]
I am more persnickety that most.  I'd like to organize my images better rather than having a ton in one flat top level directory called Images.  

01_Chap
02_Chap
etc.

This way it is more organized.

Also, it would be great if the image manager could upload several images at one time.  The the better file upload feature we have in MT.

**Comment by katehartman** [comment]
Yes - it would be extremely helpful to be able to bulk upload images. Is this possible?

Subdirectories would also be very helpful.

**Comment by sandersk** [comment]
Hi Kate,

Apologies for the delayed response. Bulk uploading images is not currently possible via the UI, but can be done by checking out the Atlas Git repo locally, and then using git to add the files to the images/ directory, commit them, and push the files up to the Atlas Git server. You can find more information on using Git with Atlas in Chapter 6 of the Getting Started with Atlas documentation, available here:

http://cdn.oreilly.com/atlas_docs.zip

We will add bulk-image-upload functionality to our list of future enhancements for the Atlas UI.

Please let us know if you have any further questions or run into any difficulties posting images.

Thanks,
Sanders
