### ISSUE TITLE
Preface page numbers are displayed wrong in PDF

### ISSUE THREAD

**Issue by jhodgdon-drp** [MakerPress/atlas-public-feedback#111]
In my Preface, there are several cross-references, and there are cross-references from the main chapters of the book to a particular section of the preference. In the PDF document, the Preface has pages numbered in lower-case Roman numbers (i, ii, etc.). But the page number references say "See page 3" instead of "See page iii". This is confusing, because the main book starts over at page 1, so "page 3" could be referencing page iii or the actual page 3. 

I have not checked the mobi or epub versions to see if they have the same problem.

**Comment by sandersk** [comment]
Thanks so much for reporting this bug, Jennifer. I'm working on a fix that will use roman numerals for page-number references to the Preface, and will let you know as soon as it's in place.

Best,
Sanders

**Comment by sandersk** [comment]
Hi Jennifer,

Just wanted to let you know that we now have a fix in place that generates roman-numeral page numbers for cross-references to content in the Preface. Please do let me know if you see any further issues with page numbers in cross-references.

Thanks again for bringing this to our attention,
Sanders
