### ISSUE TITLE
Cross-ref links jump to wrong page in PDF

### ISSUE THREAD

**Issue by jhodgdon-drp** [MakerPress/atlas-public-feedback#112]
Ever since the cover image was added to my book, it seems like if I click on a cross-reference link in the PDF it takes me to the wrong page -- if it was supposed to go to page 51, for instance, it actually jumps to page 50. The page numbers printed out in the "See" references are correct, but the link jumps me to the wrong page.

Also, when I open up the outline viewer sidebar in the PDF reader, the same thing happens -- if i click on a section or chapter name, it takes me to the page before that section or chapter actually starts. It's scrolling to the exact spot on the page where that section would start, but it's one page off.

I have tested this in two different PDF readers: The Adobe reader for Linux (I use Ubuntu as my main desktop), and the Linux generic open-source "Document Viewer" application. The behavior is the same, so I am pretty sure the problem is in the PDF file generated by Atlas and not in the reader.

I haven't checked the mobi or epub builds to see if they have the same problem.
http://ano-atlas2.herokuapp.com/books/1230000000517/builds

**Comment by sandersk** [comment]
Thanks for another great bug report. We're working on this one as well, and will let you know when the cross-reference links are fixed.

This issue is just PDF-specific, and does not affect EPUB/Mobi, as these formats are reflowable HTML and do not have "pages".

Best,
Sanders

**Comment by sandersk** [comment]
Just an FYI that this bug has been fixed now. I've rebuilt the PDF, and the cross-ref links are now going to the correct spot. Please let us know if you see any more problems.

Thanks,
Sanders

**Comment by jhodgdon-drp** [comment]
Thanks Sanders! Works like a charm. :)
