### ISSUE TITLE
Segmentation fault during build

### ISSUE THREAD

**Issue by mrflip** [MakerPress/atlas-public-feedback#113]
I'm getting the following segmentation fault building a PDF:

```
PDFJob
Failed at 2012-10-02 21:29:43 UTC

Job failed
Full error:

2012-10-02 21:29:31,002 INFO Input file: /usr/local/app/worker/tmp/pdf/1230000000073/book.xml.worker.310.xml
2012-10-02 21:29:31,002 INFO Output file: /usr/local/app/worker/tmp/pdf/1230000000073/book.xml.worker.310.xml.highlighted.xml
2012-10-02 21:29:31,108 WARNING Unable to successfully validate XML content in /usr/local/app/worker/tmp/pdf/1230000000073/book.xml.worker.310.xml. Attempting to parse anyway.
2012-10-02 21:29:31,130 INFO Outputting highlighted DocBook to /usr/local/app/worker/tmp/pdf/1230000000073/book.xml.worker.310.xml.highlighted.xml
AHFCmd : AH CSS Formatter V6.0 MR2 for Linux64 : 6.0.2.5372 (2012/05/16 18:26JST)
         Copyright (c) 1999-2012 Antenna House, Inc.

Segmentation fault
```

Book id is 1230000000073. It builds in my local asciidoc => pdf rig.

**Comment by mrflip** [comment]
BTW -- only happens with PDF, not epub or mobi.

**Comment by mrflip** [comment]
(You'll note one successful build in there; I removed the first half of files and it built. So if necessary a bisection search may work.)

**Comment by sandersk** [comment]
Hi Philip,

Thanks for reporting this. We're looking into the cause right now, and will keep you posted.

Sanders

**Comment by sandersk** [comment]
Hi Philip,

I pinpointed the issue to a footnote in its own paragraph directly following a bulleted list in ba07-data_formats.asciidoc:

```
* Structured to model

footnote:[the worst example iis "node": a LAN node configured by a chef node running a Flume logical node handling graph nodes in a Node.js decorator.]
```

The footnote: macro location in the text is exactly where the superscripted footnote marker will be placed in the body text, so it should be inline in the body text paragraph at the proper location, e.g.:

```
* Structured to modelfootnote:[the worst example iis "node": a LAN node configured by a chef node running a Flume logical node handling graph nodes in a Node.js decorator.]
```

I've made the above change to your AsciiDoc text, and all book formats are now building successfully. Please let me know if you encounter any further issues.

Best,
Sanders

**Comment by mrflip** [comment]
Thanks Sanders!
