### ISSUE TITLE
Images uploaded via Git showing up as broken

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#114]
Hi,

I tried uploading a bunch of images into Make: Electronics (see http://ano-atlas2.herokuapp.com/books/1230000000953), but when I preview in HTML, or click Insert Image, I only see the broken image icon except for the one image I uploaded via the web interface.

Thanks,

Brian

**Comment by runemadsen** [comment]
Hey Brian

Yes, this is a known issue. The images don't transfer to Atlas right now, but your book will build with the correct images. This is definitely on the todo list.
- Rune

**Comment by bjepson** [comment]
Thanks, Rune. Unfortunately, I'm getting the "stairstep" placeholder image in my build. Can you have a look at this book? I've added you as a collaborator.

Thanks,

Brian

**Comment by runemadsen** [comment]
Thanks, let me take a look.

**Comment by runemadsen** [comment]
Hey Brian

This is caused by all the images being saved in the "image" folder, but references in the asciidoc as being in the "figs/web" folder. I just changed the first picture in ch01, and it worked. Go take a look and let me know if that doesn't solve your problem

**Comment by bjepson** [comment]
Thanks, Rune. I just caught that error myself and was coming over here to apologize. Sorry about the false alarm!

**Comment by runemadsen** [comment]
No worries at all. It's good to know these things.

**Comment by bjepson** [comment]
Thanks, Rune. Should I not expect the images to show up in HTML preview when they are added via git? Is there any way to get them to appear in the HTML preview? See http://ano-atlas2.herokuapp.com/books/1230000000953/versions/master/editor/ch04.asciidoc/preview for an example.

Also, is there an existing issue that's open for this problem that I can watch?

Thanks,

Brian

**Comment by runemadsen** [comment]
Correct. Right now they don't show up. Go ahead and create an issue. We
know it's an important thing, however not a lot of people are using the
command line, so it hasn't come up a lot.
