### ISSUE TITLE
Figures missing from git (and PDF!), but are there in Atlas

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#115]
Hi,

These figures appear in the HTML preview in Atlas, but not in the PDF.

They also don't show up when I check the project out using git. The two issues are probably related.

http://orm-atlas-prod.s3.amazonaws.com/1230000000237/images/09_FountainPrint1.png
http://orm-atlas-prod.s3.amazonaws.com/1230000000237/images/09_FountainPrint2.png
http://orm-atlas-prod.s3.amazonaws.com/1230000000237/images/09_ml_no_poission.png
http://orm-atlas-prod.s3.amazonaws.com/1230000000237/images/09_ml_poission.png

Thanks,

Brian

**Comment by sandersk** [comment]
Hi Brian,

Yes, looks like there may be an issue with the Image worker process we use for propagating the image files from S3 to Git, where they're used for the ebook builds. An Exception was thrown on all four images listed above, so we'll look into that.

I don't think this is a global problem with image uploads, though, as I just did a test upload of an image on another project, and it propagated to the Git repo successfully.

Sanders

**Comment by bjepson** [comment]
Thanks! I think I'll re-upload those images via git for now.

**Comment by sandersk** [comment]
Hi Brian,

I saw your email that you got a 502 error when trying to upload those images. But when I checked out the repo, I saw them there, and the commit went through successfully:

```
commit 4f37e8b09b8faaaa1aab7e698ef59f6423c7e839
Author: Brian Jepson <bjepson@gmail.com>
Date:   Thu Oct 4 08:52:27 2012 -0400

    added missing images

 images/09_FountainPrint1.png |  Bin 0 -> 2954666 bytes
 images/09_FountainPrint2.png |  Bin 0 -> 2178640 bytes
 images/09_ml_no_poission.png |  Bin 0 -> 224638 bytes
 images/09_ml_poission.png    |  Bin 0 -> 213928 bytes
 4 files changed, 0 insertions(+), 0 deletions(-)

```

So I went ahead and rebuilt the PDF in Atlas, and the images are showing up now. Does everything look OK from your end?

Thanks,
Sanders

**Comment by bjepson** [comment]
It does look good; I deleted that comment about the 502 because I needed to set the HTTP  postBuffer. I thought I had set it on this repo, but I might have done a fresh checkout recently.
