### ISSUE TITLE
Show book title on Atlas Dashboard

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#116]
This is a really minor, really low-priority thing, but I think it would be nice if the Atlas Dashboard page displayed the title of the book you were working on. Oftentimes I get sent a link like this:

http://atlas.labs.oreilly.com/books/1230000000...

And if there's not a cover loaded, I have to go to the Admin tab to find the title.

**Comment by adamwitwer** [comment]
Yeah, agreed. I requested that change in the Atlas UI enhancements task in Asana.

**Comment by sandersk** [comment]
This has been fixed, and book titles are now displayed on the Dashboard.
