### ISSUE TITLE
Push via git hangs after writing

### ISSUE THREAD

**Issue by akaziuna** [MakerPress/atlas-public-feedback#117]
I am working on this book: http://ano-atlas2.herokuapp.com/books/1230000000237

I was able to push my changes via git early this afternoon.  Around 2pm, my pushes started to hang and not complete:

Ceres:newestBookDraft annakaziunasfrance$ git push
Password for 'https://anna@kaziunas.com@atlas-server.oreilly.com': 
Counting objects: 59, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (53/53), done.
Writing objects: 100% (53/53), 197.81 MiB | 17.29 MiB/s, done.
Total 53 (delta 15), reused 1 (delta 0)

I let it go for over a half hour.  I have tried it a few times since, but no change.

**Comment by sandersk** [comment]
Hi Anna,

Do your changes include adding new image files, or are you just making text changes? It's possible that it might take a while to post a bunch of images, as the files are transmitted over HTTP, but text changes should post rather quickly.

I just did a test commit right now to your repo, and confirmed it transmitted successfully, so I don't think there's anything wrong with our Git server at the moment. Could you try doing a "git pull", followed by a "git push" one more time and let us know if you're still unable to post the files.

Best,
Sanders

---

Sanders Kleinfeld
Publishing Technology Engineer
O'Reilly Media Inc.
sanders@oreilly.com
@sandersk

**Comment by akaziuna** [comment]
The changes did include image files, perhaps I was not waiting long enough.  I cloned a new copy before I saw your response.  The text pushed just fine and I have been adding the images a few at a time.  It seems to be working fine now.  Thanks!
