### ISSUE TITLE
Not selecting a build format drops changes to file selections

### ISSUE THREAD

**Issue by mrichardson23** [MakerPress/atlas-public-feedback#118]
If a user makes changes to the "Files to Build" listing, but does not select a format, their changes to the listing are lost when they click the "Build!" button.

Steps to reproduce:
1. Click "Build" on the toolbar to go to build page.
2. Don't select a file format.
3. Change "Files to Build" listing by adding or removing files.
4. Click "Build!" button. An error will appear saying to select a build format.

Expected result:
Changes to the "Files to Build" listing keeps the changes I made.

Actual result:
Changes to the "Files to Build" listing reverts to original settings.

**Comment by sandersk** [comment]
Hi @mrichardson23 

Thanks very much for the error report. We've added this to our bug list and will work on getting this fixed in the next round of Atlas updates.

Best,
Sanders
