### ISSUE TITLE
Cursor greys out after saving

### ISSUE THREAD

**Issue by jcarrott** [MakerPress/atlas-public-feedback#119]
A counter-intuitive thing that's been disrupting my flow.  When I hit "save" I can't just continue typing in my document (weird things happen if I do)--I have to click on the cursor to re-activate it (goes from grey to back to black), then continue typing.  

As someone who saves frequently and compulsively, this drives me nuts.  I end up in the dashboard or some other chapter and have to make my way back to where I was…

Is this something that can be readily fixed?  Thanks much.

**Comment by sandersk** [comment]
Hi @jcarrott 

Sorry for the delayed response. This is a great suggestion, and we will look into whether we can adjust the UI so that focus isn't lost on the editing window when users click Save. Will keep you posted.

Best,
Sanders
