### ISSUE TITLE
500 Error loading a specific chapter

### ISSUE THREAD

**Issue by toddllm** [MakerPress/atlas-public-feedback#120]
Trying to load:
http://ano-atlas2.herokuapp.com/books/1230000000605/versions/master/editor/ch04.asciidoc

gives a 500 error.

The other chapters seem to load fine.

**Comment by runemadsen** [comment]
Thanks Todd. I'm looking at it right now.

**Comment by MakerPress** [comment]
Hey, Rune.  I think it has something to do with a character encoding issues around the single-tick quote.  Todd, just curious if you pasted this markup in from some other editor? 

The weird thing is that I cloned the repo down, removed the weird characters, and tried to push, but still got a 500 error.  However, when I made a new file and pasted it directly into the editor, it works great:

http://atlas.labs.oreilly.com/books/1230000000605/versions/master/editor/ch04_fixed_quotes.asciidoc

Andrew 
----- Original Message -----

**Comment by toddllm** [comment]
Not my chapter. Including my co-author now.

Thanks,
Todd

On Tue, Oct 9, 2012 at 12:57 PM, MakerPress notifications@github.comwrote:

> Hey, Rune. I think it has something to do with a character encoding issues
> around the single-tick quote. Todd, just curious if you pasted this markup
> in from some other editor?
> 
> The weird thing is that I cloned the repo down, removed the weird
> characters, and tried to push, but still got a 500 error. However, when I
> made a new file and pasted it directly into the editor, it works great:
> 
> http://atlas.labs.oreilly.com/books/1230000000605/versions/master/editor/ch04_fixed_quotes.asciidoc
> 
> Andrew
> ----- Original Message -----
> From: Rune Skjoldborg Madsen notifications@github.com
> To: MakerPress/atlas-public-feedback <
> atlas-public-feedback@noreply.github.com>
> Sent: Tue, 09 Oct 2012 12:46:07 -0400 (EDT)
> Subject: Re: [atlas-public-feedback] 500 Error loading a specific chapter
> (#120)
> 
> Thanks Todd. I'm looking at it right now.
> 
> On Tue, Oct 9, 2012 at 12:27 PM, Todd Deshane notifications@github.comwrote:
> 
> > Trying to load:
> > 
> > http://ano-atlas2.herokuapp.com/books/1230000000605/versions/master/editor/ch04.asciidoc
> > 
> > gives a 500 error.
> > 
> > The other chapters seem to load fine.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/MakerPress/atlas-public-feedback/issues/120>.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> ## https://github.com/MakerPress/atlas-public-feedback/issues/120#issuecomment-9269042
> 
> Andrew Odewahn
> Chief Technology Officer
> O'Reilly Media
> 617-460-6693
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MakerPress/atlas-public-feedback/issues/120#issuecomment-9269470.

## 

Todd Deshane
http://todddeshane.net

**Comment by runemadsen** [comment]
Hey Todd

This has been fixed now. I would love to know how those weird characters got in there. Was this added via command-line git? Is he on Windows? Any information would be helpful.

Thanks

**Comment by toddllm** [comment]
I cloned the repo onto a windows machine and used word to edit it, so that
could be related.
I think AndyO might have added the text that was causing issues, but maybe
it was just the way word dealt with them?

Thanks,
John

On 9 October 2012 18:07, Todd Deshane deshantm@gmail.com wrote:

> Not my chapter. Including my co-author now.
> 
> Thanks,
> Todd
> 
> On Tue, Oct 9, 2012 at 12:57 PM, MakerPress notifications@github.comwrote:
> 
> > Hey, Rune. I think it has something to do with a character encoding
> > issues around the single-tick quote. Todd, just curious if you pasted this
> > markup in from some other editor?
> > 
> > The weird thing is that I cloned the repo down, removed the weird
> > characters, and tried to push, but still got a 500 error. However, when I
> > made a new file and pasted it directly into the editor, it works great:
> > 
> > http://atlas.labs.oreilly.com/books/1230000000605/versions/master/editor/ch04_fixed_quotes.asciidoc
> > 
> > Andrew
> > ----- Original Message -----
> > From: Rune Skjoldborg Madsen notifications@github.com
> > To: MakerPress/atlas-public-feedback <
> > atlas-public-feedback@noreply.github.com>
> > Sent: Tue, 09 Oct 2012 12:46:07 -0400 (EDT)
> > Subject: Re: [atlas-public-feedback] 500 Error loading a specific chapter
> > (#120)
> > 
> > Thanks Todd. I'm looking at it right now.
> > 
> > On Tue, Oct 9, 2012 at 12:27 PM, Todd Deshane notifications@github.comwrote:
> > 
> > > Trying to load:
> > > 
> > > http://ano-atlas2.herokuapp.com/books/1230000000605/versions/master/editor/ch04.asciidoc
> > > 
> > > gives a 500 error.
> > > 
> > > The other chapters seem to load fine.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/MakerPress/atlas-public-feedback/issues/120>.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > ## https://github.com/MakerPress/atlas-public-feedback/issues/120#issuecomment-9269042
> > 
> > Andrew Odewahn
> > Chief Technology Officer
> > O'Reilly Media
> > 617-460-6693
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/MakerPress/atlas-public-feedback/issues/120#issuecomment-9269470.
> 
> ## 
> 
> Todd Deshane
> http://todddeshane.net

## 

## John Garbutt MA (Cantab) MBCS

13 Greenhaze Lane
Great Cambourne
Cambridge

## CB23 5EF

07903 211430

## www.johngarbutt.com

**Comment by sandersk** [comment]
Hi John,

I'm going to go ahead and close this ticket, as the problem has been resolved. Could you please reopen if you encounter any further issues? We're continuing to work on making Atlas more robust in handling different character encodings, so hopefully that will help prevent similar issues in the future.

Thanks,
Sanders
