### ISSUE TITLE
Text wrapping in Atlas

### ISSUE THREAD

**Issue by myarbrough** [MakerPress/atlas-public-feedback#121]
In Ch 06 of Kinect Hacks (http://ano-atlas2.herokuapp.com/books/1230000000841/versions/master/editor/ch06.asciidoc), if you scroll down past line 280, the text starts auto-wrapping before the edge of the text box. It's disruptive because I can't tell which breaks are actual line breaks and which are not. Otherwise, the PDF seems to render just fine.

Thanks!
Mel

**Comment by sandersk** [comment]
Hi Mel,

Great catch! I took a look at the Chapter 6 AsciiDoc source file. After line 280, the text is actually not auto-wrapping before the edge of the text box; there actually were line breaks inserted into the text at those spots by the author. 

The good news is that these extra line breaks within body paragraphs are considered to be "nonsignificant" here, and are ignored by the toolchain when converted to PDF and the other ebook formats. So, as you noticed, they have no effect on the PDF output.

So, from a markup and toolchain perspective, the Chapter 6 text is fine as is, and you can ignore any extra linebreaks that you spot in body paragraphs.

Let me know if you have any questions about this, or if you do spot any problems in the PDF.

Thanks,
Sanders
