### ISSUE TITLE
Kinect Hacks: Errors when creating PDF

### ISSUE THREAD

**Issue by myarbrough** [MakerPress/atlas-public-feedback#122]
Hello!

After Ron made a few edits to the stylesheet today, I noticed the errors below when making a PDF:

AHFCmd :WARNING: Error Level : 2
AHFCmd :WARNING: Error Code  : 12813 (320D)
AHFCmd :WARNING: Invalid property value: min-height: auto;
AHFCmd :WARNING: Line 988, Col 16, /usr/share/dcps/pdfrenderer/css/series/hacks/hacks.css

The PDF still built, but I thought someone would like to take a look.

Thanks!
Mel

**Comment by adamwitwer** [comment]
Thanks Mel. I moved this over here:

https://github.com/oreillymedia/pdfrenderer/issues/184

and assigned to Ron.
