### ISSUE TITLE
When adding image via git push, raw image data shows up in Changes tab

### ISSUE THREAD

**Issue by mrichardson23** [MakerPress/atlas-public-feedback#124]
I added a JPG via a git push and under the Changes tab, it showed all the raw bytes in the file as added lines.

**Comment by sandersk** [comment]
Hi Matt,

We recently have suppressed binary data from the Changes tab, so you should no longer see the raw bytes for things like image and PDF files that you add to the repo. I'm going to go ahead and close this ticket, but please do reopen and let us know if you see any additional problems with the Changes tab.

Thanks,
Sanders
