### ISSUE TITLE
HTTP request failing

### ISSUE THREAD

**Issue by rjaillet** [MakerPress/atlas-public-feedback#127]
My attempts to push and pull to the repo of 1230000000729 are failing. One of our IT guys looked at the issue briefly and we both think it's on the Atlas end, probably due to the recent git server switch.

Here's the error:

```
$ git pull 
error: The requested URL returned error: 500 while accessing https://rjaillet%40safaribooksonline.com@atlas-server.oreilly.com/git/1230000000729.git/info/refs
fatal: HTTP request failed
```

When I try to just go to https://atlas-server.oreilly.com/git/1230000000729.git in the browser, I get a page saying "Not found". Not sure if that's relevant.

Thanks!

**Comment by runemadsen** [comment]
Thanks. I'm looking into this.

**Comment by rjaillet** [comment]
Update... This is the new error I'm getting:

```
$ git pull
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
```

**Comment by runemadsen** [comment]
Thanks. I'll hopefully be able to resolve this soon. Stay tuned.

**Comment by rjaillet** [comment]
Thanks for the quick action.

Just so you know, I had a similar (but not identical) Atlas problem in the past that we figured out was due to "hairpinning." I'm not clear on the details. We don't think that's the issue this time, but if you can't seem to figure out the source of this problem, we can revisit it.

**Comment by odewahn** [comment]
Hi.  This could be related to the size of the post buffer, which can sometimes be an issue for large repositories.  Try running this command from the command line and give it another shot:

git config http.postBuffer 524288000

Andrew

----- Original Message -----

**Comment by runemadsen** [comment]
Yeah, it fails on my tiny repo, so I'm pretty sure it's something on the server.

**Comment by runemadsen** [comment]
This should be fixed now. Please confirm that it's working.

**Comment by rjaillet** [comment]
Success! Thank you for the speediness.
