### ISSUE TITLE
Hung PDF build

### ISSUE THREAD

**Issue by clintongormley** [MakerPress/atlas-public-feedback#128]
Hiya

My book ( http://ano-atlas2.herokuapp.com/books/1230000000825/builds ) has stopped building as of commit 77c1ef14423cde55df2e6962811d438cae5f2515

There is no error log, the builds just hang.

Any idea what the problem is?

ta

**Comment by sandersk** [comment]
Hi Clinton,

There was an issue with a temp checkout of your book we had on our build server. I cleared the cache, and was able to rebuild your PDF successfully. You should be able to download it from the dashboard now.

Please let us know if this problem recurs.

Thanks,
Sanders

**Comment by clintongormley** [comment]
Many thanks @sandersk

**Comment by runemadsen** [comment]
Thanks Sanders. I'm looking into why this happened.
