### ISSUE TITLE
Undefined, Nan in the changes log

### ISSUE THREAD

**Issue by clintongormley** [MakerPress/atlas-public-feedback#129]
Hiya

In the first line of each commit in the changes log,  it is showing the commit message then: `undefined NaN, NaN, NaN:NaNPM`

Not sure what those are supposed to refer to, but they're certainly not right :)

http://ano-atlas2.herokuapp.com/books/1230000000825/versions/master/changes

**Comment by runemadsen** [comment]
Hey Clinton

Weird, I don't see that. Do you mind going here and pasting the link you see in the box? Then I can check out your system specs and see what is causing this:

https://aboutmybrowser.com
- Rune

**Comment by clintongormley** [comment]
Heya @runemadsen 

I tried in Chrome, and that works fine.  In Firefox 14 https://aboutmybrowser.com/MRWoNLQL , I get this error in the console:

```
TypeError: t.replace is not a function
```

**Comment by runemadsen** [comment]
Better late than never, this has been fixed now!
