### ISSUE TITLE
Italic style not working for Vintage Tomorrows

### ISSUE THREAD

**Issue by courtneynash** [MakerPress/atlas-public-feedback#130]
I don't know if it's the new trade interior or what, but no builds of Vintage Tomorrows are rendering italics at all. I'm simply using the _formatting_, is there something I'm missing?

**Comment by sandersk** [comment]
Hi Courtney,

No, this appears to be an issue specific to the trade stylesheets. I will pass along this bug report to the appropriate folks, and we'll get a fix in place.

Thanks for catching this,
Sanders

**Comment by courtneynash** [comment]
Thanks!

**Comment by jhosman** [comment]
The italics in the trade stylesheet have been fixed and are now working correctly.
