### ISSUE TITLE
Code Wrapping

### ISSUE THREAD

**Issue by whyisjake** [MakerPress/atlas-public-feedback#134]
Is there a way to make it so that code wraps to a new line? I have a couple of long strings, and it would be nice if they wrapped to a new line.

**Comment by adamwitwer** [comment]
Hi @whyisjake. I can add an override so that long code lines wrap automatically throughout the book. So you want me to add that, or are you looking for more granular control?

**Comment by whyisjake** [comment]
That'd be great, I don't think I need any more granular control.

**Comment by adamwitwer** [comment]
Cool. Okay, it's all set. When you next pull from git, you'll notice that I added the override to tools/oneoffs/oneoff.css (which affects the PDF format only). I tested it in Atlas, and it looks like it is working as expected, but please let me know if anything looks amiss.

**Comment by whyisjake** [comment]
Thanks, looks great.
