### ISSUE TITLE
Not sure the stats are updating after git migration

### ISSUE THREAD

**Issue by JohnGarbutt** [MakerPress/atlas-public-feedback#135]
It seems like recent commit are not showing up in the stats.
The status say they have been updated, but the last commit seems a long way in the past now, relative to what has actually happened since then.

**Comment by JohnGarbutt** [comment]
Also, probably a feature request, but it doesn't say about aggregate lines added and removed per collaborator.

**Comment by runemadsen** [comment]
Hey John

Thanks for the feedback. What book are you looking at? If you send the link I can take a look.
- Rune

**Comment by JohnGarbutt** [comment]
Sure, I was comparing this screen:
http://ano-atlas2.herokuapp.com/books/1230000000605/stats
With this one:
http://ano-atlas2.herokuapp.com/books/1230000000605/versions/master/changes

**Comment by MakerPress** [comment]
Hi, John.  Computing the stats is a pretty costly process, so the "Stats" tab isn't updated on each commit.  Rather, it only updates when you build the book.  So, it will be out of sync until you build, at which point all the stats will be recomputed. 

Of course, there still might be an issue, but you might try building the project and seeing if the stats are inline with what you expect.

Andrew

----- Original Message -----

**Comment by runemadsen** [comment]
Thanks. The commits will only update when you build the book. We should probably be more clear about that. So try to build it as a PDF and see if it doesn't update.

**Comment by JohnGarbutt** [comment]
The commit list seems up to date, it is the stats that seem behind. I have built the book recently, but I have set it off again. At the moment only the pdf seems to build, the others seem to fail. I don't know if that is related to the stats not getting updated?
