### ISSUE TITLE
Any way to enable remarks/showcomments?

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#136]
Hi,

I tried putting :showcomments: at the top of chapter 1 in http://ano-atlas2.herokuapp.com/books/1230000000237, but it doesn't make comments appear in the book.

But when I generate a local preview with asciidoc, comments that start with // appear as remarks in the generated document.

Thanks,

Brian

**Comment by sandersk** [comment]
Thanks for bringing this to our attention, Brian. We do have a mechanism in our PDF-generation toolchain for specifying whether comments should be displayed or not, but we don't yet have it hooked into the Atlas UI.

Rune, would love to get your advice on the best way to do this, but what I'm thinking is that we could maybe add a checkbox to the Build tab called "Display comments in PDF", and then if this param could be passed to pdf_worker.rb, I'd just have to change one line of code to pass it into to the PDF generation.

Brian, in the meantime, I'll cut you a PDF with comments and send it to you via email.

Sanders

**Comment by runemadsen** [comment]
Good idea Sanders. Maybe I could make something general, so we could pass options to the workers? So if this comes up again for another option, it would be really easy to do?

**Comment by sandersk** [comment]
Ooh, great idea, Rune! I'm sure there will be other options we'll want to pass to the workers in the future.

**Comment by runemadsen** [comment]
Great. I'll put it on my list :-)

**Comment by odewahn** [comment]
You're gonna need a bigger sheet of paper...  ;)

But, passing options to the workers, perhaps with a helpful modal form like you created for the buttons or the metadata stuff, is the right way to go.

Andrew

----- Original Message -----

**Comment by bjepson** [comment]
Howdy,

I was wondering if this feature was any closer to becoming a reality? Is there anything I could do in a oneoff file or some other kind of workaround to get comments to appear in the meantime?

Thanks,

Brian

**Comment by adamwitwer** [comment]
Hi Brian,

Not any closer in Atlas, I'm afraid. You can include the comments if you build on touchstone and use the `--show-comments` flag. Not sure if that helps?

Adam

**Comment by bjepson** [comment]
Thanks, Adam. I'm looking for a solution that would make my comments visible even in the PDFs that the authors generate. Is there any other facility for adding editorial or reviewer comments in the works?
- Brian

**Comment by sandersk** [comment]
Hi Brian,

Actually, I can kludge this for now with a oneoff XSL for you. I added a oneoff.xsl file in tools/oneoffs directory of the repo. It contains the following line:

```
<xsl:param name="show.comments" select="1"/>
```

Just change select="1" to select="0" when you want to turn the comments back off.

Thanks,
Sanders

**Comment by sandersk** [comment]
Oh, actually, I also have to make a slight tweak to our backend as well, so it won't work just yet, but should have that in place later today.

Sanders

**Comment by bjepson** [comment]
Oh cool! That will be wonderful, thanks!

**Comment by sandersk** [comment]
Hi Brian,

OK, that additional backend handling is now in place so that AsciiDoc comments will now be displayed in the PDF output for this book.

There's one more caveat, though, which is that only the single-line syntax for comments will be rendered--e.g. comments like this:

```
// Comment
// Another comment
// And so on
```

But not multiline block comments like this:

```
////
Comments
More comments
Yet More comments
////
```

Because asciidoc.py drops the multiline block comments on conversion to DocBook.

Hope this helps. As previously mentioned, we're still planning to add additional functionality to the Atlas UI with toggle-able options to let you turn on/off comment display in PDF output, but in the meantime, hopefully this oneoff method will serve that need.

Let me know if you have any questions or encounter any issues.

Thanks,
Sanders

**Comment by bjepson** [comment]
Thanks! It's working great with this.
- Brian

**Comment by katehartman** [comment]
Looks like this idea was floated a while back, but it would indeed be awesome if authors could select whether or not to include comments on the Build page!

**Comment by sandersk** [comment]
Hi @katehartman,

Yes, this is indeed already on our feature to-do list. We're working on the next release of Atlas right now, so will try to see if we can get this enhancement rolled out with it :)

In the meantime, if you have a project where you want comment display enabled in builds, let me know, and I can  do that on the backend for you.

Thanks,
Sanders
