### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by nanliu** [MakerPress/atlas-public-feedback#139]
We have an issue in Chap. There's a problem building the section after features. I can narrow down to about 5 lines, but all Atlus shows is:

http://ano-atlas2.herokuapp.com/books/223/jobs/13383

"We're sorry, but something went wrong. If you think this is a bug, please report it"

This has been rather unhelpful since I can't make any progress on fixing the issue without any more insight.

**Comment by runemadsen** [comment]
Thanks! I'm looking into it right now. I'll post updates here.

**Comment by runemadsen** [comment]
This has been fixed now. Let me know if you keep seeing it.

**Comment by sandersk** [comment]
Hi Nan,

I'm going to go ahead and close this issue, as we believe it's now resolved. Could you please reopen this ticket and let us know if you encounter further issues?

Thanks,
Sanders
