### ISSUE TITLE
Public key upload/management?

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#14]
When I interact with git at the command-line, it requests my password each time. I can put it into my ~/.netrc, but that's insecure. Could you add a way to manage SSH public keys in the Atlas UI?

Thanks,

Brian

**Comment by sh1mmer** [comment]
Bump.

**Comment by JohnAlbin** [comment]
Indeed, having the ability to add a SSH public key into the system would make using Git from my local computer a breeze.

**Comment by davidsklar** [comment]
I would really, really like this. Pretty please.

**Comment by davidsklar** [comment]
Any indication of where this is on the priority list? It gets in my way many times a day.

**Comment by odewahn** [comment]
Hi, David. I asked around, and here's a hack that Brian Jepson figured out:

On Windows, I just cache the password, and on the Mac, I Use the osxkeychain credential helper: 

http://stackoverflow.com/questions/5343068/is-there-a-way-to-skip-password-typing-when-using-https-github

There is a credential helper for Windows, but I'm not sure it works with Cygwin (which is what I'm using). It does come with GitHub for Windows, though: https://help.github.com/articles/set-up-git#platform-windows

It's not SSH, but it might help with passwordless access over HTTP.

----- Original Message -----

**Comment by davidsklar** [comment]
Thanks, Andrew! That is very helpful. I am on Mac (+ Linux) so the keychain helper will be useful. I will also see if I can wire it up to pass (http://zx2c4.com/projects/password-store/) which I use as my password store.

**Comment by Jammerwoch** [comment]
Bump

**Comment by zaremba** [comment]
The new version of Atlas (currently in beta) now supports SSH. Thanks to everyone for the feedback!

**Comment by RoUS** [comment]
Definitely +1 for having SSH.  Of course, things are tied to the eddress in Atlas; would changing the eddress break everytHing?

**Comment by sandersk** [comment]
Hi @RoUS, projects in the current version of Atlas will continue to use https, and addresses will not change. Projects in the new Atlas release will have different addresses for SSH access.

If you're interested in moving an existing project to the new Atlas release, please let your editor know.
