### ISSUE TITLE
Nov 12, 2012 Logged into Atlas and it is not listing my files.

### ISSUE THREAD

**Issue by raywilson007** [MakerPress/atlas-public-feedback#143]
Hi

There is something up with Atlas today. It is not showing me my files and kind of acting like I was never there.

Thanks

Ray

**Comment by runemadsen** [comment]
Hey Ray. Try again. Should work now. I had a few problems with the git server.

**Comment by raywilson007** [comment]
Awesome, it's back on the air. Thanks

Ray
