### ISSUE TITLE
Changes tab acting weird

### ISSUE THREAD

**Issue by jhosman** [MakerPress/atlas-public-feedback#144]
Hi,

The changes tab is intermittently working for me. Sometimes it hangs, sometimes crashes with an unresponsive script warning, and when it does work it refreshes on its own to show all change times/dates with the text " undefined NaN, NaN, NaN:NaNPM". Any idea what's going on with it?

I've noticed the behavior on these 2 pages:

http://atlas.labs.oreilly.com/books/1230000000285/versions/master/changes

http://atlas.labs.oreilly.com/books/1234000000134/versions/master/changes

Thanks!

**Comment by runemadsen** [comment]
Hey @jlhosman. 

We have a small bug that will show content of some binary files, if added via Git. This will make the changes tab stall.

The NaN problem is another small bug, that only happens in Firefox/IE. 

Both of these things are on our list of things to fix. Let me know if you see any other things.

**Comment by jhosman** [comment]
Oh okay, thanks Rune!

**Comment by runemadsen** [comment]
No, thank you! I'll do my best to fix it as soon as possible.

**Comment by sandersk** [comment]
Hi Jess,

Rune recently fixed the issue with the binary files and the changes tab, so that problem shouldn't recur anymore. I'll go ahead and close this ticket, and make a separate ticket for the NaN issue in Firefox/IE.
