### ISSUE TITLE
adding revision history section to admin>metadata

### ISSUE THREAD

**Issue by zaremba** [MakerPress/atlas-public-feedback#145]
Can we add a revision history section to admin>metadata gui to link to the docinfo.xml? It would probably fit best next to the edition section.

``` xml
<revhistory>
    <revision>
        <date>2012-07-10</date>
        <revremark>First release</revremark>
    </revision>
</revhistory>
```

**Comment by sandersk** [comment]
Good idea, Adam. I've added this to the enhancements list.

Thanks,
Sanders
