### ISSUE TITLE
Unable to access same repo as author

### ISSUE THREAD

**Issue by fluxama** [MakerPress/atlas-public-feedback#146]
I'm not quite sure what's going on here, but here's a summation:
1. I set up a book for an author and invited him here:
   
   http://ano-atlas2.herokuapp.com/books/1234000000142
2. The authors were working in their own git repo, and he went and checked the material in to the URL he says he was provided when he was invited:
   
   http://ano-atlas2.herokuapp.com/books/1234000000206/

This throws a 404 error when I try to access it. Apparently the author can see the repo. Any ideas?

Thanks in advance!

**Comment by odewahn** [comment]
Hi, Shawn.  I didn't see the author listed as a collaborator on 1234000000142 -- it looks like it's only you:

So, I added you to the repo he set up, which is 1234000000206.  You should see it show up in the "Your Books" list.

Also, a few minor observations:
- You should change the file extentionsions to asciidoc (not asc), which you can do by either renaming them in git and repushing, or changing them in Atlas in the filename box and pulling to the local copy.
- If you add [source, cpp] in front of the code listings you'll turn on syntax highlighting in the PDFs and epubs

Let us know if you have other problems!

Andrew

----- Original Message -----

**Comment by fluxama** [comment]
Ah, he set up his own book; thanks Andrew.

Shawn

On Nov 14, 2012, at 8:46 PM, Andrew Odewahn wrote:

> Hi, Shawn. I didn't see the author listed as a collaborator on 1234000000142 -- it looks like it's only you:
> 
> So, I added you to the repo he set up, which is 1234000000206. You should see it show up in the "Your Books" list.
> 
> Also, a few minor observations:
> - You should change the file extentionsions to asciidoc (not asc), which you can do by either renaming them in git and repushing, or changing them in Atlas in the filename box and pulling to the local copy.
> - If you add [source, cpp] in front of the code listings you'll turn on syntax highlighting in the PDFs and epubs
> 
> Let us know if you have other problems!
> 
> Andrew
> 
> ----- Original Message -----
> From: Fluxama notifications@github.com
> To: MakerPress/atlas-public-feedback atlas-public-feedback@noreply.github.com
> Sent: Wed, 14 Nov 2012 20:31:30 -0500 (EST)
> Subject: [atlas-public-feedback] Unable to access same repo as author (#146)
> 
> I'm not quite sure what's going on here, but here's a summation:
> 1. I set up a book for an author and invited him here:
> 
> http://ano-atlas2.herokuapp.com/books/1234000000142
> 1. The authors were working in their own git repo, and he went and checked the material in to the URL he says he was provided when he was invited:
> 
> http://ano-atlas2.herokuapp.com/books/1234000000206/
> 
> This throws a 404 error when I try to access it. Apparently the author can see the repo. Any ideas?
> 
> Thanks in advance!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MakerPress/atlas-public-feedback/issues/146
> 
> ## 
> 
> Andrew Odewahn
> Chief Technology Officer
> O'Reilly Media
> 617-460-6693
> —
> Reply to this email directly or view it on GitHub.

---

Shawn Wallace
O'Reilly Media
(401) 835-7550 cell
swallace@oreilly.com
www.fluxly.com
follow @fluxly
