### ISSUE TITLE
Build page doesn't hold list of files (book.asciidoc)

### ISSUE THREAD

**Issue by mrflip** [MakerPress/atlas-public-feedback#147]
On 1230000000073 (Big Data for Chimps), the build page doesn't show the list of included files any more -- it used to be pre-populated. 

This started today (it worked a couple days ago).

**Comment by runemadsen** [comment]
Thanks @mrflip. We're aware of this, and I'm working to fix it. I'll post an update when it's fixed.

**Comment by runemadsen** [comment]
This should be fixed now. Let me know if you keep experiencing problems.

**Comment by sandersk** [comment]
Hi @mrflip, I'm closing this ticket as we believe the problem is now resolved. Please reopen and let us know if you experience this problem again.

Thanks,
Sanders
