### ISSUE TITLE
Getting 500 Errors when trying to sync...

### ISSUE THREAD

**Issue by whyisjake** [MakerPress/atlas-public-feedback#148]
error: The requested URL returned error: 500 while accessing https://jspurlock%40oreilly.com@atlas-server.oreilly.com/git/1230000000673.git/info/refs
fatal: HTTP request failed
 (256)

**Comment by whyisjake** [comment]
Tried both the command line, and the github app.

**Comment by whyisjake** [comment]
Also can't do a pull or anything like that...

**Comment by mrichardson23** [comment]
I'm having the same issue, so +1 on this. Jake, did anything work for you? I'm working on the web-based side for now but need to modify some image files through git.

**Comment by runemadsen** [comment]
Thanks, I'll take a look right away. I'll update you here.

**Comment by runemadsen** [comment]
The problem should be fixed now. Let me know if you're still experiencing any problems.

**Comment by whyisjake** [comment]
Yeah, working now. Thanks.

**Comment by mrichardson23** [comment]
This issue has cropped up for me again.

**Comment by runemadsen** [comment]
Hi Matt. Try again. We're having problems with some monster repos that bring down our server. Should be back up.

**Comment by mrichardson23** [comment]
Great, thanks. I was able to push, but now it looks like our files are gone in this book, when viewed via the web:
http://ano-atlas2.herokuapp.com/books/1230000000649

**Comment by mrichardson23** [comment]
.....and it's back. Disregard.

**Comment by runemadsen** [comment]
Cool, thanks. And sorry for this. We're working on it.
