### ISSUE TITLE
search functionality within book files?

### ISSUE THREAD

**Issue by zaremba** [MakerPress/atlas-public-feedback#149]
Is it possible to add a search functionality to Atlas to search within the whole book file currently displayed? Apparently the Chrome browser search can do this, but in Firefox the browser search only seems to search the part of the book file displayed in the window.

So for example, if i open ch02.asciidoc and search for "Figure 2-15", firefox won't find it because it is not displayed in in the window at the top of the chapter file.

**Comment by jhosman** [comment]
This feature does actually exist, but you have to make sure to click your cursor into the text window in Atlas first. Then if you press command+f, it should bring up a special search dialog box in Atlas instead of using the browser's find feature. It does seem a little obscured though. Would it be possible to make this more transparent?

Thanks!

**Comment by kristenORM** [comment]
+1 on improving the search feature...some things on my wishlist:

-A search-and-replace function (if feasible in a web interface)
-Right now, the window disappears after finding the next instance of my search term. But if that isn't the one I'm searching for (say, the phrase appears multiple times or I entered a typo), I have to reopen the Find window and try try again. Is there any way we can get the search window to stick around until we are actually done using it?
-On that note, a "search term not found" message at the bottom of the window would be lovely!

**Comment by adamwitwer** [comment]
Hey Kristen -- Here's one tip that may help. If you hit command-G, your last search will repeat. Or command-shift-G to repeat your last search going up in the document. Not exactly what you asked for, but maybe it will help speed things up a bit.
