### ISSUE TITLE
Back-compatibility of /images directory

### ISSUE THREAD

**Issue by nelliemckesson** [MakerPress/atlas-public-feedback#151]
It would be cool if we could maintain the legacy naming convention for image folders, to minimize pain during back-conversions of older titles. The pre-Atlas naming convention for directories of images was "figs".  Or if we could build it so it supports both folders named "images" and "figs", maybe that would work?

**Comment by adamwitwer** [comment]
+1 

The builds seem to work just fine if the files are in a figs/ directory, but the images will show up on Chimera only if the directory is named images/. We'll need more flexibility there eventually.

**Comment by runemadsen** [comment]
I can easily add the /figs directory to the pool of stuff that gets uploaded to Chimera. However, this will upload everything, even giant images only meant for print books. Maybe this is not a problem though?

**Comment by adamwitwer** [comment]
I think that would be okay. We've started using a single set of files for everything (high-res images that work well for both print and retina screens).

Nellie, when we port old books into Atlas, we should just make sure to not include the old PDF image files of yore.

**Comment by nelliemckesson** [comment]
cool thanks guys. cc'ing @sarahs and @jlhosman for an early heads up. I'll work with them to put together an "official process" for importing old books and their figs.

**Comment by jhosman** [comment]
Hi Rune,

Just wondering if this has been implemented yet, or if we should continue putting the figs in an /images dir for now.

Thanks!
Jess

**Comment by runemadsen** [comment]
This has currently not been implemented, but it shouldn't take long to do.
I can look at it tomorrow. I quick fix is putting it in /images, yes.

**Comment by jhosman** [comment]
Hi Rune,

Sorry to bug you about this one again. Just wanted to check on the status of this, since this week we've implemented a new process that will entail moving over a lot more books to Atlas that have a figs/ dir (author updates to already published books).

Thanks!
Jess

**Comment by runemadsen** [comment]
Hi @jlhosman.

Thanks for checking up on it. We're working on a new release that will make this a lot easier. We will remove the need for having all images in /images, so that will hopefully take care of your problems.
