### ISSUE TITLE
How to See Warnings When Build Job Doesn't Fail

### ISSUE THREAD

**Issue by mrichardson23** [MakerPress/atlas-public-feedback#153]
I had a build job fail because of an error. When looking at the error messages, I noticed a bunch of warnings that have existed, but I wasn't aware of them until the error stopped the job from happening. Is there a way I can see the warnings on a build when there's no critical error?

**Comment by runemadsen** [comment]
That's a great idea. Right now we don't bubble that stuff to the UI, but we definitely could. I'll put it on the feature list.
