### ISSUE TITLE
Error when cloning: RPC failed; result=22, HTTP code = 502

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#154]
Hi,

I'm trying to clone https://bjepson%40oreilly.com@atlas-server.oreilly.com/git/1230000000669.git but it fails with the following errors:

error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly

Thanks,

Brian

**Comment by runemadsen** [comment]
Thanks Brian. Investigating.

**Comment by runemadsen** [comment]
Ahh, this is the giant, giant encyclopedia book. We're having some problems with  +1gb repos, as it kills our git server. @sandersk @adamwitwer how are we handling this right now? Any suggestions?

**Comment by odewahn** [comment]
Try running this command on your git client:

git config http.postBuffer 524288000

Git restricts the size of the HTTP buffer to 2MB by default. If you have a repo with lots of images, though, you might need a bigger buffer, as described here:"

http://stackoverflow.com/questions/2702731/git-fails-when-pushing-commit-to-github

We should watch the git server and see if it croaks after this.

Andrew

----- Original Message -----

**Comment by bjepson** [comment]
You need to have an existing repo to execute that git config command, but I did try it with this command:

git -c http.postBuffer=524288000 clone https://bjepson%40oreilly.com@atlas-server.oreilly.com/git/1230000000669.git

But that's the post buffer (stuff you send to the server), right? Would it be problematic to remove the large PDFs that are clogging things up or to move them to another location?

**Comment by adamwitwer** [comment]
> You need to have an existing repo to execute that git config command

Really? I thought it was a one-time config change to your git client. But maybe not.

Give me a sec. I'm checking on the PDFs now. Just want to make sure we have them archived elsewhere.

**Comment by bjepson** [comment]
Thanks; yeah, it's a per-repo config:

$ git config http.postBuffer 524288000
error: could not lock config file .git/config: No such file or directory

I wonder if there's a way to make it global?

**Comment by odewahn** [comment]
Hmmm -- maybe try something like this:

$ mkdir my_repo
$ cd my_repo
$ git init
$ git remote add atlas https://bjepson%40oreilly.com@atlas-server.oreilly.com/git/1230000000669.git
$ git config http.postBuffer 524288000
$ git pull atlas master

Andrew

----- Original Message -----

**Comment by adamwitwer** [comment]
I think Andrew's instructions will work, but I've gone ahead and moved the huge PDFs to another location and left a README.

**Comment by runemadsen** [comment]
Oh, to make this a global config add --global in the calls:

git config --global http.postBuffer 524288000

**Comment by bjepson** [comment]
Thanks! Unfortunately, I'm still receiving the same error when I try git clone. I'm also getting it when I try Andrew's suggestion.

**Comment by bjepson** [comment]
Howdy,

I was wondering if you had any suggestion on this; I need to check the repo out and I'm still getting this error (I don't remember what I did last time; I think I might have gotten the file(s) I needed some other way).

I get this error whether I'm on my computer or on touchstone.

Thanks,

Brian

**Comment by runemadsen** [comment]
Hi Brian

We've been having a few problems with the git server this morning, and I'm still trying to resolve them now. That might be the problem. I'll update the issue when I know more.

**Comment by runemadsen** [comment]
Brian, the problems have been fixed now. Give it a try and let me know if you're still seeing this.

**Comment by bjepson** [comment]
Hi Rune,

I still am getting this error:

$ git clone https://atlas-server.oreilly.com/git/1230000000669.git
Cloning into '1230000000669'...
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
- Brian

**Comment by adamwitwer** [comment]
I put this book on GitHub at one point:

https://github.com/oreillymedia/Encyclopedia_of_Electronic_Components

May make more sense to use that + touchstone for builds. I believe I put it up _after_ the book went to press.

**Comment by bjepson** [comment]
Thanks, Adam. Now I remember; that was the workaround. Should we delete the Atlas repo and update the old SVN's !README_files_moved to point to github?

Can any of you see what's in the Atlas repo? Maybe those old PDFs are still there—deleting those from Atlas might be an alternative.

**Comment by adamwitwer** [comment]
Hi Brian,

Working on this. I actually do have a checkout via SSH, but the keys have changed and I have to fix that. I'll make sure that the GitHub repo is representative of the most current version of what's in Atlas, and then I'll remove the files from Atlas and leave a README. More soon, and thanks for your patience!

**Comment by adamwitwer** [comment]
Okay, this is done. The GitHub repo is up to date with the latest files. I've removed the files from the Atlas git repo and left a README. It's pretty huge. I'm cloning the GitHub repo now and we're at 2 gigs and counting.

Anyway, I hope this works for you, Brian. Please reopen if you have any problems.
