### ISSUE TITLE
error 500 swap file

### ISSUE THREAD

**Issue by gerdmiske** [MakerPress/atlas-public-feedback#156]
Looks like I generated a swap file at https://gerd%40oreilly.de@atlas-server.oreilly.com/git/1234000000314.git

I'm not able to open the .ch02.asciidoc.swp file and got error 500

Gerd

**Comment by runemadsen** [comment]
Hi @gerdmiske 

Do you just want to delete the file? Let me know and I can do it.

Also, do you know how this happened? Was it something that happened on our end?
- Rune

**Comment by gerdmiske** [comment]
Hi Rune,

Am 27.11.2012 17:46, schrieb Rune Skjoldborg Madsen:

> Hi @gerdmiske https://github.com/gerdmiske
> 
> Do you just want to delete the file? Let me know and I can do it.

That would be good if you could delete the swap file.

> Also, do you know how this happened? Was it something that happened on 
> our end?

I think it was my fault. I guess I checked in the files at the 
repository as one of the files was still open at my local version ;-(

Best,

Gerd

> ```
> * Rune
> ```
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MakerPress/atlas-public-feedback/issues/156#issuecomment-10765495. 

## 

Gerd Miske, O'Reilly Verlag GmbH&  Co.KG Balthasarstr.81  50670 Koeln, Germany
Registergericht Koeln, HRA 13894, Geschaeftsfuehrer: Timothy O'Reilly, Elke Hansel
Tel. 0221-973160-20 Fax.:0221-973160-8

http://www.oreilly.de

Verlagsblog: http://community.oreilly.de/blog/
Twitter: http://twitter.com/OReilly_Verlag
Facebook: http://www.facebook.com/oreilly.de
Google+:  http://bit.ly/googleplus_oreillyverlag

**Comment by runemadsen** [comment]
Thanks, and sorry for the wait. I've now deleted the file. Let me know if you run into other problems.

**Comment by sandersk** [comment]
Hi Gerd,

I'm going to go ahead and close this ticket. Please reopen if you still encounter any problems, or need any other files removed.

Thanks,
Sanders
