### ISSUE TITLE
This might not be the place for it, but I can't access my book in Chimera. Any ideas?

### ISSUE THREAD

**Issue by whyisjake** [MakerPress/atlas-public-feedback#157]

**Comment by sandersk** [comment]
Hi Jake,

Which book can't you access? We'll take a look.

Sanders

**Comment by whyisjake** [comment]
The Bootstrap book...

**Comment by sandersk** [comment]
Hi Jake,

Sorry for the delayed response. We recently released some software updates that I think likely resolved the problem for you. Are you still unable to access your Bootstrap book in Chimera? If so, let us know.

Thanks,
Sanders
