### ISSUE TITLE
Unable to add Figures in a Single Git Push

### ISSUE THREAD

**Issue by tobrien** [MakerPress/atlas-public-feedback#158]
One thing, I noticed this happened when I was trying to push about 20 MB of figures I have in the existing book:

```
tmac:maven-tdg Tim$ git push oreilly master
Password for 'https://tobrien@oreilly.com@atlas-server.oreilly.com': 
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

So, I rolled-back a commit and decided to add my figures one by one, it worked:

```
tmac:web Tim$ git commit -m "Added a single figure to test my assumption that this Git repository   doesn't like big pushes"
[master 44451d2] Added a single figure to test my assumption that this Git repository doesn't like big  pushes
1 file changed, 0 insertions(+), 0 deletions(-)
create mode 100644 figs/web/pom_book-example.png
tmac:web Tim$ git push oreilly master
Password for 'https://tobrien@oreilly.com@atlas-server.oreilly.com': 
To https://tobrien%40oreilly.com@atlas-server.oreilly.com/git/1234000000354.git
   f964727..44451d2  master -> master
```

My guess is that the Apache 2.2.14 server that is running on atlas-server.oreilly.com has a small LimitRequestBody.  That's just my guess, any time I tried to push more than 2 MB of figures at once it would return a HTTP 502.

**Comment by adamwitwer** [comment]
Thanks for the detailed report, @tobrien.

While we ultimately need a better fix for this, the workaround for now is to increase the size of your http.postBuffer in your git client, as described in [this Stackoverflow post](http://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning):

```
git config --global http.postBuffer 524288000
```

We've got this as a TODO, so I'm going to close this comment, but please let us know if the above workaround doesn't work for you or if you have any other problems.

**Comment by tobrien** [comment]
That fixed it Adam, thanks for the quick reply.
