### ISSUE TITLE
Add support for formatting keyboard shortcuts?

### ISSUE THREAD

**Issue by kristenORM** [MakerPress/atlas-public-feedback#159]
Curious if it's feasible to build in keyboard shortcuts for formatting (bold, italic, and code, at the least), like cmd-I, cmd-B, and so on.

The toolbar at the top is convenient, but the tiny lag of generating the dropdown menu and reading my options slows me down when entering wholesale formatting changes throughout text.  And when I'm in the flow, typing special characters like + and _ around multiple terms is also a bit of drag. Whinewhinewhine. :) Just mentioning this as a possible enhancement!

**Comment by runemadsen** [comment]
This is a good idea, and shouldn't be too hard.

**Comment by kristenORM** [comment]
Awesome, thanks much!

**Comment by runemadsen** [comment]
This has been implemented in the new editor:

Cmd + i makes something emphasized
Cmd + b makes something bold
Cmd + s saves the document

Let me know if you have other ide for shortcuts you're using a lot.

**Comment by kristenORM** [comment]
What about to make something literal font? By that, I mean code sitting within plain text paragraphs. Thanks!

**Comment by runemadsen** [comment]
Yes, @sandersk suggested that also. Maybe Cmd + L?

**Comment by kristenORM** [comment]
I like Cmd-L!

**Comment by runemadsen** [comment]
Apparently Cmd + L is taken for "go to a line number", so I made it Cmd + k instead. Think "k" for "the thing that is close to L for literal" or something. If you have a better idea, let me know.

Oh, it's live, so you can use the shortcut right now.

**Comment by kristenORM** [comment]
I think the Cmd + K shortcut should be fine...in XMLMind, prodeds use an Esc-K shortcut to put words in a keep-together, so it should be pretty easy to remember! Thanks again, Rune.
