### ISSUE TITLE
Locked out of Security Bibliography

### ISSUE THREAD

**Issue by troymott** [MakerPress/atlas-public-feedback#161]
I had access to this project this morning, but now I am getting a 500 error when trying to access it. Can you look into this right away for me?

Thanks,

Troy

**Comment by sandersk** [comment]
Hi Troy,

We are looking into this right now. Rune, this problem seems to be specific to just the Security Bibliography, and not a more global Atlas issue.

Troy, did you or any other collaborators make any edits to the book this morning, or were you just viewing it?

Thanks,
Sanders

**Comment by runemadsen** [comment]
Thanks. Taking a look right now.

**Comment by runemadsen** [comment]
Ok, I know what the problem is now. I fixed this on my local machine and will deploy this tonight.

**Comment by runemadsen** [comment]
Okay, this has been fixed now. It was a single corrupt permission, and I'll deploy code later that makes sure this doesn't happen again.

**Comment by troymott** [comment]
Thank you so much!!!
