### ISSUE TITLE
500 Error When Accessing Changes View

### ISSUE THREAD

**Issue by mrichardson23** [MakerPress/atlas-public-feedback#162]
When I try to see the changes on GSWRPi, I'm getting a 500 error. My hunch is that a lot of the last changes involved binary files, and I've seen some weirdness with the changes tab and binaries in the past:
http://ano-atlas2.herokuapp.com/books/1230000000649/versions/master/changes

**Comment by runemadsen** [comment]
Hi Matt. I have the fixes for this on my local machine, and I'll deploy it tomorrow. I'll follow up with you then and see if you're still experiencing issues.

**Comment by sandersk** [comment]
Hi Matt,

It looks like the changes tab is now displaying properly for your book, so I'm going to go ahead and close this ticket. Could you please reopen this ticket and let us know if you encounter further errors?

Thanks very much,
Sanders
