### ISSUE TITLE
Commit message field next to Save button not working

### ISSUE THREAD

**Issue by jhosman** [MakerPress/atlas-public-feedback#163]
The Atlas docs say I should be able to enter a commit message in the field next to the Save button, in the Atlas text editor. But I'm unable to type anything in that field. Is this an upcoming feature, or is it broken?

Thanks!

**Comment by runemadsen** [comment]
Hi! What browser are you using? I'm not having problems with it.

**Comment by jhosman** [comment]
Okay, I just tried it in Safari, and it worked. It doesn't work in Firefox, though.

**Comment by runemadsen** [comment]
Thanks. I'll investigate.

**Comment by jhosman** [comment]
Thanks Rune!

**Comment by runemadsen** [comment]
We decided to get rid of the commit box in the new editor. It's easy to add in again if it's needed, but less than 1% of Atlas users where actually using it. Please open a new issue if this bugs you :-)
