### ISSUE TITLE
Trying to access Atlas: 404 error

### ISSUE THREAD

**Issue by myarbrough** [MakerPress/atlas-public-feedback#164]
Hello!

Trying to sign into Atlas and I'm getting an error message. Is it down?

**Comment by sandersk** [comment]
Hi Mel,

Yes, it's down. We're looking into the outage and will let you know as soon as it's back up.

Sorry for the inconvenience.
Sanders

**Comment by runemadsen** [comment]
This should be fixed now. We're working on making the system more stable.
