### ISSUE TITLE
cover to showing up in EPUB and MOBI builds

### ISSUE THREAD

**Issue by slynchoreilly** [MakerPress/atlas-public-feedback#165]
I built an EPUB and MOBI for this title:

Encyclopedia of Electronic Components Volume 1
http://atlas.labs.oreilly.com/books/1230000000669

The cover is showing up in the dashboard, but isn't making it in to the files when I build.

**Comment by sandersk** [comment]
Hi Sam,

I'll touch base with you on this tomorrow. This is normally an easy fix to the metadata in book-docinfo.xml, but we're currently experiencing some issues with the Atlas git infrastructure that affect checkouts and builds of large books like this one, so we may need to employ a workaround here.

Sorry for the inconvenience,
Sanders

**Comment by sandersk** [comment]
Closing, as I resolved this working with Sam last week.
