### ISSUE TITLE
Use Bootstrap or something trendy like that...

### ISSUE THREAD

**Issue by tobrien** [MakerPress/atlas-public-feedback#166]
I'm specifically talking about these nav bar buttons.  Ok, I know, this is annoying feedback, but why not use Bootstrap or Foundation in Atlas?    I know, who cares?  Right?  

"O'Brien, what a shallow thing to bring up.  Go back to writing your damn book."

Ok, ok, sorry.  But, it would look sexier. no?

**Comment by whyisjake** [comment]
+1 :)

**Comment by tobrien** [comment]
Also, please feel free to forget about me.   I'm a hyperactive idiot obsessed with things like Bootstrap.

**Comment by runemadsen** [comment]
Thanks for the feedback @tobrien and @whyisjake. This first half a year in Atlas has mostly been about developing a system that works with a range of features, and you're right that the UI needs some attention. There has simply just not been time for it, but spending time on usability and site design is something that is very much on our radar (I'm a designer by profession so it nags me, but it's all a matter of priority).

That being said, I'm personally not a big fan of Bootstrap when it comes to bigger web applications. I think Bootstrap is great when you want good design that gets out of your way for internal tools or hobby projects, but for actual application identity it quickly gets humdrum. I would get terribly mad if Github or GMail switched to Bootstrap, and in our case I don't think it's so much about choosing an already existing framework, as it is designing something that works for what we do.

Please keep the feedback coming. It's always good to hear.

**Comment by tobrien** [comment]
Ok, please get back to Atlas.  It is sublime and awesome, and sorry for the distraction.     

Also, from what I can see of your work there's no doubt it will one day look sexier than I can even conceive at the moment.

**Comment by runemadsen** [comment]
No, it's not a distraction at all. These are the things that are important to hear. Developing applications like this, it's dangerous to work on optimizing all the things the users don't see, and forget about the things that matters to users. So I would love to know what distracts you in the interface (as I said, I have a ton of things that I think needs to change).

**Comment by whyisjake** [comment]
FWIW, I read updating the design of Atlas, but in my head I was thinking Chimera. Would be nice to show off of the Bootstrap book with a Bootstrap website. VERY HAPPY, AND NOT WORRED ABOUT IT THO.

**Comment by runemadsen** [comment]
We're definitely working on custom templates for Chimera books. That's
going to be the killer feature. It will take some time to get there, but
it's on the roadmap.
