### ISSUE TITLE
Atlas UI (ACE editor) using Windows-style linefeeds

### ISSUE THREAD

**Issue by adamwitwer** [MakerPress/atlas-public-feedback#167]
An editor wrote in to point out a problem with diffing because of the linefeeds that Atlas uses:

> I think what the authors were telling me was that they were getting reformatting of the asciidoc when they edit the files via the Atlas interface versus textmate and command line commits. So there is one commit on a file and it was checked out and edited with textmate and committed via the command line. There is a second round of edits done in the Atlas interface and the changes are committed via Atlas. The dif of these two versions show significant reformatting.

I'm not sure if we should change anything but I'm creating a ticket to raise visibility. I'll plan to add a warning to the docs.

**Comment by runemadsen** [comment]
Thanks Adam

Are you sure they are using Textmate? I would think this would happen on Windows computers, but not on Macs. Can you ask what OS they edited on?

**Comment by zaremba** [comment]
resolving due to age; please reopen if this is still relevant
