### ISSUE TITLE
validity error: emphasis and literal

### ISSUE THREAD

**Issue by DanGitOreilly** [MakerPress/atlas-public-feedback#169]
I spoke briefly with Sanders about this issue. Several books are coming in to production with this validity error:

element literal: validity error : Element emphasis is not declared in literal list of possible children

It would be very useful to have a fix that could be applied for this rather than manually fixing at intake.

Thanks,

Dan

**Comment by sandersk** [comment]
Hi Dan,

I'll look into this and see if that's something that we can correct for in either the AsciiDoc->DB conversion, or as a DB pre-processing step in csspdf.

Thanks for reporting this. Definitely a good idea to automate a fix for this, if it keeps coming up.

Sanders

**Comment by sandersk** [comment]
Hi Dan,

Just an FYI that I now have some handling in place to convert simple nestings of emphasis in literals to valid DocBook. The following will now convert properly:

```
+_Monospace and italic_+
```

I'm still looking into handling for more complex cases like this:

```
+Everything in monospace, but only the word _italic_ in italic+
```

Will keep you posted.

Thanks,
Sanders

**Comment by DanGitOreilly** [comment]
Thanks Sanders!

**Comment by jhosman** [comment]
Hi Sanders,

Just wanted to add a related comment. It looks like your complex example above is working now:

```
+Everything in monospace, but only the word _italic_ in italic+
```

but it breaks if there are two separately marked italic words inside the same literal, like this:

```
+Everything in monospace, but only the words _italic_ and _another_ in italic+
```

In that case, it outputs both of the italic words in emphasis elements instead of replaceable elements.

**Comment by sandersk** [comment]
Thanks, Jess. Yes, I've got handling in the AsciiDoc for cases where there is just one italic nested in a monospace block, but not multiples yet, but that's on the to-do list.
