### ISSUE TITLE
Build issue in .Net Bibliography

### ISSUE THREAD

**Issue by troymott** [MakerPress/atlas-public-feedback#171]
A build of this book eventually completed after 5 minutes, but it is only building to PDF the first 3 chapters, and there are 19 chapters total. I have looked at chapter 3 and at chapter 4 and I don't see anything unusual. We are using # quite a bit in this bibliography for languages such as C# and F#. Not sure that it is the issue though. Please help.

--Troy Mott

**Comment by sandersk** [comment]
Hi Troy,

I see 19 chapters in the PDF I downloaded from the Atlas dashboard of your book (see screenshot below). Is it possible your PDF download was corrupt? Could you try downloading again and see if you still are getting an incomplete PDF?

Thanks,
Sanders

![dotnet_biblio](https://f.cloud.github.com/assets/703865/18253/2f87fdba-48a5-11e2-8a8f-29d710068a32.png)

**Comment by troymott** [comment]
Thanks Sanders. Okay, so Christina was able to build and open a PDF version with all 19 chapters showing, but when I open the PDF link I just get the first 3 chapters only still. There were some building errors for me earlier, but not sure why I am not seeing the entire PDF?

--Troy

**Comment by sandersk** [comment]
Hi Troy,

Oh, I suspect your browser may have cached a previous version of the PDF that contained only the first few chapters. After you load the link in your browser, can you hit the Refresh button, and then try downloading? I suspect that you'll get the full PDF this time. Let me know if not, though.

Thanks,
Sanders

**Comment by troymott** [comment]
Thanks Sanders. It won't view in my browser, but I was able to download it and see everything that way. Thanks for all the help. We can close this one now. ;-)

--Troy
