### ISSUE TITLE
can't save changes to chapter title / file name field

### ISSUE THREAD

**Issue by jcarrott** [MakerPress/atlas-public-feedback#173]
I need to change the numbering and titles of some of my book's chapters, but when I make a change in the chapter title field and click "save" the change doesn't stick.  it freezes on "saving" and when I refresh, it defaults back to the old unchanged title.  please advise.  thanks!

**Comment by runemadsen** [comment]
Hi @jcarrott. What's the book and file you're talking about? Let me know and I'll check it.

**Comment by bjepson** [comment]
Hi Rune,

It's http://ano-atlas2.herokuapp.com/books/1234000000530, and I believe he's having this problem with any file he tries. I tried it with cuts-from-act-3.asciidoc and had the same problem.

**Comment by jcarrott** [comment]
Thanks for looking into this, guys--it will be a huge help to have it resolved.

On 21 Dec 2012, at 5:16 AM, Brian Jepson notifications@github.com wrote:

Hi Rune,

It's http://ano-atlas2.herokuapp.com/books/1234000000530, and I believe he's having this problem with any file he tries. I tried it with cuts-from-act-3.asciidoc and had the same problem.

Brian

**Comment by bjepson** [comment]
You're welcome, James. Do you want me to try using the git backend to rename one of the files? For example, let me know what you want me to call Chapter 3 and I'll see what happens.

**Comment by jcarrott** [comment]
er…  yeah.  Chapter 8 should be renamed chapter 7 and chapter 7 should be noted as "REMOVED"

On 21 Dec 2012, at 5:24 AM, Brian Jepson notifications@github.com wrote:

You're welcome, James. Do you want me to try using the git backend to rename one of the files? For example, let me know what you want me to call Chapter 3 and I'll see what happens.

**Comment by bjepson** [comment]
Got it. So cuts-from-ch8.asciidoc becomes chapter07.asciidoc, right? Do you want me to delete Chapter07-Its-Not-All-Top-Hats-and-Goggles.asciidoc or just rename it to REMOVED.asciidoc?

**Comment by jcarrott** [comment]
just rename for now.  I haven't fully built out the supplement content yet.

though it would be nice to know how to delete a chapter for when the time comes. :)

On 21 Dec 2012, at 5:29 AM, Brian Jepson notifications@github.com wrote:

Got it. So cuts-from-ch8.asciidoc becomes chapter07.asciidoc, right? Do you want me to delete Chapter07-Its-Not-All-Top-Hats-and-Goggles.asciidoc or just rename it to REMOVED.asciidoc?

**Comment by bjepson** [comment]
Sure thing; I just pushed those renames. I'm not sure if you can delete a chapter from within Atlas, but if you (or I) check it out using a git client, you (or I) can delete a chapter.

**Comment by runemadsen** [comment]
Thanks @bjepson. I'll check the rename functionality. It should work, but i'll double check. You're correct that deleting files is not an option in Atlas right now.

**Comment by bradlygreen** [comment]
I'm seeing this as well.  In the console, I see these errors:

POST http://ano-atlas2.herokuapp.com/books/1234000000034/versions/master/editor/Introduction.asciidoc 500 (Internal Server Error) application-f81bf0b76071eb24a8870eba5f234950.js:16
send application-f81bf0b76071eb24a8870eba5f234950.js:16
v.extend.ajax application-f81bf0b76071eb24a8870eba5f234950.js:16
e.rails.r.ajax application-f81bf0b76071eb24a8870eba5f234950.js:16
e.rails.r.handleRemote application-f81bf0b76071eb24a8870eba5f234950.js:17
(anonymous function) application-f81bf0b76071eb24a8870eba5f234950.js:17
v.event.dispatch application-f81bf0b76071eb24a8870eba5f234950.js:15
o.handle.u application-f81bf0b76071eb24a8870eba5f234950.js:15

Uncaught TypeError: Object [object Object] has no method 'setFailure' editor-6734db1c253f13cb3e005121e825ebe7.js:9
(anonymous function) editor-6734db1c253f13cb3e005121e825ebe7.js:9
v.event.dispatch application-f81bf0b76071eb24a8870eba5f234950.js:15
o.handle.u application-f81bf0b76071eb24a8870eba5f234950.js:15
v.event.trigger application-f81bf0b76071eb24a8870eba5f234950.js:15
(anonymous function) application-f81bf0b76071eb24a8870eba5f234950.js:15
v.extend.each application-f81bf0b76071eb24a8870eba5f234950.js:14
v.fn.v.each application-f81bf0b76071eb24a8870eba5f234950.js:14
v.fn.extend.trigger application-f81bf0b76071eb24a8870eba5f234950.js:15
c.complete application-f81bf0b76071eb24a8870eba5f234950.js:17
l application-f81bf0b76071eb24a8870eba5f234950.js:14
c.fireWith application-f81bf0b76071eb24a8870eba5f234950.js:14
T application-f81bf0b76071eb24a8870eba5f234950.js:16
r application-f81bf0b76071eb24a8870eba5f234950.js:16

**Comment by runemadsen** [comment]
Thanks Brad. I'm looking into this right now.

**Comment by runemadsen** [comment]
Hi Brad. I can confirm that this is not working. We're actually working on an entire new editor, and we're going to launch it at the end of next week. It has a brand new renaming functionality that will take care of this. 

Do you have access to your files via the git command line, and can you rename them like that and push your changes up again?

Otherwise I can help you, if you tell me what I need to rename.
- Rune

**Comment by bradlygreen** [comment]
Hey, thanks for the offer.  But yes, I have git access and can do what I
need to until the new UI shows up.

Thanks!

**Comment by runemadsen** [comment]
The new version of the editor has ben launched today, along with the rename functionality. Closing this issue, so please create a new issue if you see any problems with the new feature.

**Comment by jcarrott** [comment]
brilliant!  thank you.  I'm continually impressed with your responsiveness in improving your tools.  

On 14 Jan 2013, at 1:41 PM, Rune Skjoldborg Madsen notifications@github.com wrote:

The new version of the editor has ben launched today, along with the rename functionality. Closing this issue, so please create a new issue if you see any problems with the new feature.

**Comment by runemadsen** [comment]
Thanks! That's great to hear.
