### ISSUE TITLE
Git integration seems to be having problems

### ISSUE THREAD

**Issue by ceteri** [MakerPress/atlas-public-feedback#174]
Currently, when I commit changes via Git, then I see those changes in Atlas by looking through each chapter individually -- in the "Write" mode. When I try to "Build", the updates are not there (builds based on commits from late Dec 22). When I try to see "Changes", Atlas returns a 500 error in the browser.

Perhaps the Mayans were correct about no more history after Dec 21 :)

**Comment by sandersk** [comment]
Hi @ceteri,

You're working on this book, correct?: http://atlas.labs.oreilly.com/books/1230000000065/

I took a look at the latest PDF available for download on the Dashboard, and it does seem to reflect the most recent changes you made on 12/23. Could you double-check that the old PDF isn't just cached in your Web browser? If you try hitting Refresh in your Web browser, do you get the up-to-date PDF?

With respect to the Changes tab, that's most likely a bug we'll need to investigate further. O'Reilly's offices are now officially closed for the holidays (we reopen on January 2), but we will review and address the problem when we return. In the meantime, you can get a diff of changes via the command line as follows:

```
$ git log -p
```

Hope this helps. Apologies for any inconvenience you've experienced.

Best,
Sanders

**Comment by ceteri** [comment]
Thank you Sanders -
Yes, that's correct I'm working on that book. The problem with "Build" cleared up (latest PDF is correct) -- was intermittent. I'd checked browser cache before, but that wasn't the issues.

"Changes" tab still produces a 500 error. Not a problem, since I use Git a lot already and can view changes there. However, I thought it might relevant for the other issue.

Anywho, I'm fine for what I need over the holidays, but I wanted to track this if there are other related issues and it might help.

**Comment by ceteri** [comment]
I haven't seen that 500 HTTP error in a while. Seems to be working well.
