### ISSUE TITLE
And the pending icon just spins and spins...

### ISSUE THREAD

**Issue by whyisjake** [MakerPress/atlas-public-feedback#176]
Trying to do a build [here](http://ano-atlas2.herokuapp.com/books/1230000000673/builds)...

**Comment by runemadsen** [comment]
Thanks Jake. Looking into this right now.

**Comment by runemadsen** [comment]
This has been resolved now. Please let me know if you see it happen again.

**Comment by whyisjake** [comment]
Thanks Rune.

**Comment by lookfwd** [comment]
I think this still happens today.
