### ISSUE TITLE
Metadata tab: authorblurb validity errors

### ISSUE THREAD

**Issue by nelliemckesson** [MakerPress/atlas-public-feedback#177]
It looks like currently if you add an author field to the metadata tab, the author blurb field is also automatically added as part of the author group. However, if they choose not to fill in the author blurb, then csspdf throws a validity error at the empty authorblurb in book-docinfo. We either need to split the author and authorblurb fields apart, or automatically include a para or something inside every authorblurb so as to make it valid.

**Comment by runemadsen** [comment]
Thanks for noticing Nellie. Whatever you think is better, I can do. @sandersk @adamwitwer any ideas?

**Comment by adamwitwer** [comment]
Good catch, Nellie.

Rune, I think the easiest thing would be to just add an empty `<para>` in the `<authorblurb>`:

``` xml
<author>
  <firstname>Lisa</firstname>
  <surname>Simpson</surname>
  <authorblurb>
    <para></para>
  </authorblurb>
</author>
```

**Comment by runemadsen** [comment]
Great. I'll do that.
