### ISSUE TITLE
Builds failing with 'openFile: does not exist' error

### ISSUE THREAD

**Issue by mrflip** [MakerPress/atlas-public-feedback#178]
Book 1230000000073 -- http://ano-atlas2.herokuapp.com/books/19/jobs/16978

```
Job failed
Full error:

pandoc: e44d6d.asciidoc: openFile: does not exist (No such file or directory)
```

grep'd e44d6d and it's nothing I'm referring to.

**Comment by sandersk** [comment]
Hi @mrflip,

Thanks for reporting this. You've pinpointed a bug in our build system affecting filenames with space characters, which we'll work on fixing.

In the meantime, as a workaround, I renamed your file "Document e44d6d.md" as "Document_e44d6d.md" (hope that's OK with you), and the build is now succeeding.

Let me know if you have any questions or encounter further issues.

Thanks,
Sanders
