### ISSUE TITLE
NaN everywhere

### ISSUE THREAD

**Issue by 0xf2** [MakerPress/atlas-public-feedback#179]
I see a whole lot of NaN on my git commit headers:

http://ano-atlas2.herokuapp.com/books/1230000000993/versions/master/changes

I am not usre what the origin is.  It gets more interesting, tho - if I look at stats

http://ano-atlas2.herokuapp.com/books/1230000000993/stats

It thinks my commits are all back in October, while they are really mostly in January. 

I am using both the web interface (occasionally) and Git push (all the time).

Any hint?

Thanks -F

**Comment by runemadsen** [comment]
Hi Frederico

This is a browser-problem related to Firefox. We have it on the todo list, but if you see the page in Chrome, it should work.

**Comment by runemadsen** [comment]
Better late than never. This has been fixed now!
