### ISSUE TITLE
How can I delete files?

### ISSUE THREAD

**Issue by truthtrap** [MakerPress/atlas-public-feedback#18]
I am trying to delete a file, but I can't find how I can do that.

**Comment by odewahn** [comment]
Hi, Jurg.  There's not a way to do it directly in the atlas interface (yet), but that's on the roadmap.  The best way to delete a file is to pull it locally, delete it using git, and then push the repo back up.  

What's the file?  I'd be happy to do it for you.

Andrew

----- Original Message -----
From: Jurg van Vliet reply@reply.github.com
To: Andrew Odewahn odewahn@oreilly.com
Sent: Mon, 04 Jun 2012 07:01:18 -0400 (EDT)
Subject: [atlas-public-feedback] How can I delete files? (#18)

I am trying to delete a file, but I can't find how I can do that.

---

Reply to this email directly or view it on GitHub:
https://github.com/MakerPress/atlas-public-feedback/issues/18

## 

Andrew Odewahn
Chief Technology Officer
O'Reilly Media
617-460-6693

**Comment by truthtrap** [comment]
hi andrew,

thanks for your reply. how can get to my repository? can you add me
(truthtrap) and flavia (locomundo) as collaborators directly?

this is 100% github based? really cool!

groet,
jurg.

On Mon, Jun 4, 2012 at 3:25 PM, Andrew Odewahn <
reply@reply.github.com

**Comment by odewahn** [comment]
Hi, Jurg.  If you go to the "Metadata" tab, you'll find your git repo URL as the first element on the page.  You can then use that to clone the repo locally to your machine.  It will ask you for a password -- just use the same password that you use in Atlas.  (Currently, we're only supporting HTTPS access, so it will ask you for a password each time.) 

It's just plain git, though, not directly on GitHub.  But, if you want to put it on github, all you have to do is add a new remote and push it over.  Chapters 6 and 7 in the Atlas getting started guide --  -- it will you can get it a http://cdn.oreilly.com/atlas_docs.zip -- explain how to use all the git features and github together.

Andrew

ps -- also, you can add anyone as a collaborator in Atlas yourself -- just go to the collaborator tab and put in their email address

pps -- we're working on a much more smooth integration with GitHub, but the next big thing on the roadmap is a better text editor.  Please keep the feedback coming, though, so we'll know where to focus.

----- Original Message -----

**Comment by truthtrap** [comment]
Andrew,

Thanks! This works flawlessly.

I don't need github, I was just curious, just git is fine. We'll focus on
working in the editor, I am a sucker for wysiwygs :P

Groet,
Jurg.

On Mon, Jun 4, 2012 at 3:50 PM, Andrew Odewahn <
reply@reply.github.com

**Comment by odewahn** [comment]
Awesome -- glad it worked for you.  One quick nit that we're trying to fix -- when you build a file in atlas, it changes a file called "book.asciidoc," so your local repo and the Atlas repo get out of sync each time you build.  So, if you try to push from your local repo back to atlas, sometimes you'll get a conflict.  All you need to do is pull from Atlas again, or do a fetch/merge (which is actually a better way to do this, anyway.)

To work around the problem, you can just add "book.asciidoc" to your .gitignore.  But, please don't force push!  (Plus, if changes have been made by a collaborator or a production editor, you'll blow those away!).

Keep the comments coming and thanks for participating in the beta as we iron out these details.

Andrew

ps -- I really enjoyed your AWS book, BTW!  Great work.

----- Original Message -----
