### ISSUE TITLE
New Atlas interface: Double-click highlighting

### ISSUE THREAD

**Issue by myarbrough** [MakerPress/atlas-public-feedback#181]
Hello!

When I try to double click a word to highlight and edit it, the highlight doesn't pertain to any particular word. In the attached image, I tried to highlight the word "specially". 

This might pose the most problems for indexers. Otherwise, I love the new larger window!
![Screen shot 2013-01-14 at 10 18 50 AM](https://f.cloud.github.com/assets/1180731/64829/d5986bd6-5e5d-11e2-880a-dfc1bc9910fa.png)

Thanks!
Mel

**Comment by runemadsen** [comment]
Hi @myarbrough. It looks like the real font is not getting loaded, and that's why you're seeing this problem. What browser and operating system are you on?

If you go to "settings" and choose "Monaco" as your font, this will probably go away.

**Comment by adamwitwer** [comment]
Hey Rune. Souvenir and Helvetica both seem to be loading for me. I'm using Chrome.

Adam

**Comment by myarbrough** [comment]
Hi Rune, I'm using Chrome. I was able to switch it to Monaco under Settings (Helvetica & Souvenir are also options). I'll let the indexer know about this in the meantime. 

Thank you!
Mel

**Comment by runemadsen** [comment]
Ok, great. It's weird that the font is not loading for you, as it seems to be working elsewhere. Have you tried to refresh the page?

**Comment by runemadsen** [comment]
Okay, I've made some changes, so the font will always default back to Monaco, if the other fonts are not found. This should mean that you don't need to choose "monaco" in the settings, as it will fall back to it if the loading of the other fonts fail.

I'm looking into why the font loading would fail for you.

**Comment by myarbrough** [comment]
Thank you! I just closed and reopened Atlas and Monaco is loading now.

**Comment by runemadsen** [comment]
Ok, great. One last thing: What happens when you choose "Helvetica". Does the font change, and does the highlighting work?

**Comment by myarbrough** [comment]
Nothing happens when I choose Helvetica or Souvenir. The text remains Monaco and highlighting works.

**Comment by runemadsen** [comment]
Ok, thanks. The fonts are still not loading for you then. Looking into it!
