### ISSUE TITLE
Atlas--cursor and what really happens

### ISSUE THREAD

**Issue by JillEd** [MakerPress/atlas-public-feedback#183]
This may be related to the specific document, but...

With the cursor placed at the end of a line, adding or deleting text actually takes place 6 or 8 or 10 spaces to the left of the actual cursor placement. Causing havoc! Document worked fine before the interface was changed.

Jill Ed

**Comment by runemadsen** [comment]
Hi Jill

Can you post a screenshot of your screen? I think this is related to the font not loading.
- Rune

**Comment by runemadsen** [comment]
Also, the tabs has been changed around now, so the files are at the bottom.

**Comment by JillEd** [comment]
Here they are. I tried Firefox, Pale Moon, Chrome, SeaMonkey browsers--all with the same result and the highlighting issue mentioned elsewhere.
![Altas cirsor issue2](https://f.cloud.github.com/assets/3267499/65321/e0deac7c-5e75-11e2-8526-4600948d4df1.jpg)
![Atlas cursor issue](https://f.cloud.github.com/assets/3267499/65322/e1343610-5e75-11e2-9139-72b2f63c6f87.jpg)

**Comment by JillEd** [comment]
The images loaded in the wrong order--look at the bottom one first--it shows where the cursor was placed. The top one shows where the ((( three parentheses were added. Trying to delete or backspace does the same thing and the cursor also does move one letter space at a time--just a random distance not related to the letters.

**Comment by JillEd** [comment]
I also tried all different font sizes.

I do like all the different "looks"; they're cool.

**Comment by runemadsen** [comment]
Yeah, this is related to issue https://github.com/MakerPress/atlas-public-feedback/issues/181. Somehow the fonts are not loading.

Can you do me a favor and do a hard refresh? (Cmd - shift - R). Does that help now?

Are you on Windows?
- Rune

**Comment by JillEd** [comment]
On Windows--Monoco {sp?} is not a standard Windows font as far as I know, and does not exist on my system.

**Comment by JillEd** [comment]
Actually I tried all the fonts--sometimes saw them change, sometimes not. For that matter Helvitica is not on my the system either. What's the other one?

**Comment by JillEd** [comment]
Checked the other one, too, also not on my system.

**Comment by JillEd** [comment]
Why not use some of the both system compatible fonts:

http://www.ampsoft.net/webdesign-l/WindowsMacFonts.html

**Comment by JillEd** [comment]
From above--I can;t type with a cat on my lap--"and the cursor also does NOT move one letter space at a time--just a random distance not related to the letters."  I left a word out before.

**Comment by runemadsen** [comment]
The thing that is messing it up is that the editor is defaulting to a non-monospaced font because it can't find the other fonts, and this is blowing up the editor with all these errors. The thing is that I'm loading the fonts as webfonts, so it should work.

I just pushed something I believe will fix your problem. Try a hard refresh again and let me know if you still have the selection problem.

**Comment by JillEd** [comment]
That seems to have helped--can highlight correctly and also add and delete text. Why not just let the individual's system choose a font? Or at least include some Windows fonts--Georgia, Courier New and Tahoma or Trebuchet.

**Comment by JillEd** [comment]
Text is much easier to read in the narrower window (than the way Atlas was a week or so ago), esp. now that it goes the width of the window (before your fix it was only going about halfway across which was too narrow). Looking very good! Thanks!

Tool tips for the icons on top? That would be great, too.

**Comment by runemadsen** [comment]
Great. If you want the window narrower, you can just resize the browser window. That's the beauty of it. It's not bound to a specific size anymore.

The problem with all those fonts is that they are not mono-spaced. I'm essentially doing what you're proposing, letting the system choose its own font at the end, but I'm still not sure why some of the better looking web fonts are not loading. I guess this means I have to VM install Windows. Dammit.

**Comment by JillEd** [comment]
Windows. Unfortunately some of us are stuck with it. We're mostly jealous though of you Mac folks. :-)

Thanks for your efforts. Looks good in my browser now. Courier New is monospaced, isn't it?

**Comment by runemadsen** [comment]
Yup, that's the fallback font right now.
