### ISSUE TITLE
Can't add two users to Atlas

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#184]
Hi,

I'm trying to add a couple of users to Atlas (the book is http://ano-atlas2.herokuapp.com/books/1234000000778), but they had a problem getting in.

When they tried to use the invite, they got a 500 error.
After that, their token became invalid.
I attempted to delete them as collaborators and reinvite them, but they never got the second invitation.

Thanks,

Brian

**Comment by runemadsen** [comment]
Thanks Brian, looking at it right now.

**Comment by runemadsen** [comment]
This should be fixed now. I checked, and they are both users with passwords in the system. If they just go to Atlas and input their passwords they put in before the app broke, it should all work.

Let me know if not.

**Comment by bjepson** [comment]
Thanks; I'll let them know!
