### ISSUE TITLE
File contents not displaying in Atlas editor

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#185]
The following issue was submitted by Andy Oram to the Tools RT queue:

```
For some reason, the following file shows up empty in 
the Atlas interface: 

http://ano-atlas2.herokuapp.com/books/1230000000549/versions/master/editor/bibliography.asciidoc 

I checked out the repository manually and the file there 
has 75 lines.
```

**Comment by runemadsen** [comment]
Thanks, I can confirm this is happening. On my list of things to do today.

**Comment by runemadsen** [comment]
This has been fixed now. It was caused by the git server somehow being absolutely certain that this was a binary file. Not sure why, but I added a workaround.

**Comment by jhosman** [comment]
Thanks! I'll let Andy know it's fixed.
