### ISSUE TITLE
Warning blocks not styled in Chimera

### ISSUE THREAD

**Issue by clintongormley** [MakerPress/atlas-public-feedback#186]
Hiya

Have a look at the text under http://ano-chimera.herokuapp.com/books/1230000000825/ch05.xhtml#prefix_filter

There is a warning block, which is marked as `class="warning"` but no style is applied

ta

**Comment by nelliemckesson** [comment]
Thanks @clintongormley ! I've added a style for warnings. The Chimera stylesheet is likely to get an overhaul in the very near future, but this should work for the time being :)

**Comment by clintongormley** [comment]
On Wed, 2013-01-16 at 06:34 -0800, Nellie McKesson wrote:

> Thanks @clintongormley ! I've added a style for warnings. The Chimera
> stylesheet is likely to get an overhaul in the very near future, but
> this should work for the time being :)

many thanks Nellie.  I actually thing Chimera is looking pretty good!
