### ISSUE TITLE
book-docinfo.xml in build list

### ISSUE THREAD

**Issue by DanGitOreilly** [MakerPress/atlas-public-feedback#188]
How about excluding the book-docinfo.xml file from the list of files that can be included in a build? 

My thinking is that if you can't think of an instance where it should be included in a build, having it there could be confusing, and if included would result in unwanted text in the build. 

I would still want to see it in the list of files that can be edited.

**Comment by zaremba** [comment]
Dan, going to resolve this for now. If this or something similar is still an issue with v2 please let me know.
