### ISSUE TITLE
Tooltips when hovering over toolbar options

### ISSUE THREAD

**Issue by DanGitOreilly** [MakerPress/atlas-public-feedback#190]
I like the new design. When using Atlas in Chrome, I don't see any tooltips when I hover over the new icons for the drop-down menus (Headings, Lists, Media, etc.). It would be nice to have those.

**Comment by sandersk** [comment]
Tooltips are on the way, Dan. Look for them very soon.

**Comment by runemadsen** [comment]
These has been implemented now!
