### ISSUE TITLE
Indicating the active chapter in writing window

### ISSUE THREAD

**Issue by DanGitOreilly** [MakerPress/atlas-public-feedback#192]
It's great having the list of chapters available next to the writing window. But other than seeing the name of the active chapter at the end of the url, it's hard to tell which chapter you're editing. It would be nice to have some indication, maybe highlighting the active chapter in some way in the list that appears to the left. 

That would make it a little easier to move from chapter to chapter and stay in order.

**Comment by runemadsen** [comment]
Hi @DanGitOreilly. We're actually highlighting the current file you're editing with a white background. It might be too subtle though, so I can change it to something more visible?

**Comment by DanGitOreilly** [comment]
Hi Rune,

Yeah, I think that would do it. Or I could try one of the cool new themes you added.

Dan

**Comment by runemadsen** [comment]
Ok, I've added a small icon in front of the file that is currently being edited. I'll deploy it some time tomorrow, so keep an eye out!

**Comment by runemadsen** [comment]
This has also been fixed.
