### ISSUE TITLE
Deleting comments in chimera

### ISSUE THREAD

**Issue by clintongormley** [MakerPress/atlas-public-feedback#193]
Hiya

Is there any way to delete comments in Chimera?  Once an issue has been corrected, I'd want to remove the comments so that they don't add clutter

ta

Clint

**Comment by runemadsen** [comment]
Yes, this is definitely something that's on the list. Hopefully coming very soon.

**Comment by runemadsen** [comment]
It's possible for book owners to delete files in Chimera now. Coming to Atlas soon.
