### ISSUE TITLE
Stuck build (PDF, ePub, Mobi)

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#195]
Hi, I've got a book (http://ano-atlas2.herokuapp.com/books/1234000000422) that usually takes a few seconds to build a PDF, but the ePub+PDF+Mobi build has been running for 38 minutes now. Could it be stuck?

Thanks,

Brian

![Screen Shot 2013-01-28 at 7 29 26 PM](https://f.cloud.github.com/assets/278746/105366/f763b948-69aa-11e2-8053-80207895ce55.png)

**Comment by runemadsen** [comment]
Hi Brian. Sorry about that. You must have built the book exactly as I was pushing changes to production. I tried building the book again, and it worked. 

Please let me know if you keep seeing this.
- Rune

**Comment by bjepson** [comment]
Thanks, Rune. That did the trick (sorry for the delayed response).
