### ISSUE TITLE
Upload XML files and convert to asciidoc

### ISSUE THREAD

**Issue by jhosman** [MakerPress/atlas-public-feedback#196]
Just wondering if there's any plan eventually to be able to upload XML files in the web interface and then click a button to convert them to asciidoc using the d2a.xsl script. That would be pretty cool!

Jess

**Comment by sandersk** [comment]
That's a good idea, Jess. I agree we should put that on the to-do list, although I think it'll probably sit below some higher-priority Atlas improvements.

Sanders

**Comment by jhosman** [comment]
That's understandable. It would be a great new feature when there's time, though. Thanks!

**Comment by ianmolynz** [comment]
Has anything been done to address this? The ability to convert from other formats to asciidoc would seem a must-have?

**Comment by sandersk** [comment]
Support in Atlas for automatically converting your source files for XML to AsciiDoc isn't available at this time, but we are actively investigating adding an Import feature to our next release of Atlas that will convert files from other formats.
