### ISSUE TITLE
"quick build"

### ISSUE THREAD

**Issue by shiffman** [MakerPress/atlas-public-feedback#197]
I'm testing out a bunch of stuff and regenerating the HTML build every few minutes, a "quick build previous build" button somewhere would be great!

**Comment by odewahn** [comment]
Thanks for the suggestion, Dan!  For a super quick preview, you can also try the "HTML Preview" button under the quicklinks.  It will just render the asciidoc instantly so you can see if the formatting is right.

----- Original Message -----
