### ISSUE TITLE
Time Stamp of commit

### ISSUE THREAD

**Issue by mikehatora** [MakerPress/atlas-public-feedback#2]
On the changes tab in Atlas, it would be great to have a time stamp of when you made the change.  That way you know that there was no issue of wrong repository, internet connection or remoting issue.

**Comment by bjepson** [comment]
This would also be helpful when reviewing changes, so you can focus on only the most recent changes.

**Comment by runemadsen** [comment]
This has been implemented now. The timestamp will be converted into the current client timezone, which means that all times are relative to your time (e.g. someone in China committing something at 1pm their time will show up as 1am for a person in the US). Hope that helps.
