### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by r0ml** [MakerPress/atlas-public-feedback#20]
I attempted a build to see if I had correctly figured out how to include images.

The response was:

500
We're sorry, but something went wrong.
If you think this is a bug, please report it

I think this is a bug.  But unfortunately, there's not enough feedback from the system for me to suggest where to start looking for the problem.

**Comment by MakerPress** [comment]
Hi, R0ml.  Can you tell me which file you w file you were editing, and which files you were trying to build?

Andrew

----- Original Message -----
From: r0ml reply@reply.github.com
To: MakerPress makerpressadmin@oreilly.com
Sent: Sun, 10 Jun 2012 21:20:32 -0400 (EDT)
Subject: [atlas-public-feedback] Build failure (#20)

I attempted a build to see if I had correctly figured out how to include images.

The response was:

500
We're sorry, but something went wrong.
If you think this is a bug, please report it

I think this is a bug.  But unfortunately, there's not enough feedback from the system for me to suggest where to start looking for the problem.

---

Reply to this email directly or view it on GitHub:
https://github.com/MakerPress/atlas-public-feedback/issues/20

## 

Andrew Odewahn
Chief Technology Officer
O'Reilly Media
617-460-6693

**Comment by r0ml** [comment]
I was editing  whyDoWeRead.asciidoc

Em Jun 10, 2012, às 9:32 PM, MakerPress reply@reply.github.com escreveu:
