### ISSUE TITLE
Getting the following when trying to commit.

### ISSUE THREAD

**Issue by whyisjake** [MakerPress/atlas-public-feedback#200]
``` bash
macjspurlock:1230000000673 jspurlock$ git push origin master
Password for 'https://jspurlock@oreilly.com@atlas-server.oreilly.com': 
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

**Comment by whyisjake** [comment]
And if I try to use the Github app, I get this screen.

![Github App](http://f.cl.ly/items/1C2v3S053Q2c2W3e3I0L/Screen%20Shot%202013-01-31%20at%2012.18.47%20AM.png)

**Comment by odewahn** [comment]
Hi, Jake.  Try running this command on your git client:

git config http.postBuffer 524288000

Git restricts the size of the HTTP buffer to 2MB by default.  If you have a repo with lots of images, though, you might need a bigger buffer, as described here:"

http://stackoverflow.com/questions/2702731/git-fails-when-pushing-commit-to-github

----- Original Message -----

**Comment by whyisjake** [comment]
That fixed it, thanks.
