### ISSUE TITLE
Issue with a blockquote.

### ISSUE THREAD

**Issue by whyisjake** [MakerPress/atlas-public-feedback#201]
Trying to add a blockquote, manuscript looks like this:

``` asciidoc
[quote, Mark Otto, https://dev.twitter.com/blog/bootstrap-twitter]
----
In the earlier days of Twitter, engineers used almost any library they were familiar with to meet front-end requirements. Inconsistencies among the individual applications made it difficult to scale and maintain them. Bootstrap began as an answer to these challenges and quickly accelerated during Twitter’s first Hackweek. By the end of Hackweek, we had reached a stable version that engineers could use across the company.
----
```

![381341939257](https://f.cloud.github.com/assets/848187/115095/ecb5bc3a-6bc1-11e2-99e3-cb936d63fbbb.png)

The quote is just showing up like a blank code block. Any ideas?

**Comment by adamwitwer** [comment]
Hi Jake. AciiDoc uses underscores for blockquotes. I just updated that block and regenerated. It looks much better. The URL could break better, but that's a style issue that you can probably leave for production.

**Comment by whyisjake** [comment]
Yeah, nothing confusing about that... :)

Thanks.
