### ISSUE TITLE
Made changes to pr01.asciidoc undefined NaN, NaN, NaN:NaNPM 

### ISSUE THREAD

**Issue by elharo** [MakerPress/atlas-public-feedback#202]
On the changes view I see

 5881238c3c8da40ef5ba8fe6dc4ff835?s=25&d=identicon elharo@macfaq.com Made changes to pr01.asciidoc undefined NaN, NaN, NaN:NaNPM 

Notice all the NaN's. Something's gone wrong there.

**Comment by runemadsen** [comment]
Thanks @elahro. This is a known Firefox bug. I'll fix it tomorrow.

**Comment by runemadsen** [comment]
This has been fixed now. Let me know if you come across something that looks weird!
