### ISSUE TITLE
Build locally?

### ISSUE THREAD

**Issue by simonmar** [MakerPress/atlas-public-feedback#204]
I like to build my book on my local computer, before pushing to Atlas, because the turnaround time is much quicker. But the default Asciidoc/DocBook installation on Linux obviously doesn't have the O'Reilly stylesheets installed, so the output is quite different.  Is there a way to get them?

**Comment by odewahn** [comment]
Hi, Simon.  We use a proprietary tool called antennahouse to generate the final PDFs, so we can't make local installs available even if we wanted.  Sorry!

**Comment by simonmar** [comment]
ok, no problem.
