### ISSUE TITLE
Files Gone

### ISSUE THREAD

**Issue by davidtlang** [MakerPress/atlas-public-feedback#207]
This morning I couldn't save a file. Then, when I went back to my book, all my files had disappeared. Not sure...

**Comment by runemadsen** [comment]
Thanks. Looking into this right now. I believe the server is down. Will post update here.

**Comment by runemadsen** [comment]
Ok, this is fixed now. Sorry for the inconvenience.

**Comment by davidtlang** [comment]
Thanks! Phew... I hadn't thought to back up my marked-up work. I know differently now!

**Comment by runemadsen** [comment]
Yes, sorry. We backup all the files every day, so the most you should ever be able to loose are your current changes in the editor, if the server goes down. If you ever see "Save Failed", please file a an issue here and keep your browser window open. When the server is up again, you can press "Save" and it should save to the DB.
