### ISSUE TITLE
Images missing from epub

### ISSUE THREAD

**Issue by MikeW50** [MakerPress/atlas-public-feedback#209]
Building my book in PDF format works fairly well. Building the same book as an epub, all of the images show up as a broken link icon.

**Comment by sandersk** [comment]
Hi @MikeW50,

Could you please tell us which book you're working on in Atlas? We'd be happy to take a look and see why the EPUB images aren't showing up.

Thanks,
Sanders

**Comment by MikeW50** [comment]
Hi Sandra,

I guess that would help. :)

The book.s title is Building iPhone and iPad Electronic Projects.

The link I see it at is http://ano-atlas2.herokuapp.com/books/1234000000706.

I'm not sure if that's enough for you to identify it from your end. If you need more, let me know.

Mike Westerfield
Byte Works, Inc.
www.byteworks.us
505-280-3998

Check out techBASIC on YouTube!

**Comment by MikeW50** [comment]
This issue seems to be gone as of 11 April 2013.

**Comment by sandersk** [comment]
Great, glad to hear that @MikeW50. And my apologies that I neglected to follow up with you on this issue sooner. Please do let us know if you encounter any further issues moving forward.

Best,
Sanders
