### ISSUE TITLE
Add salting back to passwords (or swicth to ORM authentication)

### ISSUE THREAD

**Issue by MakerPress** [MakerPress/atlas-public-feedback#21]
We took off salting so that we could do auth in grack, but we should add it back in now that we're using our own auth layer.  Let's not wind up like linkedin:

http://www.nytimes.com/2012/06/11/technology/linkedin-breach-exposes-light-security-even-at-data-companies.html?_r=1&hp

The other thing we should think about is switching our auth layer to oreilly.com SSO entirely.

**Comment by zaremba** [comment]
I'm pretty certain that our authentication has evolved quite a bit since this was opened, but Rune please reopen this if this is still valid at all.
