### ISSUE TITLE
can't invite people

### ISSUE THREAD

**Issue by mikeloukides** [MakerPress/atlas-public-feedback#210]
just says "something went wrong"

**Comment by runemadsen** [comment]
Hi Mike

What email are you trying to put in?

Let me know and I'll try to fix it.
- Rune

**Comment by adamwitwer** [comment]
I believe the problem is fixed, Rune. The author said in another thread that he can get in now.

**Comment by mikeloukides** [comment]
Yes, I don't know what was wrong before, and I used the same email address both times. osamet67@gmail.com

**Comment by runemadsen** [comment]
Ok, great. Let me know if something else comes up.
