### ISSUE TITLE
Chimera build produces "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#211]
Attempting to rebuild HTML for http://ano-chimera.herokuapp.com/books/1234000000726/index.xhtml produces the error message in the title. This happened after I added the appendix-a.asciidoc file.

**Comment by odewahn** [comment]
This is fixed -- there was a typo in the template name

**Comment by jdeisenberg** [comment]
Thanks! If this is something I mistyped, please let me know how to avoid doing it again.

**Comment by odewahn** [comment]
Thanks, David.  (And, the new appendix looks great.)  I was changing the template this morning (It's on the "Admin" tab) and just put in the wrong thing.  So, it was my bad -- sorry!

Andrew

----- Original Message -----
