### ISSUE TITLE
Repository invisible on some systems

### ISSUE THREAD

**Issue by andyoram** [MakerPress/atlas-public-feedback#212]
I was added as a collaborator to the 1230000000289 project. I can view the book at home on an Ubuntu system, but not at work on a Mac. Another editor at work has also been unable to view the book; she is also on a Mac. When I try to visit the URL on my Mac at work, I just get my Atlas home page listing other books.

**Comment by adamwitwer** [comment]
Hi Andy. That's really strage. We're all on Macs. I see your title here:

http://atlas.labs.oreilly.com/books/1230000000289

Can you please take a screenshot (cmd+shift+3) of what you see at that URL on your Mac?

Thanks!
