### ISSUE TITLE
Can't push documents

### ISSUE THREAD

**Issue by mpcollins** [MakerPress/atlas-public-feedback#213]
## I've been running into what appears to be a github problem.  Whenever I try to push my latest commits to the main server, I get an rpc error.  Text follows:

$ git push
Password for 'https://mcollins@aleae.com@atlas-server.oreilly.com': 
Counting objects: 37, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (30/30), done.
Writing objects: 100% (30/30), 1.15 MiB | 803 KiB/s, done.
Total 30 (delta 13), reused 0 (delta 0)
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly

**Comment by odewahn** [comment]
Hi.  Try running this command on your git client:

git config http.postBuffer 524288000

Git restricts the size of the HTTP buffer to 2MB by default. If you have a repo with lots of images, though, you might need a bigger buffer, as described here:

http://stackoverflow.com/questions/2702731/git-fails-when-pushing-commit-to-github

----- Original Message -----

**Comment by mpcollins** [comment]
And that worked!  Danke schön

**Comment by davidsklar** [comment]
I had the same problem and "git config http.postBuffer 524288000" solved it for me, too. Yay.
