### ISSUE TITLE
PDF has garbled code 

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#216]
Created a PDF for "Études for Erlang"; all the code samples in Appendix A as well as headings that include plus signs for monospace formatting are totally garbled. Looks like every character has been replaced by its ASCII value minus two. See attached screenshot.
![weird_pdf](https://f.cloud.github.com/assets/160096/215538/55cf989a-8494-11e2-92da-89f8de15f1e3.png)

This only happens when I look at the PDF in the browser window. If I download the file, it looks great when viewed in Acrobat reader.

**Comment by sandersk** [comment]
Hi David,

Which browser are you using to view the PDF? The PDF looks fine for me in Acrobat, as well as in Safari for Mac's browser window.

Our PDFs should render properly in most major PDF readers, but we can't guarantee full rendering support for every single PDF reader available.

Thanks,
Sanders

**Comment by jdeisenberg** [comment]
I'm using Firefox 19 on Ubuntu (at the school) and a comparably new version of Firefox on Fedora 17 at home.

**Comment by sandersk** [comment]
Ah, yes we've seen that some Linux PDF readers may have issues rendering our PDFs. We'd recommend that you stick with Acrobat for PDF review.

Thanks,
Sanders
