### ISSUE TITLE
Selected Code should be Included in Block

### ISSUE THREAD

**Issue by tobrien** [MakerPress/atlas-public-feedback#217]
When using the web-based asciidoc editor, I found the following interaction a bit frustrating from a user experience perspective.
1. Type in a code example
2. Select the code example
3. Click on Blocks -> Code Block 
4. Select a language
5. Click on OK.

At this point, the system simply replaces the code I had initially selected and drops in a blank code listing.     It would be better if this interaction were aware of the text I had initially selected.

**Comment by runemadsen** [comment]
Thanks @tobrien. Should be easy to do. I'll look at it as soon as I can.
