### ISSUE TITLE
Save buttons seem so 2005

### ISSUE THREAD

**Issue by tobrien** [MakerPress/atlas-public-feedback#218]
I'm working on a chapter in the web-based asciidoc interface and I notice that there's a inconspicuous save button in the upper right hand corner.    

Why not save periodically?   Why not just update the content and then provide some interface to browse through history?   I only ask because I was using this editor and I happened to get distracted for a few minutes.  When I came back to the interface, I realized that I had poured an hour of effort into something that hadn't been sent back to the server.

That scares me.  (I scare easily.)

I don't know if you use sessions to keep track of users, but if you do and they have an expiration this could create a nightmare writing scenario.    If you were working on a particular important chapter there's a chance that you might get lost in the writing process.    Hours pass and you go to click the Save button only to realize that your work is lost.    Haven't tested this, won't.

**Comment by runemadsen** [comment]
The reason why we chose the "normal" save over an automatic save is that we're committing to Git repos. As power users are committing to Git via the command line, we wanted the system to emulate Git behavior as close to possible, and if we enabled auto-save, there would be a ton of commits with the same name, with only a few characters in each.

This may still be the best route, but for now we just did a normal save button.

**Comment by adamwitwer** [comment]
FYI, ctrl-s or cmd-s works as a keyboard shortcut so that you don't have to click save button. It's not the automatic save that you're looking for, but in my personal experience, the keyboard shortcut makes it easier to save more often.

**Comment by runemadsen** [comment]
One other thing is that the window will alert you if you try to close it without saving.

**Comment by tobrien** [comment]
Sounds good, I see a warning if I attempt to close it.   BTW, the interface looks awesome.

**Comment by tobrien** [comment]
Closing it, because I can.

**Comment by runemadsen** [comment]
Great. Thanks. Please keep the feedback coming. It's great to hear these things, so we're not working in a vacuum.
