### ISSUE TITLE
It would be great to get a 'rebuild' button

### ISSUE THREAD

**Issue by sh1mmer** [MakerPress/atlas-public-feedback#22]
Most of the build processes I am doing involve the same files as I'm using the build process to look at the "finished" book. It would be great to have a "rebuild" button that just prints the same config as the last build.

**Comment by MakerPress** [comment]
Great suggestion -- thanks, Tom!

----- Original Message -----
From: Tom Hughes-Croucher reply@reply.github.com
To: MakerPress makerpressadmin@oreilly.com
Sent: Tue, 12 Jun 2012 03:07:52 -0400 (EDT)
Subject: [atlas-public-feedback] It would be great to get a 'rebuild' button (#22)

Most of the build processes I am doing involve the same files as I'm using the build process to look at the "finished" book. It would be great to have a "rebuild" button that just prints the same config as the last build.

---

Reply to this email directly or view it on GitHub:
https://github.com/MakerPress/atlas-public-feedback/issues/22

## 

Andrew Odewahn
Chief Technology Officer
O'Reilly Media
617-460-6693

**Comment by adamwitwer** [comment]
So I believe we have this in place now. Atlas automatically defaults to including the files used in the previous builds. Please reopen if it's not working as you'd hoped.
