### ISSUE TITLE
Deleting a Chapter in the Asciidoc Editor

### ISSUE THREAD

**Issue by tobrien** [MakerPress/atlas-public-feedback#220]
Maybe I'm missing something.   I was looking for a way to delete a chapter file on Atlas.   From the Asciidoc editor I was looking for something that would hint of this, I tried right-clicking on the name, nothing.   Just wondering if there's a way to do this?

**Comment by runemadsen** [comment]
Nope. Not possible right now :-) You can imaging that it's on the list.
