### ISSUE TITLE
Location of Latest Builds "Threw me for a Loop"

### ISSUE THREAD

**Issue by tobrien** [MakerPress/atlas-public-feedback#221]
I'm on the Builds page, I triggered a PDF build.   Then I went to go grab some coffee.  I come back, I'm wondering where my PDF is.   The screen doesn't give me a hint, so I click on Builds.  I would expect some indication that the PDF is ready on that build screen.

Not finding it, then I click on Dashboard.  I see the latest builds on the dashboard.  I wonder if it may make sense to put this latest build on the Builds page as well?

**Comment by ceteri** [comment]
Yes, this was really confusing.  Also, when I'm at the "Latest Builds" page and try to refresh, now it submits another build. That changed from previous behavior -- is there anyway to workaround that?

**Comment by runemadsen** [comment]
@ceteri unfortunately that's a current bug in Chrome. When you refresh a page you were redirected to, it will reload the former request. This is broken behavior in Chrome, and nothing we can anything about unfortunately.

But this is great feedback.

**Comment by odewahn** [comment]
Thanks for reporting this -- it's a total annoyance. One thing that might help, though, is we've soft-launched a new feature for the Atlas, which is a chatbot that lives in the right sidepanel of the writing environment.

One of its jobs is to notify you when your build completes, which is probably a big reason that you're trying to hit refresh in the first place.  So, if you just leave that sidepanel open during the built, you'll get a message when the build finishes.

We'll be talking a lot more about its other functions in the weeks to come.  So, give it a look and see what you think.

Andrew

----- Original Message -----
