### ISSUE TITLE
Chrome shows form re-submit warning on builds page

### ISSUE THREAD

**Issue by mrflip** [MakerPress/atlas-public-feedback#224]
So I'm seing something I hadn't before: Slamming "refresh" on the /builds page (which is what I like to do when I'm on the /builds page) all of a sudden started giving me a form resubmit confirmation.

After lovingly crafting a bug report it turns out this is a bug in Chrome not Atlas. But I have enough sunk cost in finding that out that I'll save anyone else who hits this the trouble: 
https://code.google.com/p/chromium/issues/detail?id=177855&q=reload&colspec=ID%20Pri%20Mstone%20ReleaseBlock%20OS%20Area%20Feature%20Status%20Owner%20Summary

(close this issue, I just want to make it searchable)

**Comment by sandersk** [comment]
Thanks @mrflip for pinpointing this as a Chrome-specific bug. I'll go ahead and close the ticket, and hopefully the bug will be fixed soon :)

Sanders
