### ISSUE TITLE
Request from author to add support for orgmode as an input format

### ISSUE THREAD

**Issue by sarahs** [MakerPress/atlas-public-feedback#226]
Stephen Nelson-Smith recently sent this message to Tools:

> Aaron and I are collaborating on the 2nd edition of Test Driven
>    Infrastructure, and Chef: The Definitive Guide.  We're using Atlas,
>    which we both agree is seriously awesome.
> 
> However, as dyed-in-the-wool Emacs users, we write in orgmode.
>    Orgmode is actually superb for structured text, but rather than
>    evangelise, I'll get to the point…
> 
> It would be absolutely brilliant if you could add support for orgmode
>    as an input format, in addition to markdown and asciidoc.  Markdown
>    is ok, but (as you acknowledge) is limited for serious document
>    writing.  Asciidoc is fine, but Emacs lacks good asciidoc support,
>    and the suite of tools provided within orgmode eclipse it for
>    productivity.
> 
> It's theoretically possible to convert orgmode to asciidoc using
>    either pandoc or babel, but it's a bit fiddly, requiring multiple
>    passes.  What I've done in the past is export orgmode as docbook
>    (which works just fine), so if that works for book building,
>    perhaps that's an option.
> 
> I could invest the time writing a filter in Emacs LISP that produces
>    asciidoc, but frankly I think my time would be better spent writing
>    the book(s)… I'm sure Meghan and Courtney would agree :)
> 
> So - if you chaps could have a think about the best way to support
>    orgmode authors, we (and every other Emacs-using author) would be
>    most grateful!

I told him that converting to DocBook is probably his best option for this book, but I also promised I'd pass his request along to the Atlas team, so that's what I'm doing!

Thanks,
Sarah

**Comment by sandersk** [comment]
Thanks, Sarah. We don't have any plans to support authoring in Org mode in the near future, so I'll close this ticket.
