### ISSUE TITLE
Atlas build seems to have cached old PDF, can't get it to update

### ISSUE THREAD

**Issue by sarahs** [MakerPress/atlas-public-feedback#227]
Hi Rune, Sanders, et al.

In this book:

http://atlas.labs.oreilly.com/books/1234000001505/

there's a file called tdi2-whole.xml from which the author made a PDF a few days ago. The XML was messy, so the PDF had a bunch of XML tags in it.

I committed a cleaned-up file called tdi2-whole_clean.xml. This makes a nice PDF for me locally, but when I build it in Atlas, it keeps generating the old tag-filled PDF. It's like the old one is cached or something.

I tried renaming my clean file to book.xml, but then I got this:

```
Job failed
Full error:
DCPS Error Log

/usr/local/app/worker/tmp/pdf/1234000001505/book.xml
```

Can you help? Jess says this has come up before.

Thanks!
Sarah

**Comment by sandersk** [comment]
Discussed with Sarah offline. This error was related to badly formed XML in the repo, which Sarah is going to set aside. Sarah, please reopen this ticket if you still encounter problems with the PDF builds.

Thanks,
Sanders
