### ISSUE TITLE
Changes tab error

### ISSUE THREAD

**Issue by jhosman** [MakerPress/atlas-public-feedback#229]
Hi,

The author of Learning R reported that the changes tab for his book (http://atlas.labs.oreilly.com/books/1230000000829) is throwing a 500 error: "We're sorry, but something went wrong..."

Any idea what could be causing this?

Thanks!
Jess

**Comment by richierocks** [comment]
It would be quite useful to know if this happens for anyone else, or just me.  Also, if any other authors are experiencing this problem.

**Comment by sandersk** [comment]
Hi @richierocks,

I took a look at the AsciiDoc content, and I've pinpointed that line 7288 of the file Cotton_Learning_R.asciidoc is what's causing the Changes tab to fail:

```
An \221xts\222 object on 2007-01-03/2013-03-20 containing:
```

There's an encoding issue with those characters \221 and \222, which is causing our Rails app to fail. Those look like Windows Character codes for curly single quotes, correct? If you were to switch to Unicode encodings instead, I believe that should solve the problem. We'll also look further into this character-encoding issue on the Rails side to see if we can prevent issues like this from recurring.

Hope this helps. Let us know if you need any further assistance here.

Thanks,
Sanders
