### ISSUE TITLE
Build / Rebuild from Git

### ISSUE THREAD

**Issue by sh1mmer** [MakerPress/atlas-public-feedback#23]
The SVN docbook system has a commit hook for "ora:commitpdf" in the commit message. It would be good to get that kind of thing on this system.

I don't know what the exact mechanism would be (tag, commit message, etc) but something to push changes and then get a built PDF book would be great.

**Comment by MakerPress** [comment]
Great suggestion, Tom.  We'll put this on the roadmap.

Andrew

----- Original Message -----
From: Tom Hughes-Croucher reply@reply.github.com
To: MakerPress makerpressadmin@oreilly.com
Sent: Mon, 18 Jun 2012 11:53:42 -0400 (EDT)
Subject: [atlas-public-feedback] Build / Rebuild from Git (#23)

The SVN docbook system has a commit hook for "ora:commitpdf" in the commit message. It would be good to get that kind of thing on this system.

I don't know what the exact mechanism would be (tag, commit message, etc) but something to push changes and then get a built PDF book would be great.

---

Reply to this email directly or view it on GitHub:
https://github.com/MakerPress/atlas-public-feedback/issues/23

## 

Andrew Odewahn
Chief Technology Officer
O'Reilly Media
617-460-6693
