### ISSUE TITLE
Invalid Error preventing account save: Current password can't be blank

### ISSUE THREAD

**Issue by java-javascript** [MakerPress/atlas-public-feedback#230]
When trying to save account info (just added name) the text says don't enter anything in the password field if you don't want to modify it.  But there is a problem on save:

Account
1 error prohibited this user from being saved:
Current password can't be blank

**Comment by runemadsen** [comment]
Hi there. Yes, this is a little weird, and we should fix it. You need to leave the "New Password" fields blank, but put your current password in the last password field, in order to update your profile.
