### ISSUE TITLE
Cookbook stylesheet not being pulled in for Atlas build

### ISSUE THREAD

**Issue by jhosman** [MakerPress/atlas-public-feedback#231]
Hi,

PHPUnit Cookbook (http://atlas.labs.oreilly.com/books/1234000000554) is set up on both the admin tab and in the book.asciidoc file to use the cookbook stylesheet, but when I build in Atlas the problems and solutions are still showing up in the toc. When I build locally using csspdf, the pdf renders correctly without those items in the toc. Any idea why Atlas and csspdf would be generating different pdfs?

Thanks!
Jess

**Comment by odewahn** [comment]
Did you just change the template?  There is a small bug on the build screen that requires you to update the build list before it will apply the new template.  Try taking a file out and putting it back in, and then rebuild.

Andrew

----- Original Message -----

**Comment by jhosman** [comment]
Yup, that sounds like it was the problem. Good to know. Meanwhile I just added the bookseries to the book.asciidoc file locally, and pushed it to Git, and that seems to have worked too. Thanks!
