### ISSUE TITLE
Reordering "Files to build"

### ISSUE THREAD

**Issue by jhosman** [MakerPress/atlas-public-feedback#232]
Hi,

Forgive me if I'm totally missing something, but I can't figure out how to reorder the files in the "Files to build" section of the build page. I used to be able to drag each file up or down, but now it won't let me. I'm using Firefox.

Thanks!
Jess

**Comment by runemadsen** [comment]
Wow, you're right. This is totally broken. I'll look at it right away.

A thing you can do right now is to just edit the book index in the editor:

http://atlas.labs.oreilly.com/books/ISBN/versions/master/editor/book.asciidoc
- Rune

**Comment by jhosman** [comment]
Thanks Rune!

**Comment by runemadsen** [comment]
This should be fixed now. Please test and close the issue if it works for you.

Note to self: Atlas V2 should have javascript tests.

**Comment by jhosman** [comment]
Works great now, thanks!
