### ISSUE TITLE
[source, erl] code shows up in proportional font in Chimera

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#234]
This URL: http://chimera.labs.oreilly.com/books/1234000000726/ch07.html#CH07-ET01 shows source code formatted as [source, erl] in asciidoc. It shows up in a proportional font in Chimera. epub and PDF format show a fixed-width font.

**Comment by adamwitwer** [comment]
Hi @jdeisenberg. Thanks for letting us know. We intend for the source code to be in a non-proportional font. Can you let us know which browser and OS you are using? Thank you.

**Comment by jdeisenberg** [comment]
Ubuntu 12.10, Firefox 19.0. Also shows up as a proportional font in Konqueror 4.9.4. Web error console in Firefox has oodles of warnings about CSS declarations, then this: 

Timestamp: 03/20/2013 11:41:17 AM
Error: downloadable font: download failed (font-family: "heading" style:normal weight:normal stretch:normal src index:0): bad URI or cross-site access not allowed
source: http://orm-social-book-dev.s3.amazonaws.com/templates/rune/Gotham-Book.ttf
Source File: http://chimera.labs.oreilly.com/assets/default-a68cfd26d7bb96d0dfc3435130d3ce6b.css
Line: 0
Source Code:
@font-face {   font-family: "heading";   src: url("http://orm-social-book-dev.s3.amazonaws.com/templates/rune/Gotham-Book.ttf"); }

**Comment by jdeisenberg** [comment]
More info: displays proportional font on Firefox or Chrome under Fedora 17, but displays monospace under both Internet Explorer and Firefox on Windows 7.

**Comment by adamwitwer** [comment]
Thanks very much. I think we've figured it out. You should see a fix within the next day or so.

**Comment by nelliemckesson** [comment]
Hey @jdeisenberg this should be all set - let me know if you're still seeing problems!

**Comment by jdeisenberg** [comment]
On Tue, Mar 26, 2013 at 9:18 AM, Nellie McKesson
notifications@github.com wrote:

> Hey @jdeisenberg this should be all set - let me know if you're still seeing problems!

The font is now monospaced, but blanks show up as solid blocks using
the default settings for fonts.
