### ISSUE TITLE
Make hubot panel visible on all project pages

### ISSUE THREAD

**Issue by jhosman** [MakerPress/atlas-public-feedback#235]
Hi,

It would be great if the hubot panel would show on all pages of a book project in Atlas, not just the Write page. The info about build status especially would be great to see from the dashboard, for example. I find it a bit confusing that I can only see it when writing, since it seems like a tool that's relevant to all aspects of the book, not just the writing process.

Thanks!
Jess

**Comment by runemadsen** [comment]
Thanks @jlhosman. This is also a thing that will get much better with the new release. Thanks for posting.
