### ISSUE TITLE
Quicker steps to cloning a repository

### ISSUE THREAD

**Issue by andyoram** [MakerPress/atlas-public-feedback#241]
I think the most common use for the Admin page is to clone the repository. (That's the only way I ever use the Admin page, being a reviewer.) You might consider adding a "Clone" button so that the URI is easier to find and more intuitively located.

**Comment by sandersk** [comment]
Sorry for the delayed response @andyoram. Yes, I agree it would be good to make the Git URL more prominent, and  we'll look into making a better user experience for this in the next release of Atlas.

Sanders
