### ISSUE TITLE
git push hangs up

### ISSUE THREAD

**Issue by ceteri** [MakerPress/atlas-public-feedback#244]
A problem began this afternoon -- which had been working okay this morning.

If I include 2+ new images in a commit, then the push hangs up.
If I constrain changes to 1 new image in a commit, the push works fine.

They aren't huge images, hopefully :)

bash-3.2$ git push
Password for 'https://ceteri@gmail.com@atlas-server.oreilly.com': 
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by ceteri** [comment]
isolating this further, it looks like the remote git push is hanging up when an image is > 1Mb

i had images which were +950Kb and those worked fine, but one tipped the 1Mb threshold.

could that be the reason for remote hang up?

**Comment by sandersk** [comment]
Hi Paco,

Yes, you just need to increase the HTTP buffer size to allow larger files to be pushed. Try running the following command:

git config http.postBuffer 524288000

And then run your "git push" again, and it should succeed this time. 

Let me know if you still encounter problems.

Thanks,
Sanders

**Comment by ceteri** [comment]
many thanks! 
works perfectly
