### ISSUE TITLE
Avoid having Atlas invites flagged as spam

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#245]
(Thanks to Rob Faludi for shedding light on why this happens.)

I've heard from a few authors over time that invites end up being marked as spam. It looks like there are a couple things that could be done to avoid this problem:
- Include a plaintext alternative to the HTML.
- Avoid embedded invisible images

Here are the relevant scores and headers:

```
X-Spam-Flag-Was: YES
X-Spam-Score: 6.707
X-Spam-Level: ******
X-Spam-Status: Yes, score=6.707 tag=-999 tag2=2.5 kill=3.5 tests=[HTML_IMAGE_ONLY_16=2.646, HTML_MESSAGE=0.001, HTML_MIME_NO_HTML_TAG=1.661, MIME_HTML_ONLY=2.299, RDNS_NONE=0.1] autolearn=disabled
```

Thanks,

Brian

**Comment by zaremba** [comment]
Hi @bjepson, thanks for this feedback. I believe changes have been implemented to prevent invitation emails from getting filtered as spam. Please let me know if you're still hearing these reports.

Thanks,
Adam
