### ISSUE TITLE
"Opening and ending tag mismatch" ?

### ISSUE THREAD

**Issue by ALRubinger** [MakerPress/atlas-public-feedback#246]
Full Error: http://ano-atlas2.herokuapp.com/books/122/jobs/25454

Thoughts?  Works fine w/ AsciiDoctor implementation used by GitHub engine.

**Comment by sandersk** [comment]
Hi @ALRubinger,

In Chapter02-EnablingTechnologies.asciidoc, there were a few code listings that had [source] lines that did not specify a code language, like this:

```
[source]
----
archive.jar:
/java/
/java/lang/
/java/lang/String.class
/java/lang/Integer.class
----
```

In our toolchain, [source] declarations must contain a language parameter, like this:

```
[source, java]
```

Or the output will be invalid. If you don't intend to specify a language, you can just drop the [source] line entirely, like this:

```
----
archive.jar:
/java/
/java/lang/
/java/lang/String.class
/java/lang/Integer.class
----
```

For now, I went ahead and stripped out the few [source] lines without languages specified in Chapter02-EnablingTechnologies.asciidoc, and was able to build a PDF successfully. Let me know if you have any questions or encounter any further issues, though.

Thanks,
Sanders

**Comment by ALRubinger** [comment]
Thanks, Sanders!
