### ISSUE TITLE
How do I get a login account for Atlas?

### ISSUE THREAD

**Issue by thecontentwrangler** [MakerPress/atlas-public-feedback#247]
I'd love to test Atlas out. Can someone tell me how to get an account set up?

Scott Abel
The Content Wrangler

**Comment by annegentle** [comment]
Hi Scott, fancy seeing you here. I understand Atlas is an invite-based system. Hopefully you can find a contact at O'Reilly who can send you an invitation to try it out. I love that it's git-backed.

**Comment by thecontentwrangler** [comment]
Anne:

I have connected with O'Reilly and am good to go. Thanks!

Looking forward to seeing you soon.

Scott

On Apr 30, 2013, at 11:09 AM, Anne Gentle notifications@github.com wrote:

> Hi Scott, fancy seeing you here. I understand Atlas is an invite-based system. Hopefully you can find a contact at O'Reilly who can send you an invitation to try it out. I love that it's git-backed.
> 
> —
> Reply to this email directly or view it on GitHub.

Scott P. Abel
The Content Wrangler, Inc.
4153 24th Street #4
San Francisco, CA 94114

www.thecontentwrangler.com
scottabel@mac.com
415.857.2235 office
317.409.0839 mobile
about me: http://about.me/scottpatrickabel

CONTENT STRATEGY WOES? YOU'RE NOT ALONE.
Content Strategy Workshops comes to Vancouver, July 2013.
Register today and save!
www.contentstrategyworkshops.com

**Comment by grebeccahaines** [comment]
Hi Scott and Anne:
I am a society publisher and serious non-technical noob. I'm interested in learning more about Atlas. Can you point me in the right direction at O'Reilly to get more information or insight?

Thanks
Becky Haines
Sr. Director, ACR Press
American College of Radiology

**Comment by thecontentwrangler** [comment]
Becky:

Send me an email (scott@thecontentwrangler.com) and I will set up a brief call with you. I'm happy to try and help.

Scott

**Comment by sandersk** [comment]
Hi Becky,

The Atlas platform is currently in closed beta, but we'd love to talk further to you Atlas. Do you have an email or phone # at which we can reach you.

Thanks,
Sanders

---

Sanders Kleinfeld
Publishing Technology Engineer
O'Reilly Media Inc.

**Comment by grebeccahaines** [comment]
Thanks Sanders:

My contact information is noted below:

Becky Haines
Sr. Dir., ACR Press
American College of Radiology
1891 Preston White Dr.
Reston, VA 20191
bhaines@acr.org
703-390-9850
