### ISSUE TITLE
No space left on device error

### ISSUE THREAD

**Issue by troymott** [MakerPress/atlas-public-feedback#248]
When trying to build the Web Design Bibliography I'm getting the following error for mobi and epub and the PDF isn't building:

Job failed
Full error:

No space left on device - /tmp/systemu_atlas-worker_3460_3463_0.4166491153124927_1

--Troy

**Comment by runemadsen** [comment]
Thanks. I'm fixing this as we speak!

**Comment by troymott** [comment]
Thank you, it is working now!
