### ISSUE TITLE
Cancel pending builds

### ISSUE THREAD

**Issue by mulderp** [MakerPress/atlas-public-feedback#249]
So far the builds all worked fine, however, now I get some builds that are 'pending' (since 1 hour). Maybe it would be good to have something to cancel the build, and inspect some logs, to see where a problem occurs.

**Comment by runemadsen** [comment]
Thanks. I'm fixing this as we speak!

**Comment by runemadsen** [comment]
You should see your builds as either "succeeded" or "failed" now. We had some problems with space on our build HD, but it's fixed now.

**Comment by mulderp** [comment]
Thanks, Rune! It looks green again :+1:
