### ISSUE TITLE
Add support for Undo

### ISSUE THREAD

**Issue by shelleyp** [MakerPress/atlas-public-feedback#250]
In addition to spellcheck (in another issue), you really need to ensure Undo works. These are two fundamental editing tools we've all become dependent on, regardless of our writing environment.

**Comment by zaremba** [comment]
Hi @shelleyp, thanks for this feedback. We've made sure that the undo and redo keyboard shortcuts are fully supported in the new version of Atlas (currently in beta), and we're exploring ways to make the functionality obvious in the UI as well.

Thanks,
Adam

**Comment by shelleyp** [comment]
Very cool, thank you @zaremba-oreilly

**Comment by shelleyp** [comment]
You know what else would be extremely nice @zaremba-oreilly ?

The ability to search on and/or replace text. 

Autosave, especially an autosave that can be manually configured. 

These are two other items that I've desperately missed with Atlas 1.0.

I would add these if missing in Atlas 2, but don't have access to the beta. I'm hoping this functionality is there.
