### ISSUE TITLE
Would like quick way to download existing PDF

### ISSUE THREAD

**Issue by andyoram** [MakerPress/atlas-public-feedback#251]
So far as I see, if I want to view the most recent PDF (or any PDF), I first have to request a build.

**Comment by adamwitwer** [comment]
Hi Andy. You can download the latest PDF from the Dashboard.

**Comment by andyoram** [comment]
Thanks, I hadn't thought of checking there. 

Andy 

----- Original Message -----

**Comment by adamwitwer** [comment]
Sure thing, Andy. The next version of Atlas will likely include download links from within the editing interface.
