### ISSUE TITLE
Multiple authors?

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#252]
I just added my author blurb to the metadata for a book by directly editing book-docinfo.xml. When I look at the metadata on Atlas, it lists my name first (probably going by alphabetical order of surname), but I'm the secondary author. I didn't rebuild the book, so I'm not sure how the cover or back material will come out -- in alphabetical order or in document order, where my &lt;author&gt;...&lt;/author&gt; is after the primary author's info.

**Comment by jhosman** [comment]
Hi @jdeisenberg , the author bios will render on the colophon page in the order they appear in the book-docinfo.xml file. No need to worry about it for now, though. Your production editor will check it once the book is submitted to production. Thanks!
