### ISSUE TITLE
Horizontal lists rendered poorly

### ISSUE THREAD

**Issue by clintongormley** [MakerPress/atlas-public-feedback#254]
Hiya, when using a horizontal list like:

```
[horizontal]
name:: definition
name:: definition
```

each row is rendered with too much vertical whitespace, but not enough white space on the right hand side of the `name` box.  For instance, see two lists under:

http://chimera.labs.oreilly.com/books/1230000000825/ch03.html#_core_simple_field_types

thanks

**Comment by zaremba** [comment]
Hi @clintongormley, sorry for the very delayed response here. If you're still using Chimera and experiencing this problem please reopen this ticket and someone will take a look.

Thanks,
Adam

**Comment by clintongormley** [comment]
Hi @zaremba-oreilly 

I can't reopen this ticket (you can) but yes, horizontal lists are still rendered poorly.  For example, have a look at this section:

http://chimera.labs.oreilly.com/books/1230000000825/ch05.html#multi-index-multi-type

**Comment by christopappas** [comment]
Hi @clintongormley,

Although horizontal list markup is valid, the Atlas toolchain does not really support it.
Instead of using the horizontal list markup, you might try using an informal table to achieve a similar look. 

In place of:

```
[horizontal]

_Mapping_::     how the data in each field is interpreted
_Analysis_::    how full text is processed to make it searchable
_Query DSL_::   the flexible, powerful query language used by Elasticsearch
```

you could try something like:

```
|=======
|_Mapping_     |how the data in each field is interpreted
|_Analysis_    |how full text is processed to make it searchable
|_Query DSL_   |the flexible, powerful query language used by Elasticsearch
|=======
```

Hope this helps,
Chris

**Comment by clintongormley** [comment]
Hi @christopappas 

You misunderstand me. I'm perfectly happy with how docbook renders horizontal lists as a table.  We use this layout extensively on the Elasticsearch docs already.  

All I'm suggesting is that the CSS for the table needs some work. For instance, there is way too much vertical margin on the `p` elements within each row, and not enough horizontal padding between cells.  This results in an excess of vertical whitespace, but not enough separation between columns.  Compare the same table on:
- Chimera: http://chimera.labs.oreilly.com/books/1230000000825/ch05.html#multi-index-multi-type
- Elasticsearch: http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/multi-index-multi-type.html#multi-index-multi-type

**Comment by christopappas** [comment]
Hi @clintongormley,

Ah, I see. In that case, we'll pass your table CSS suggestion along to the designers.

Thank you for your feedback!

Sincerely,
Chris
