### ISSUE TITLE
Including admonition blocks

### ISSUE THREAD

**Issue by richierocks** [MakerPress/atlas-public-feedback#255]
If I try to include admonition blocks (http://asciidoc.org/userguide.html#X22) then Atlas throws a warning during the build, for example

```
asciidoc: WARNING: MyFile.asciidoc: line 123: missing style: [blockdef-listing]: TIP
```

It would be useful to have support for TIPs, WARNINGs, etc.

**Comment by sandersk** [comment]
Hi @richierocks,

We do indeed support admonition blocks as described in the AsciiDoc User Guide. I took a look at your book, and it appears that in your file Cotton_Learning_R_Chapter16_Programming.asciidoc, the incorrect delimiter was used for admonition blocks: they should be delimited with equals signs, not hyphens. For example, a "tip" admonition should look like this:

```
[TIP]
====
Text for the Tip goes here
====
```

Hope this helps. Could you try making these corrections and then let me know if you encounter any further issues when building?

Thanks,
Sanders

**Comment by sandersk** [comment]
Closing this ticket, as I'm assuming I've answered your question, @richierocks. Let me know if you have any further questions or run into any further issues.

Thanks,
Sanders
