### ISSUE TITLE
Trying to embed an underscore in a filename by escaping it

### ISSUE THREAD

**Issue by andyoram** [MakerPress/atlas-public-feedback#259]
Asciidoc is supposed to allow an underscore character into the text if I use \ before it. This is not working in Learning Android on p. 39.

**Comment by jhosman** [comment]
Hi Andy,

I'm assuming you're talking about this text in ch03.asciidoc:

 _resources.ap__

Markup like that can be tricky, so you could try instead using the double dollar sign markup. That tells it to translate literally everything inside the dollar signs. For example:

_$$resources.ap_$$_

Give that a shot, and let me know if you're still running into problems.

Thanks!
Jess
