### ISSUE TITLE
Add Image Returns Error 500

### ISSUE THREAD

**Issue by mrichardson23** [MakerPress/atlas-public-feedback#26]
Clicking on the toolbar button in the editor to add an image shows a window with the number 500 and "We're sorry, but something went wrong. If you think this is a bug, please report it." Before getting this error, I accidentally uploaded an image with a space in the file name. Perhaps that had something to do with it?

**Comment by MakerPress** [comment]
Hi, Matt.  The space in the name is probably the issue. Can you make me a collaborator and I can try to fix it?  (Or, if you're a git fan, you can clone the repo down and rename the file, which is what I'll be doing...)

Andrew

----- Original Message -----
From: Matt Richardson reply@reply.github.com
To: MakerPress makerpressadmin@oreilly.com
Sent: Wed, 04 Jul 2012 14:51:55 -0400 (EDT)
Subject: [atlas-public-feedback] Add Image Returns Error 500 (#26)

Clicking on the toolbar button in the editor to add an image shows a window with the number 500 and "We're sorry, but something went wrong. If you think this is a bug, please report it." Before getting this error, I accidentally uploaded an image with a space in the file name. Perhaps that had something to do with it?

---

Reply to this email directly or view it on GitHub:
https://github.com/MakerPress/atlas-public-feedback/issues/26

## 

Andrew Odewahn
Chief Technology Officer
O'Reilly Media
617-460-6693

**Comment by mrichardson23** [comment]
Andrew, I just renamed the file locally and pushed the changes, including the filename reference in the asciidoc. However, the image file isn't coming through in the HTML view now. Opening the image in a new tab returns an "access denied" error. I'll add you as a collaborator. It's in ch02.asciidoc and the file is Extracting-XZ-cropped.png

**Comment by MakerPress** [comment]
Thanks, Matt.  Yes, this is a known issue we're working on fixing -- the image preview in the HTML view only works when you upload or name an image through the Image uploader.  It does not (yet) work for images uploaded in git.  We're working on a post-commit hook that will fix this by uploading the images to S3, but it's still a bit of a ways off.  

Now that you're no longer getting a 500 error, I'd just suggest re-uploading the image, this time without a space in the name, and it should take care of everything.  

Sorry for the trouble, but keep the suggestions coming!

Andrew

----- Original Message -----

**Comment by runemadsen** [comment]
This is fixed now. Spaces in images are working.
