### ISSUE TITLE
maker4c: Table titles are not appearing

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#260]
Hi,

I recently noticed that table headers aren't showing up (they are black against a black background). But if I add the following oneoff, they appear:

thead, thead tr, thead tr td, thead tr p {
  color: cmyk(100%,0%,0%,20%); 
  background-color: cmyk(0%,0%,0%,0%);
}

Before and after images attached.

![01 before](https://f.cloud.github.com/assets/278746/580085/0617c93c-c880-11e2-8c7c-4af55f16aa79.png)
![02 after](https://f.cloud.github.com/assets/278746/580292/92b103a0-c884-11e2-8f81-2746b6faef51.png)

Thanks,

Brian

**Comment by sandersk** [comment]
@nelliemckesson @adamwitwer, do either of you want to take a look at this one?

Thanks,
Sanders

**Comment by nelliemckesson** [comment]
oh i feel like i fixed this a while ago maybe? lemme check.

**Comment by nelliemckesson** [comment]
alright this is all set

**Comment by nelliemckesson** [comment]
@sandersk i don't have permission to close issues in this queue apparently. Can you close?

**Comment by jhosman** [comment]
Hi @nelliemckesson, the maker4c table heads are now showing up as white on light blue, which is really hard to read. Could you take a look?

This example is from The Makerspace Workbench (http://atlas.labs.oreilly.com/books/1230000000789/)

![screen shot 2013-08-06 at 11 15 05 am](https://f.cloud.github.com/assets/1183847/917876/325cfd8a-feab-11e2-8562-122d3169cdbe.png)

**Comment by nelliemckesson** [comment]
this is actually due to customizations in the oneoff. @adamwitwer can you close?

**Comment by bjepson** [comment]
If I recall correctly, I made the background light blue in the oneoff to workaround the earlier problem of the headers being black on a black background. @jlhosman do you want to change the oneoff or do you want me to look at it? 

I'm trying to git pull right now, but I'm not sure I'll be able to pull it down if the repo has gotten too big.

**Comment by jhosman** [comment]
Hi @bjepson, I can take care of it. Thanks!

**Comment by bjepson** [comment]
Thank you! Sorry for leaving that little mess there!

Hastily typed by thumbs

**Comment by jhosman** [comment]
No worries, @bjepson! It was an easy fix:)
