### ISSUE TITLE
Rename button on Atlas Web doesn't use Git mv, breaks file history

### ISSUE THREAD

**Issue by hexagon5un** [MakerPress/atlas-public-feedback#261]
Hey folks,

I actually just did a quick search of the issues and found that this has been noted before, but we got bitten by it last week, so I thought I'd bring it up again.

We have one writer (me) working from the git repo directly, and an editor who's using the online Atlas interface.  When he renames/moves a file, the underlying git deletes the old version and creates a new one rather than moving/renaming it.  

The problem is that I've got local changes to a file that's now deleted, (and with different line-endings, but that's a red herring).  The two of us are editing the same content, but in two differently-named files.

This caused me to have to think about it hard for a few minutes before I figured out how to make the merge work in a way that I could easily see my editor's comments between revisions.   (An intermediate tracking/merging branch on my local machine works fine until we are both done with the file, when it'll be finally re-merged on atlas/master.)

This isn't a showstopper at all.  In the end, it was no problem, and it's probably only a problem for people who use git directly and are used to seeing the specific changes made by their collaborator within git -- you can also work around this using a non-git diff utility on the two files.

But, on the other hand, it "should" be easy to link the Atlas UI's "rename" button to the "git mv" action, no?  (Yeah, I don't know the details, wherein the devil is.  I know.)

Anyway, now there's two bug reports for this issue.  :)

**Comment by runemadsen** [comment]
Hi @hexagon5un. Thanks so much for this. I'm aware of this, and it will be changed in the next version of Atlas. I'll close this issue as soon as it's deployed.

:+1:
