### ISSUE TITLE
Can't clone repo for 1234000001660

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#262]
Hi,

I'm trying to check out https://bjepson%40gmail.com@atlas-server.oreilly.com/git/1234000001660.git, but when I do, it fails partway through receiving objects with:

fatal: The remote end hung up unexpectedly 
fatal: early EOF
fatal: index-pack failed

I have my http postbuffer set, though, so that's not the problem.

Thanks,

Brian

**Comment by ptwobrussell** [comment]
I have not been able to git push to one of my repositories for several hours now. Is it possible that the git server is hung up or down?

**Comment by sandersk** [comment]
Hi @ptwobrussell,

We've had some ongoing issues with the Git server today, and are currently troubleshooting the issues. We will let you know as soon as things are resolved.

Thanks for your patience,
Sanders

**Comment by sandersk** [comment]
Hi @ptwobrussell,

The Git server is back up and running now, so you should be able to push again. Let us know if you encounter any further issues.

Thanks,
Sanders
