### ISSUE TITLE
How to specify sort for sub-entries in an index?

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#263]
Does the sortas="" attribute apply to the primary entry or the secondary entry? I'd like to have something like this:

```
((("return values", "with case construct", sortas="case")))
```

Will this sort the primary entry as "case" or the secondary entry, which is what I really want.

**Comment by sandersk** [comment]
Hi David,

The sortas applies to the secondary entry here, so you should get the desired result. 

More generally, the sortas applies to the lowest-level entry in the list. So if there's a primary and secondary, it applies to the secondary entry, and if there's a primary, secondary, and tertiary, it applies to the tertiary entry.

Let me know if you have any further questions or run into any problems.

Thanks,
Sanders

**Comment by sandersk** [comment]
Closing this ticket, as I'm assuming I've answered your question here, David. Please reopen if you have further questions or run into any difficulties.

Thanks,
Sanders
