### ISSUE TITLE
Book Won't Build

### ISSUE THREAD

**Issue by MikeW50** [MakerPress/atlas-public-feedback#267]
HI folks,

My book suddenly stopped building in PDF format yesterday, even though it would build in HTML. I forged ahead, building pieces to keep working. Now I can't build two paragraphs. The book is Building iPhone and iPad Electronics Projects.

The error messages were less than helpful. The first ones seem to indicate a problem with indexing where none existed before. Removing Chapter 6 fixed the problem. Building Chapter 6 by itself worked, though. And Chapter 6 had not been changed since earlier, successful builds.

The error messages got less and less meaningful, culminating in:

---

PDFJob
Failed at 2013-06-11 18:18:41 UTC

Job failed
Full error:

---

That's the full text of the error.

Then things started, perhaps, to make sense, when I got this error:

---

PDFJob
Failed at 2013-06-11 18:20:07 UTC

Job failed
Full error:

No space left on device - /tmp/systemu_atlas-worker_26715_26718_0.8426147836788951_1

---

So, what incantation do I need to get back on track?

Thanks!

**Comment by adamwitwer** [comment]
Hi @MikeW50. Sorry about that. I believe we've fixed it. Please give it a try.

Adam

**Comment by MikeW50** [comment]
Thanks, Adam. It's working fine, now.
