### ISSUE TITLE
Code Snippets Never put the code into a book

### ISSUE THREAD

**Issue by RichardWarburton** [MakerPress/atlas-public-feedback#268]
Following the factorial code snippet example in http://ano-chimera.herokuapp.com/books/1230000000065/ch04.html#code_explanation doesn't seem to result in the code snippet actually being included, only the text mentioned in the description.

**Comment by sandersk** [comment]
Hi @RichardWarburton,

Sorry about that. There was originally a typo in the documentation at http://ano-chimera.herokuapp.com/books/1230000000065/ch04.html#code_explanation that I had just recently corrected. The attribute line above the snippet macro should use "identifier" for specifying the identifier, not "identifer". This is the correct syntax:

```
[filename="factorial.js", language="java", identifier="FACTORIAL_FUNC"]
snippet~~~~
Put any descriptive text you want here. It will be replaced with the
specified code snippet when you build ebook outputs
snippet~~~~
```

I corrected the typo in your book, rebuilt the PDF, and confirmed the code was inserted as expected. Please let me know if you encounter any further issues as you insert additional snippets.

Thanks,
Sanders

**Comment by RichardWarburton** [comment]
Oh - fantastic, and thanks for your quick reply.  The other thing I noticed was the source zip that is linked to at the top of that document doesn't actually use the code snippet to implement its code snippet.  It just uses an inline [source,js] block.  Its probably worth publishing a new one, so people can see a real example of it in use.
