### ISSUE TITLE
Offline authoring?

### ISSUE THREAD

**Issue by ptwobrussell** [MakerPress/atlas-public-feedback#269]
Are there any plans that would allow you to do any offline authoring? Haven't looked at the latest tech for this lately, but I'm thinking something along the lines of how Google Gears used to enable offline storage. I think HTML5 has a pretty robust spec for local storage that could be worth checking out to enable something like this

Or perhaps this a ridiculous request given that I could just as easily author in AsciiDoc in a notepad and just copy/paste it back into Atlas when I get back online? Anyhow, just curious if this had come up or been discussed.

**Comment by jdeisenberg** [comment]
You don't have to copy and paste back into Atlas; if you clone the github repository, you can make your changes locally (using something better than Notepad, I hope; I like Geany and jEdit). You can then push the changes to the repository when you get re-connected, and they will appear in Atlas the next time you log in. See http://chimera.labs.oreilly.com/books/1230000000065/ch02.html#working_locally for details.

**Comment by ptwobrussell** [comment]
Oh, right. I've done very little work with AsciiDoc and was probably just over-thinking this. I currently work with DocBook and use Git to push my changes back, so I understand how all that works. I guess my question could have better been asked this way: are there any plans for a great AsciiDoc authoring experience via Atlas when you are offline? But now as I think about it more, I understand that the way to go would be to take advantage of an existing client that has good syntax highlighting for authoring AsciiDoc,which makes total sense.
