### ISSUE TITLE
Exclude "Updated book.asciidoc" from Changes tab?

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#27]
I see that when you do a Build in Atlas, that gets reflected on the Changes tab with a message like:

"Updated book.asciidoc"

Wondering if we want to exclude changes to book.asciidoc from the Changes tab? They're not especially informative to Atlas users, and they clutter the change listing a bit and take up some valuable space.

**Comment by runemadsen** [comment]
Ah, yes. I might have added this back in, because it used to be ignored.
This is something that - when we start to write them eventually - should be
caught in automated tests.

On Thu, Jul 5, 2012 at 3:13 PM, Sanders Kleinfeld <
reply@reply.github.com

**Comment by runemadsen** [comment]
This has been fixed in the sense that we have much less of these commits now. Only actual changes to book.asciidoc will be commited now. No more empty commits.
