### ISSUE TITLE
Is there any way to trigger a build automatically, and/or an API for retrieving past builds?

### ISSUE THREAD

**Issue by levand** [MakerPress/atlas-public-feedback#271]
We have an author website where we want to provide a download link to the most up-to-date version of the book.

Is there any way to automatically trigger a build of the book (either periodically or whenever a commit is pushed)?

And, once it's built, is there any way to automatically retrieve a link to the HTML or PDF file?

I can do this by writing a web scraper that loads the website itself but it'd be much easier if there were built in commit hooks or an API.

**Comment by runemadsen** [comment]
Hi @levand. Right now this is not possible, but we're finishing up the next major release of Atlas, where this is a central feature. We will be updating these issues as we resolve them, but unfortunately I don't have a specific timeframe (in weeks, not months) right now. Stay put!

**Comment by sandersk** [comment]
This ticket duplicates the feature request in #284, so I'm going to resolve.
