### ISSUE TITLE
Low contrast in Chimera listings

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#274]
The color contrast for the listing at http://chimera.labs.oreilly.com/books/1234000000446/ch01.html#svgess-CHP-1-SECT-4.2 is extremely low; the comments are nearly invisible on my monitor, and the white on gray isn't the best contrast either.

The analyzer at http://snook.ca/technical/colour_contrast/colour.html shows that the contrast for the element and attribute names are good enough at their brightest pixels, but the anti-aliased pixels are just "sort of" compatible.

**Comment by sandersk** [comment]
Hi @jdeisenberg,

Sorry for the delayed response on this ticket. We're definitely planning on reviewing our color scheme for syntax highlighting on Chimera, as we've gotten feedback from others regarding the same contrast issues. Will keep you posted on any changes we make here.

Best,
Sanders
