### ISSUE TITLE
Only 2 of 9 chapters building

### ISSUE THREAD

**Issue by andyoram** [MakerPress/atlas-public-feedback#275]
This problem appears with the Zookeeper book, project 1234000000170. I listed 9 files to build, and only chapters 1 and 3 appear in the PDF.

**Comment by adamwitwer** [comment]
Hey @andyoram. I tried building again and got all nine chapters. Please see the latest PDF, which you can download from the project dashboard. I'm not sure what happened in the previous build. Please let us know if it comes up again.

**Comment by andyoram** [comment]
Thanks. I'll let you know if the problem re-occurs. 

Andy 

----- Original Message -----
