### ISSUE TITLE
console.log functionality not working with JS Bin insert

### ISSUE THREAD

**Issue by shelleyp** [MakerPress/atlas-public-feedback#276]
I'm attempting to demonstrate differences between JS literals and objects, and am using the console.log as a way of printing out some values for examination. 

The JS Bin application works fine in JS Bin, but the console.log printouts never work when the example is embedded in Atlas. 

JS Bin example 

http://jsbin.com/ayinob/1/edit

Example location (though this will change based on current build and depending on when someone will look at this). 

http://chimera.labs.oreilly.com/books/1234000001681/ch01.html#introduction-id00001

And I believe it's related to

https://github.com/remy/jsbin/issues/582

**Comment by runemadsen** [comment]
Hi @shelleyp 

Do you mean that the console.log's are not showing up in the web inspector, or not showing up in the JSBin console? The latter should work if you enable the console column in the embed. The first won't work as it's embedded as an iframe.

Let me know and we can try to solve it together.
- rune

**Comment by shelleyp** [comment]
Hi Rune, I'm using this as an embed in an Atlas book, with the console panel displayed. The console.log message is not displayed when you click the run button in the console panel of the embedded JS Bin app. The built book demonstrates, but just realized the book is not available for everyone to view.

Hopefully this info will be sufficient without a working example.

**Comment by sandersk** [comment]
Hi @shelleyp,

Yes, I can see what you're talking about from the example in Chimera. Actually, when I load the Chimera page in Chrome for Mac, pop open the Chrome JavaScript console, and click "Run", I do see the "string" and "object" lines output to the Chrome console, even if they don't show up in the Console panel in the JS Bin.

I suspect that having the JSBIn in an iframe is interfering with the ability to route the console logging properly, as suggested in the ticket you referenced. We've got an ongoing thread with Remy on future JS Bin development, so I'll ping him about this and ask him if he can advise.

Thanks,
Sanders

**Comment by remy** [comment]
Fixed in jsbin with https://github.com/remy/jsbin/pull/649 and going live shortly.

**Comment by shelleyp** [comment]
Thanks for the update! Just checked and all is well!

**Comment by sandersk** [comment]
Super! Thanks so much, @remy
