### ISSUE TITLE
Autosave?

### ISSUE THREAD

**Issue by katehartman** [MakerPress/atlas-public-feedback#28]
Is it possible to add autosave? This would be particularly helpful when moving between Editor and HTML View. Changes get lost if you don't remember to hit "save" before changing views.

**Comment by mikehatora** [comment]
Please make this an option.  I would not want the change log to grow unwieldy because of someone autosaving all the time in a multi-author project.

**Comment by katehartman** [comment]
Then perhaps a more helpful approach would be a warning that you will lose your changes when you try to switch views or files without saving...

**Comment by bjepson** [comment]
Yes, I've had authors ask for this as well.

**Comment by courtneynash** [comment]
Ditto. Had one author lose a bunch of work recently. Ugh.

**Comment by sandersk** [comment]
Hi all,

Earlier this week, we implemented a new feature in Atlas that will warn you if you close the editor window or switch to HTML view with unsaved changes in your document. We hope this will prevent users from losing work unintentionally.

Sanders

**Comment by courtneynash** [comment]
Sweet! Thanks Sanders.
