### ISSUE TITLE
RefWorks

### ISSUE THREAD

**Issue by interested1** [MakerPress/atlas-public-feedback#281]
I would love to have you implement something akin to RefWorks to chronicle sources.  I know that most of the books we write on the platform do not demand citation; however, if this is to rollout as a publishing tool it seems to me vital to have some sort of citation management tool.  Moreover, I know that having a way that transcends comments on the document to express the sources used as departure points for content development would help collaborators and editors --it also would remind author's where the genesis of the idea came from.  This could be a great data set to document not only during the initial book production, but also for edition revisions and any future collaboration.

Again, this isn't an essential issue, but I think it is something to consider as you expand the user-base and project into the future the technology.
Thanks!
David

**Comment by sandersk** [comment]
Hi @interested1,

Thanks for the suggestion to add a more comprehensive bibliographic management system to Atlas. That's not something we currently have on our short-term roadmap, but longer term, we will certainly consider more robust support for bibliographies/citations. 

We do plan to roll out some substantial enhancements to our commenting system over the next few months, so stay tuned for that, and keep the feedback coming!

Best,
Sanders

**Comment by interested1** [comment]
Hi @sandersk,
  Totally understandable why it's not on the short-term roadmap.  Just thought I would put it out there that with robust bibliographic and citation support you can market this to researchers and academics alike!
Later,
David
