### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by interested1** [MakerPress/atlas-public-feedback#283]
I can log into http://atlas.labs.oreilly.com/ without issue; however I cannot login to http://ano-chimera.herokuapp.com/ with the same credentials.  I believe I accidentally tried to login with Google's openid once and I think that's caused a bit of chaos.

When I try the username and password that works on http://atlas.labs.oreilly.com/ on http://ano-chimera.herokuapp.com/ I do not gain access.  When I now try the google login for the same page I get the error:

"The token URL or xdReceiver has not been whitelisted
switch accounts"

Also, when I attempt to reset my password the form returns that I am a social account authentication user.  Did I confuse the login system?  I know I confused myself...

Thanks for any help or suggestions you can provide.

**Comment by runemadsen** [comment]
Hi @interested1 

First of all, you need to use the following link to log into the reader:
http://chimera.labs.oreilly.com/

Where did you find the old ano-chimera link?

You login will not automatically bubble into the reader. You will need to create a user with the same email as you have in the writing environment. We are working on making this a better experience, but that's how it is for now. If your email is a google email, then you can use the social login button.

If this fixes #280, let me know.
