### ISSUE TITLE
Best practices for outputting information using console.log with JS Bin inserts 

### ISSUE THREAD

**Issue by shelleyp** [MakerPress/atlas-public-feedback#286]
I have a significant number of JS Bin inserts in my JS Cookbook excerpt book. Many require some form of output to test results. 

I've used alert in the past because it's supported by all browsers. This will _not_ work with the JS Bin inserts, not the least of which, all the active inserted code throughout the book. 

Console.log works with Firefox and Chrome, but does not work with Opera and IE-- at least not in the JS Bin context. 

It's a real pain to have to use the DOM just to output a message. 

What is the best practice in these circumstances?

**Comment by sandersk** [comment]
Hi @shelleyp,

Are you sure you can't use "alert" statements to display messages to the user? I just tested using "alert" in a simple JS Bin, and it worked fine for me when embedded in a Chimera page:

http://jsbin.com/uvogad/1/

If "alert" isn't working for you, could you point me to an example that has the problem? If we can get "alert" working, I agree that would probably be the most straightforward way to handle logging output.

Thanks,
Sanders

**Comment by shelleyp** [comment]
No, can't really use alert in the dozens or so of automatically loaded JS
Bin inserts.

In addition, the JS community has really frowned on using alerts for a long
time now. That's the whole reason for using console.log.

I'll see about adding a bug in JS Bin. Or we'll just assume only Chrome or
Firefox people can run the examples.

Thanks.

Shelley
