### ISSUE TITLE
Suggestion: A unified timeline for all actions on book in dashboard

### ISSUE THREAD

**Issue by mrichardson23** [MakerPress/atlas-public-feedback#288]
I think it would be nice to have a unified timeline on a book that shows commits, builds, and other changes to the metadata. I often look at the changes and the builds and wonder if a build includes the latest changes. It might be nice to see this info together, along with other changes.

Perhaps under "Dashboard," a section that says "Latest Actions", with content such as:
A new build is ready(link) (1 hour ago)
Matt started a new build(link) (1 hour ago)
Matt pushed 3 commits(link) (2 hours ago) 
Brian pushed 1 commit(link) (4 hours ago)
Matt added new contributors (5 hours ago)

**Comment by sandersk** [comment]
Hi @mrichardson23,

Thanks for the excellent suggestion. We're currently working on some updates to the entire editing interface, and we'll look into a more unified approach to the timeline that consolidates build, commit, and other info into one place.

Sanders
