### ISSUE TITLE
No stats generated for my project since January

### ISSUE THREAD

**Issue by happi** [MakerPress/atlas-public-feedback#289]
Since January the stats page of my project has not been updated 
(other than the "Stats Generated:" field)

http://ano-atlas2.herokuapp.com/books/1234000000902/stats

**Comment by runemadsen** [comment]
Hi @happi 

Yes, we're having a few problems with the stats generation. We are working very hard on launching a new, improved, and highly polished version of the writing interface, so I'm hoping you will stay tuned for that.
- rune
