### ISSUE TITLE
Changes in text sometimes fail to display correctly

### ISSUE THREAD

**Issue by hexagon5un** [MakerPress/atlas-public-feedback#290]
I work from home, and periodically push my changes up to the git repo.  A lot of the time, the diff-highlighting on the "Changes" page works just fine.  Sometimes, though, the changes are displayed only as the raw diffs which are not _at all_ easily readable to humans and frustrating to my editor.

None of the change sets prior to the broken one (that is, lower than the first broken commit on the page) render right either.  

This makes me think that something is going wrong with the diff parsing in the diff-to-colored-nicely-presentable-changes web code. (But I'm just guessing.)

This is a fairly critical flaw for our workflow, because if he's already worked through a chapter and I've just made some modifications, he really doesn't want to have to re-read the whole chapter again.

**Comment by sandersk** [comment]
Hi @hexagon5un,

Is this the project that has the diff problems to which you're referring:

http://atlas.labs.oreilly.com/books/1230000000769/

Could you point us to a location on the Changes tab where you're seeing raw diffs instead of the usual red-and-green highlighting? I scrolled through, and I'm not seeing the problem at first look.

Thanks, and sorry for any inconvenience this issue has caused you,
Sanders

**Comment by hexagon5un** [comment]
Sorry, I've been pushing up work to it, so the failure is way down the screen.

Search for "disentangle" in the comments and you'll see it.   I also took a screeny, but I'm sure that the code is more useful for you. 

It's also git commit 1f810cb.

**Comment by sandersk** [comment]
Ah, yes. I see it now. I've attached a screenshot to this ticket, as I think yours didn't come through.

It does indeed appear to be a bug with the diff highlighter. We'll take a look at this issue. While we investigate, I'd suggest either searching for + signs on the changes tab and/or cloning down the Git repo and doing diffs on the command line (let me know if you need guidance on that) to ensure you catch all changes.

Thanks,
Sanders

![screen shot 2013-07-27 at 8 30 22 pm](https://f.cloud.github.com/assets/703865/867657/e775630a-f71d-11e2-98f3-6d3b263bd257.png)

**Comment by hexagon5un** [comment]
That screenshot you added looks fine to me.  The problem I was describing was where a (huge) text block had absolutely _no_ markup coloring at all.  I'm going to try to attach a screeny again.

![atlas_buggy_changes](https://f.cloud.github.com/assets/1560700/892558/c728302a-fa86-11e2-943b-2e1bd1519694.png)

(Haha!  Success.)

**Comment by sandersk** [comment]
Ah, yes, got the screenshot this time @hexagon5un. We'll take a look at what's going on with the section in question.
