### ISSUE TITLE
Moving the Makerspace Workbench to github?

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#293]
Hi,

I'm trying to look into a problem with the oneoff for @jlhosman, but I get "The remote end hung up unexpectedly" when I try to pull. Would it make sense to move this over to github or is there another workaround? The book is at http://ano-atlas2.herokuapp.com/books/1230000000789

We should wait until @jlhosman gets back to us to do anything because she's actively working in the repo.
- Brian

**Comment by jhosman** [comment]
Hi @bjepson, looks the repo got pretty huge once we added the processed images back in. I ended up having to move it over to github here:

https://github.com/oreillymedia/Makerspace_Workbench
