### ISSUE TITLE
Builds do not seem to be finishing

### ISSUE THREAD

**Issue by jhodgdon-drp** [MakerPress/atlas-public-feedback#294]
The last time I tried to do a build on my book, 4 days ago, it finished in a few minutes (it's about a 120 page book at this point, and I am building just PDF version).

Today I started a build 15 minutes ago and it is still working. I am not sure if the build is ever going to finish, or if there is something wrong in one of my files that would cause it to never finish, or what? I haven't made all that many changes since 4 days ago... and normally if there is a problem with a build, I get an error message. ???

I also launched a second build... Now I have one that is 7 minutes old and one that is 18 minutes old, and neither one shows any sign of finishing.

**Comment by jhodgdon-drp** [comment]
They are up to 30/40 minutes now, still no sign of finishing.

**Comment by jhosman** [comment]
Just to add to this, it looks like the Java Web Services (1234000000910) PDF build is also hanging, as well as some others that have gotten stuck in the queue. 

@jhdrupal, someone from the development team will take a look at this as soon as they get in this morning.

**Comment by runemadsen** [comment]
Thanks @jhdrupal. I fixed a small bug, and it's going now. There's a book that is killing the server, so give it 5 minutes, and we should be back. Sorry for the inconvenience. We'll launch a new server setup very soon, which should be much faster and more stable.

**Comment by jhodgdon-drp** [comment]
This appears to be fixed. Thanks!
