### ISSUE TITLE
Suggested Feature: mobi push to kindle e-mail

### ISSUE THREAD

**Issue by interested1** [MakerPress/atlas-public-feedback#295]
It would be great if in atlas you could build and, once built, have atlas configured to push the built mobi directly to an associated e-mail address for a kindle.

I have gotten in the habit of proofing my work on my kindle and making changes on my laptop.  Having the two different interfaces with the text is really helpful for me to catch errors and omissions I would otherwise miss.  

The workflow right now isn't too burdensome, but could be streamlined within atlas.  Not sure if it is a good idea for everyone or not, but I know I would use it :-D

Thanks for reading!
David

**Comment by sandersk** [comment]
Hi @interested1,

Thanks for the suggestion to set up a "send to Kindle" for Mobi files in Atlas. We currently have this functionality in place for ebooks purchased on oreilly.com, and I can see it being equally valuable for Atlas users as they're working on their books, so we'll look into implementing this in a future Atlas release.

Thanks,
Sanders

**Comment by interested1** [comment]
Great!  Thanks Sanders.

**Comment by zaremba** [comment]
added to feature backlog
