### ISSUE TITLE
"forgot password" link claims my email address is not registered

### ISSUE THREAD

**Issue by michaelshiloh** [MakerPress/atlas-public-feedback#296]
I forgot my password, so I clicked on the "forgot password" link and entered my email address for password reset instructions.

I receive "1 error prohibited this user from being saved:

```
Email not found
```

I have tried this with all possible email addresses with the same results.

Any suggestions?

Thanks,
Michael

**Comment by adamwitwer** [comment]
Hi @michaelshiloh. It's possible you were looking at the Forgot Password form on the reader site (rather than the authoring site). I do see your email address in the system. Can you please try entering it here?

http://atlas.labs.oreilly.com/users/password/new

**Comment by michaelshiloh** [comment]
I'll bet that's exactly what happened. Thanks!

Meanwhile, Brian invited me with a different email address, and I'm all 
set up, so this issue is no longer an issue.

Thanks again,
Michael

**Comment by adamwitwer** [comment]
Great, thanks. Glad you figured it out!
