### ISSUE TITLE
Remove Yourself from a Book? You'll get a Page Not Found

### ISSUE THREAD

**Issue by tobrien** [MakerPress/atlas-public-feedback#297]
Hello there.

If you remove yourself from a book (not a common task, no? But something I recently did)... if you do this, you'll experience a 404 error with a link to the issue list.

**Comment by zaremba** [comment]
Hi @tobrien, yes, if you remove yourself from a book, a link to that book will generate a 404 error. This is expected behavior for accessing a link without permission.
