### ISSUE TITLE
Renaming sections from a converted book?

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#299]
Not a bug, just need some advice. I'm working on a book which was converted from Docbook to asciidoc, and it gives me references like <<svgess-CHP-3-SECT-2.3>> and <<svgess-CHP-3-EX-3>>. Do you recommend renaming them to things like <<stroke-opacity-section>> and <<stroke-opacity-example>>? The names would be more meaningful, and wouldn't have an inherent order, which would make editing and moving sections around a bit easier.

**Comment by sandersk** [comment]
Hi @jdeisenberg,

Totally your call. If you find that giving the ids/XREFs more meaningful unique identifiers would make it easier for you to update and maintain the text, I'd recommend going ahead and doing that. But if you feel that would just be extraneous effort, I'd advise leaving them as is. From a Production standpoint, either way works for us.

Hope this helps,
Sanders
