### ISSUE TITLE
Broken Build; help debugging?

### ISSUE THREAD

**Issue by ALRubinger** [MakerPress/atlas-public-feedback#300]
Hi guys:

Could you help out?

http://ano-atlas2.herokuapp.com/books/122/jobs/36214

Thanks!

**Comment by adamwitwer** [comment]
Hi @ALRubinger. The book is building again. The problem was related to the empty `[source]` in lines 783 and 796 of Chapter 8. I changed those lines to `[source,xml]` and that solved the problem. Please feel free to reopen this issue if you have any other trouble.
