### ISSUE TITLE
Spelling and Grammar Check

### ISSUE THREAD

**Issue by tmarrs** [MakerPress/atlas-public-feedback#302]
Could you please add a Spelling and Grammar Check?

**Comment by sandersk** [comment]
Hi @tmarrs,

We will be adding a spell check to the next version of Atlas, which we're slating to release in closed beta for O'Reilly authors later this year. We don't yet have a grammar check on our feature list, but i'll pass along that request to the rest of the development team so we can look into it.

Best,
Sanders
