### ISSUE TITLE
Collaboration problem

### ISSUE THREAD

**Issue by suehle** [MakerPress/atlas-public-feedback#304]
We have two authors working in one book. While chasing down build errors, we realized we'd done the same thing at the same time and wondered how Atlas would handle that. 

We went into the same section of the book and each added text on the same line. When we each saved, went out, and came back to that section, only person2's text was there. According to the change log, person2's text overwrote person1's text as if it had been deleted, without person2 ever having seen it. 

While it's /unlikely/ we'd be working on the same line at the same time unintentionally, this seems like the potential for a problem. It would be nice if Atlas at least told you when another collaborator was working on a section you had opened.

**Comment by sandersk** [comment]
Hi @suehle,

Thanks for reporting this issue. You're correct that if two people are working on the same text in the same file in the Atlas Web interface at the same time, the person who saves last will overwrite the work of the other person.

We're working on providing improved collaboration tools for the next release of Atlas, and implementing a solution for the problem you describe is in our development queue. We hope to have this functionality available in early 2014, and will keep authors posted.

Thanks again for your feedback, and do let us know if you encounter any other issues or have further questions.

Best,
Sanders

**Comment by aplimpton** [comment]
It is early 2014 and we are having the same issue. Is there an set release date for the solution? It's very frustrating to have a collaboration tool that does not allow collaboration.

**Comment by sandersk** [comment]
Hi @aplimpton,

Sorry that you are finding collaboration frustrating. We are very actively working on a full suite of enhancements to facilitate collaboration in the Atlas Web interface, and intend to have them in place later this year.

But in the meantime, we certainly want to help meet your collaboration needs as best we can. Atlas uses Git to manage project files, which means that there is a powerful distributed version-control system built into the platform. So while the UI doesn't yet have a full collaboration interface built in, it's still quite possible for collaborators to check out files locally via Git, create branches for their work, merge changes as needed, etc.

If you'd like to provide more details here or to your editor, we'd be happy to further discuss with you how we can help get a workflow in place that works for you and your collaborators.

Thanks,
Sanders

**Comment by aplimpton** [comment]
Hi Sanders!

Looks like you ended up with all my comments. There are several people working different parts of the book. Several are using Git and a couple aren't. The biggest problem is that there is no warning in the documentation (http://chimera.labs.oreilly.com/books/1230000000065/index.html) or on the screen that we will be stepping all over each other. This was especially disconcerting because the guide talks about using Git which actively avoids that behavior. We've had to revert to older commits and lose some work as well as start emailing each other which chapters we are in and explicitly say when its safe for the others to go in. Any suggestions  to improve the workflow are welcome. 

Thanks for all you help :)

**Comment by sandersk** [comment]
Hi @aplimpton,

Yes, again, sorry you've encountered difficulties here. I've added a note to the documentation warning users about the potential to overwrite each other's content when working on the same file simultaneously in the Web editor.

Your policy of coordinating with each other via email is a good way to avoid potential conflicts. I might also suggest that only one person work in the Web editor at any given time, and have everyone else work on a local clone of the Git repo. These people would commit their changes locally, and then do a "git push" up to Atlas, which would give them a heads-up if there were any changes from others that needed to be merged in. More details on working locally can be found here: http://chimera.labs.oreilly.com/books/1230000000065/ch02.html#working_locally

Again, apologies for the inconvenience here. Building out the collaboration features is one of our top priorities for Atlas, and we are currently hard at work on it :smile: 

Let us know if there's anything further we can help with.
Sanders
