### ISSUE TITLE
PDF build failed with "unexpected error"

### ISSUE THREAD

**Issue by ramalho** [MakerPress/atlas-public-feedback#305]
When trying to build a PDF with one chapter, Being-Pythonic.asciidoc, the build failed with an unhelpful "unexpected error" message. 

The state of the input file is recorded in commit ea4b73a937a3e98919d854f808cbac4d8f680a1e at the repo atlas-server.oreilly.com/git/1234000001884.git

The error page with traceback was:

```
PDFJob
Failed at 2013-09-12 12:26:56 UTC

Job failed
Full error:

asciidoc: WARNING: book.asciidoc: line 3: {include:/usr/local/app/worker/tmp/pdf/1234000001884/book-docinfo.xml}: file does not exist
asciidoc: FAILED: Being-Pythonic.asciidoc: line 193: unexpected error:
asciidoc: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/asciidoc", line 5672, in asciidoc
    document.translate(has_header) # Generate the output.
  File "/usr/local/bin/asciidoc", line 1554, in translate
    Section.translate()
  File "/usr/local/bin/asciidoc", line 2195, in translate
    Section.translate_body()
  File "/usr/local/bin/asciidoc", line 2203, in translate_body
    next.translate()
  File "/usr/local/bin/asciidoc", line 2575, in translate
    self.merge_attributes(attrs)
  File "/usr/local/bin/asciidoc", line 2482, in merge_attributes
    if not is_name(style):
  File "/usr/local/bin/asciidoc", line 482, in is_name
    return re.match(r'^'+NAME_RE+r'$',s) is not None
  File "/usr/lib/python2.6/re.py", line 137, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
asciidoc: ------------------------------------------------------------
```

**Comment by jhosman** [comment]
Hi @ramalho,

You're right, that is a very unhelpful error message! I took a look at the Being-Pythonic.asciidoc file, and it seems that the error actually cascaded down from an earlier code block that didn't have the final 4 hyphens below it to close it out. I went ahead and added in the 4 hyphens for you (to the code block beginning on line 110 of that file) and tested the PDF build. Everything seems to be functioning properly now.

While I was in there, I noticed that your book project was set up in Atlas to use the default basic template instead of the O'Reilly template. I went ahead and switched it over for you, so you should now see the syntax highlighting colors in the rendered PDF. Enjoy!

Thanks!
Jessica

**Comment by ramalho** [comment]
Thanks a lot, Jessica!

Cheers,

Luciano

On Thu, Sep 12, 2013 at 11:59 AM, jlhosman notifications@github.com wrote:

> Hi @ramalho https://github.com/ramalho,
> 
> You're right, that is a very unhelpful error message! I took a look at the
> Being-Pythonic.asciidoc file, and it seems that the error actually cascaded
> down from an earlier code block that didn't have the final 4 hyphens below
> it to close it out. I went ahead and added in the 4 hyphens for you (to the
> code block beginning on line 110 of that file) and tested the PDF build.
> Everything seems to be functioning properly now.
> 
> While I was in there, I noticed that your book project was set up in Atlas
> to use the default basic template instead of the O'Reilly template. I went
> ahead and switched it over for you, so you should now see the syntax
> highlighting colors in the rendered PDF. Enjoy!
> 
> Thanks!
> Jessica
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MakerPress/atlas-public-feedback/issues/305#issuecomment-24327342
> .

## 

Luciano Ramalho / OFICINAS TURING
Twitter: @ramalhoorg

Autor e professor dos cursos:
- Objetos Pythonicos   -->   http://turing.com.br/oopy
- Python para quem sabe Python   -->   http://turing.com.br/ppqsp
