### ISSUE TITLE
Code font in PDF is very weird

### ISSUE THREAD

**Issue by jhodgdon-drp** [MakerPress/atlas-public-feedback#307]
I wrote a book last year using Atlas/asciidoc and am returning to it this year to make some updates.

I have noticed that the font used for code segments, as well as for text enclosed in + in paragraphs (in asciidoc) is very odd and hard to read, compared to what it was last year. The letters in this font are all different heights and they do not read easily (seem to have blank spaces in them -- they don't show up well). I think the old simple monospace font that used to be used was better.

As an example, here is a screen shot from the published PDF (old version) of my book:
![goodfont](https://f.cloud.github.com/assets/2294278/1141984/3b5912b4-1cc1-11e3-9b2c-1c259ef89cdc.png)

And here is the same spot in the new version from a recent build:
![badfonts1](https://f.cloud.github.com/assets/2294278/1142012/a5229d96-1cc1-11e3-8d95-6c46e3a404f1.png)

Just for completeness, here is the source text for this section (from the new version; the old one was similar):

The Drupal 7 cache system has a fairly simple API, consisting of functions +cache_set()+ and +cache_get()+ (with a few variations), as well as +cache_clear_all()+ and +drupal_flush_all_caches()+ to clear cache
information. Modules can register to have their caches cleared by implementing a _hook_ (hooks are module entry points to altering Drupal) called
+hook_flush_caches()+.

It gets even worse when you have a code listing (this is from the new version):

![badfonts2](https://f.cloud.github.com/assets/2294278/1141992/74fb6b7a-1cc1-11e3-8dbb-ae9fcc4860ce.png)

I'm using the Adobe reader version 9 on Ubuntu, if that makes a difference... but the same reader for both old and new versions. The old one is a much more readable font. Can you change it back?

**Comment by jhodgdon-drp** [comment]
"theme functions" comes out looking like tHeMe FUNcTIoNS (the size of the letters is all wonky). Really annoying. Hard to read.

**Comment by sandersk** [comment]
Hi @jhdrupal,

That is strange. I took a look at the PDF we released in December 2012, and the latest PDF from Atlas, and confirmed they both use the same code font: UbuntoMono. Here is a screenshot I took of the same syntax-highlighted code listing from the latest Atlas PDF that I took using Adobe Acrobat 8 Professional for Mac:

![drupal_screenshot_syntax_highlighted_code](https://f.cloud.github.com/assets/703865/1149755/3f6790bc-1ee0-11e3-9c5d-77a3a815304a.png)

I don't see the wonky letter sizing, which leads me to believe that this is an issue specific to Adobe Reader for Ubuntu--although I don't know why it would affect only the new PDF and not the old one. I wonder if it was just a fluke. When you get a chance, could you try generating a fresh PDF in Atlas and try opening in Adobe Reader again and see if you have the same problem?

Thanks,
Sanders

**Comment by jdeisenberg** [comment]
It seems to be a Linux vs. Adobe thing; see issue https://github.com/MakerPress/atlas-public-feedback/issues/216 for a problem with Fedora 19.

**Comment by jhodgdon-drp** [comment]
It is not just a fluke. I have been seeing this for a few months on every PDF I generate in Atlas; I just didn't get around to reporting the problem until it had persisted for a while.

Hmmmm... I am now noticing that if I zoom in/out, at some magnifications the font looks OK and at some it doesn't.  And if I look at it in the Ubuntu open-source "Document Reader" application, as opposed to the Adobe Reader application, I am not seeing the problem with the font. So perhaps it is just a problem with Adobe Reader for Ubuntu, this particular font, and magnification.

And I'm still not seeing it in the PDF I downloaded from oreilly.com (the released book), at any magnification, so I'm not sure about your assertion that they are using the same font. How do you check the fonts in a PDF file?

**Comment by sandersk** [comment]
Thanks for the additional feedback, @jhdrupal. That's helpful, and we're going to continue to troubleshoot this further. The font family (UbuntoMono) is definitely the same in both PDFs, but it's possible that there may be some file-format differences we've made in the past year or so that might account for the difference in rendering in Adobe Reader. We'll research further and do our best to pinpoint the issue and fix it.

**Comment by adamwitwer** [comment]
I just adjusted things on the Atlas build server. I'd be curious to know if this problem persists.

**Comment by jhodgdon-drp** [comment]
Whatever you did seems to have fixed the problem for me. Thanks!

I'll close this issue now, and reopen if I see it happening again later.
