### ISSUE TITLE
Can't build book: build failing with "invalid byte sequence in US-ASCII"

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#308]
Hi,

How do I diagnose this error? It doesn't tell me which line in the file is causing the problem. The book is http://ano-atlas2.herokuapp.com/books/1234000001720

/usr/local/app/worker/renderer/pdfrenderer/csspdf:195:in `sub!': invalid byte sequence in US-ASCII (ArgumentError)
    from /usr/local/app/worker/renderer/pdfrenderer/csspdf:195:in`generate_oneoff_css_tmp'
    from /usr/local/app/worker/renderer/pdfrenderer/csspdf:336:in `block (2 levels) in <main>'
    from /usr/local/app/worker/renderer/pdfrenderer/csspdf:201:in`each'
    from /usr/local/app/worker/renderer/pdfrenderer/csspdf:201:in `block in <main>'
    from /usr/local/app/worker/renderer/pdfrenderer/csspdf:199:in`each'
    from /usr/local/app/worker/renderer/pdfrenderer/csspdf:199:in `<main>'

Thanks,

Brian

**Comment by sandersk** [comment]
Hi Brian,

This error is actually coming from the oneoff.css file. The toolchain doesn't currently support putting Unicode characters directly in the CSS, so you should use the corresponding codepoint instead. I went ahead and made the following change:

```

diff --git a/tools/oneoffs/oneoff.css b/tools/oneoffs/oneoff.css
index 4bcc067..11c6a96 100644
--- a/tools/oneoffs/oneoff.css
+++ b/tools/oneoffs/oneoff.css
@@ -138,7 +138,7 @@ p.photography, p.byline, p.compiler, p.testers {
 }

 p.epigraph:before {
-    content: "— ";
+    content: "\2014 ";
 }

 p.epigraph {
```

PDF should successfully build now, but let me know if you encounter any further issues.

Thanks,
Sanders

**Comment by bjepson** [comment]
Thanks! I'll make sure I don't put anything evil in that file again!
