### ISSUE TITLE
Git problem with commitment?

### ISSUE THREAD

**Issue by patrickdijusto** [MakerPress/atlas-public-feedback#309]
I'm trying to commit files to a book, and the push returns with "RPC failed; result=22, HTTP code = 502"

What does this mean?

**Comment by runemadsen** [comment]
Hi @patrickdijusto 

I think this might help:
http://chimera.labs.oreilly.com/books/1230000000065/ch05.html#push_rejected

Let me know if the problem persists.
- Rune

**Comment by patrickdijusto** [comment]
Thank you!

I tried that; in fact, I always do a pull before I push.

In this case, the pull didn't pull anything, because the files hadn't changed. Everything was up-to-date before I did my push.

Then, when I tried to push, I got the error above.

**Comment by MakerPress** [comment]
Hi, Patrick.  Try running this command on your git client:

git config http.postBuffer 524288000

Git restricts the size of the HTTP buffer to 2MB by default. If you have a repo with lots of images, though, you might need a bigger buffer, as described here:"

http://stackoverflow.com/questions/2702731/git-fails-when-pushing-commit-to-github

Andrew

----- Original Message -----

**Comment by patrickdijusto** [comment]
That did it!  Sorry to be any trouble!  Thank you for the help!

**Comment by runemadsen** [comment]
Yes sorry, I meant the box under the "push rejected" section. Glad it helped.
