### ISSUE TITLE
Suggested Feature: title of current book should be visible on all screens

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#310]
Currently the title of the book/project is only visible on the Dashboard screen, not on Write, Changes, Build, Collaborators, Stats, or Admin. For users working on more than one project, this seems pretty important.

This arose for me because I just had to delete a project from atlas and got very paranoid that I was in the correct project.

**Comment by sandersk** [comment]
Thanks, @bandersonoreilly. This is great feedback, and I agree we should have the title visible on all pages related to a project. We're actually working right now on a complete overhaul of the Web interface, so we'll put this on the list of things we should do.
