### ISSUE TITLE
Build error - "Input is not proper UTF-8"

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#311]
I receive an error notification regarding the build of this particular project:

http://ano-atlas2.herokuapp.com/books/344/jobs/39865

The text of the error is:
/usr/local/app/worker/tmp/pdf/1234000000310/book.xml:158: parser error : Input is not proper UTF-8, indicate encoding !

![image](https://f.cloud.github.com/assets/5495683/1237201/92c904f4-29d3-11e3-88a6-4c56210fe064.png)

Anything I can do to fix the encoding here and build the pdf?

Thanks.

**Comment by sarahs** [comment]
Hi Brian. It looks like there were a couple of invisible characters after this line in the preface:

> You can reach Victor at vrasputnis@faratasystems.com.

I couldn't tell what these characters were, but they were causing the problem. After I deleted them, the PDF was able to build.

Thanks,
Sarah

**Comment by bandersonoreilly** [comment]
Working fine now -- thanks!
