### ISSUE TITLE
Build to asciidoc?

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#312]
Might seem a bit silly but it'd be helpful (for me at least) to be able to build to asciidoc so that I've got all the content in one file. Certainly I could string together the individual asciidoc files, but the atlas build functionality is really great for sequencing files. Just putting it out there.

**Comment by sandersk** [comment]
Hi @bandersonoreilly,

Could you give me more context on the use case for which you like to have all the AsciiDoc content consolidated into one file? It would be helpful to know what goals that helps you accomplish as an editor, so we can figure out the best way to support those in Atlas.

Thanks,
Sanders

**Comment by bandersonoreilly** [comment]
I'd find it useful to have the book in a raw format in order to do some text processing, and to be able to display the text in different ways. It's hard to do NLP on the text once it goes to a PDF/epub/mobi build.

A bit of an outlier request I suppose! I think I mostly wanted to see if we had this functionality already.

**Comment by sandersk** [comment]
Ah, thanks for clarifying @bandersonoreilly. We don't have this functionality already, and I don't think it's something we're going to be adding in the near term, as it's not something most users are looking for.

However, if you're looking to experiment with processing AsciiDoc content and outputting it in different ways, you may want to take a look at either asciidoc.py:

http://www.methods.co.nz/asciidoc/INSTALL.html

Or its Ruby counterpart, AsciiDoctor:

http://asciidoctor.org/

Which are open source tools that can process AsciiDoc content and output in a variety of different output formats. These might be helpful to you in parsing the book content.

**Comment by bandersonoreilly** [comment]
Thanks -- I'll look into those.
