### ISSUE TITLE
"file does not exist" error

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#314]
One of our authors is unable to make a build.

http://ano-atlas2.herokuapp.com/books/1230000000245/builds

Here's the error:

asciidoc: WARNING: book.asciidoc: line 1: {include:/usr/local/app/worker/tmp/pdf/1230000000245/book-docinfo.xml}: file does not exist
asciidoc: ERROR: Basics.asciidoc: line 440: [blockdef-listing] missing closing delimiter

**Comment by adamwitwer** [comment]
I'm looking at this now @bandersonoreilly.

One thing I noticed right away is that AsciiDoc works better when you include a blank line between blocks. When you close off a code listing, for example, it's best to include a blank line before starting the next paragraph.

I cleaned up Basics.asciidoc, but it didn't fix the problem. So I'm still looking. But the blank line between blocks is good practice regardless.

**Comment by adamwitwer** [comment]
Ah, with an assist from @sarahs, we find that this is the problem:

```
[source, text]
----
id  Title       Director            Synopsis
------------------------------------------------------------
1   Top Gun     Tony Scott          Maverick is a hot pilot..
2   Jaws        Steven Speilberg    A tale of a white shark!
----
```

AsciiDoc is interpreting the blank line as the close of the block. Normally, you could escape the line using [this method](http://www.methods.co.nz/asciidoc/faq.html#_how_can_i_include_lines_of_dashes_inside_a_listing_block) but you'll lose the `[source, text]` in that case. But that may be fine for this example? If you want to keep the highlighting, you'll need to use a [passthrough block](http://www.methods.co.nz/asciidoc/userguide.html#X76).

**Comment by sarahs** [comment]
Hi @bandersonoreilly, there may also be a markup issue in Fundamentals.asciidoc that throws an error:

```
[sidenote]
As we are modifying the POJO to fit in the annotations, is it "plain" Java object any more? There are two schools 
of arguers on both sides. May be we should call them as _Annotated Java Object(AJO)_ s!
[/sidenote]
```

This should probably be a [note](http://chimera.labs.oreilly.com/books/1230000000065/ch04.html#Admonitions), since Atlas doesn't support sidenote markup.

**Comment by bandersonoreilly** [comment]
OK -- fixed! It was two issues.
1. I turned [sidenote] syntax to our note syntax.
2. I used the "listing" format to escape the line. It looks fine now.

Thank you!
