### ISSUE TITLE
Commenters in Atlas with odd names

### ISSUE THREAD

**Issue by sarahs** [MakerPress/atlas-public-feedback#315]
Passing along a question from Courtney Nash sent to RT:

This is a very minor thing, but I'm still wondering what's going on. Commenters in Learning Chef (commenting via the HTML build) are showing up with really odd "names" like this:

![pastedgraphic-15](https://f.cloud.github.com/assets/821071/1409654/b43db5e0-3d96-11e3-8360-af2adafba722.png)

Any ideas what's going on? I know the top one, but I don't know who the sea otter is, so if I want to say anything to them, I don't know who it is. Help?

**Comment by odewahn** [comment]
Yep -- this happens when you invite someone as a private collaborator, but the collaborator does not provide a username when they create an account.  I _think_ they should be able to fix this by going to their profile in chimera.

Andrew

----- Original Message -----
