### ISSUE TITLE
Hiding or archiving inactive books

### ISSUE THREAD

**Issue by patrickdijusto** [MakerPress/atlas-public-feedback#316]
Is there a way to hide or archive inactive books so they don't clutter up one's Book screen?  I have some books I'm not actively working on, but I still want to retain access to the files if necessary.

**Comment by sandersk** [comment]
Hi @patrickdijusto,

Sorry, we don't have functionality at present to hide titles from the "Your Books" list. We do, however, allow you to sort the list by a Title, Date Created, etc., as well as filter by search terms using the field in the upper-right corner of the books list.

We'll keep in mind your feature request for hiding titles for a future release of Atlas.

Best,
Sanders
