### ISSUE TITLE
Issues with PDF build

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#318]
I'm guessing this is a newbie question. While trying to build this book:

http://ano-atlas2.herokuapp.com/books/1234000001926

I get the error below. Part of the issue is that the author is not using standard asciidoc markup (I can work with him on that) but I think there's also an issue of missing a particular file? (book-docinfo.xml)

Thanks :)

---

PDFJob
Failed at 2013-11-06 14:43:49 UTC

Job failed
Full error:

asciidoc: WARNING: book.asciidoc: line 3: {include:/usr/local/app/worker/tmp/pdf/1234000001926/book-docinfo.xml}: file does not exist
asciidoc: ERROR: Chapter-1.asciidoc: line 30: illegal style name: ================
asciidoc: ERROR: Chapter-1.asciidoc: line 41: illegal style name: ============================
asciidoc: ERROR: Chapter-1.asciidoc: line 54: illegal style name: Request      |     Response
asciidoc: WARNING: Chapter-1.asciidoc: line 77: section title out of sequence: expected level 2, got level 3
asciidoc: WARNING: Chapter-1.asciidoc: line 123: section title out of sequence: expected level 2, got level 4
asciidoc: FAILED: P-Authentication.asciidoc: line 24: unexpected error:
asciidoc: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/asciidoc", line 5672, in asciidoc
    document.translate(has_header) # Generate the output.
  File "/usr/local/bin/asciidoc", line 1554, in translate
    Section.translate()
  File "/usr/local/bin/asciidoc", line 2195, in translate
    Section.translate_body()
  File "/usr/local/bin/asciidoc", line 2203, in translate_body
    next.translate()
  File "/usr/local/bin/asciidoc", line 2798, in translate
    attrs['style'] = self.calc_style(self.index)
  File "/usr/local/bin/asciidoc", line 2731, in calc_style
    assert False
AssertionError
asciidoc: ------------------------------------------------------------

**Comment by jhosman** [comment]
Hi @bandersonoreilly,

No worries, this one is a little more obscure. It looks like the less-than symbols at the beginning of lines 24 and 74-77 in the P-Authentication.asciidoc file are causing the problem. The conversion is translating them as special actions of some sort, whereas it looks like you just want them to show up as less-than characters in the output. You'll just need to put a backslash character in front of each one to escape them. For example:

`\> Base64-encoding the credentials`

**Comment by jhosman** [comment]
Actually @bandersonoreilly, instead of escaping the character with a backslash, which can sometimes render the backslash character in the output as well, replace the less-than character with its unicode hex entity `&#x3c;`

**Comment by bandersonoreilly** [comment]
Glad to hear it's just a markup issue. In fact, I'll just have the author use our standard asciidoc markup for bullets. (instead of less-than symbols) Thank you, Jessica.
