### ISSUE TITLE
<title>s of Atlas pages

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#319]
The title bar of all the pages during a session is "O'Reilly Atlas"; this makes it difficult to use the dropdown on the browser's "back" button.

**Comment by sandersk** [comment]
Hi @jdeisenberg,

Thanks for this feedback. I agree that the title bar should update to facilitate navigating through your browser history. We're currently at work on the next version of Atlas, so I'll add this to our development list for a future release.

Sanders
