### ISSUE TITLE
Cursor off running under OS/X 10.9, Safari 7.0

### ISSUE THREAD

**Issue by MikeW50** [MakerPress/atlas-public-feedback#320]
When using OS/X 10.9 (13A603) and Safari 7.0 (9537.71), the cursor position is off when editing books. At least, it is on my system. Since no one else is reporting the issue, perhaps this is something specific to my system.

The issue began with the update to OS/X 10.9; it worked fine under 10.8. Clicking on the screen places the cursor approximately at the click location, but if you begin to type, characters appear in a different location, approximately one character to the let of the cursor location for every 10 characters that appear to the left of the cursor position. For example, start at the beginning of the line and use the right arrow key 10 times. The cursor appears after the 11th character in the line. Type a character. It appears after the 10th character on the line, not the 11th. After moving in 20 characters, a newly typed character appears two characters in front of the cursor.

Here's a before shot. The cursor is halfway across the p in airplane on the 4th line.

![fig 1](https://f.cloud.github.com/assets/3238992/1535651/c10963e0-4ca6-11e3-89fe-061257b823c9.jpg)

Here's a shot after typing a ? character. Not that the character is inserted 2.5 characters early, after the a in airplane.

![fig 2](https://f.cloud.github.com/assets/3238992/1535673/efb06572-4ca6-11e3-9676-ed43d48825c0.jpg)

Any idea how to get around this issue?

If it's needed, the book is Make: Rockets. The example is from http://ano-atlas2.herokuapp.com/books/1234000001734/versions/master/editor/Chapter-23.asciidoc, but the same thing happens in all of the text.

**Comment by sandersk** [comment]
Hi @MikeW50,

Thanks for reporting this issue to us. We embed the ACE editor (http://ace.c9.io/) in Atlas, and are currently working on upgrading it to fix the bug you've noted with the misplaced cursor in Mavericks. We hope to have the fix in place within the next couple of days.

In the meantime, there's a modification you can make locally to solve the problem in your web browser. In the Terminal, try running the following command:

```
defaults delete com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2ScreenFontSubstitutionEnabled
```

If you're interested in more context on the issue (which relates to handling of fractional fixed-width fonts), you may want to see the discussion here:

https://github.com/ajaxorg/ace/issues/1534

Let me know if you have any questions, or encounter any further issues.

Best,
Sanders

**Comment by lehni** [comment]
It's been a month since the last update so I was wondering if there is any progress on this issue? It seems rather wide-spread...

**Comment by MikeW50** [comment]
It's still very much a problem for me. The cited fix does not run cleanly on my Mac. Rather than track it down, I ended up switching to Chrome for Atlas work.

**Comment by sandersk** [comment]
Thanks for pinging us about this again, @MikeW50 and @lehni. I'll follow up with the rest of the development team on this and see where we are on getting the fix in place.

Thanks for your patience,
Sanders

**Comment by lehni** [comment]
Great, thanks! I'm using Ace over at http://sketch.paperjs.org/, and it's affecting Safari users. My theory is that it has to do with the Canvas next to it forcing Ace to use the hardware accelerated renderer for type. You can spot that by the thinner glyphs and lack of sub-pixel rendering. And perhaps this renderer is causing the wrong offsets?

Just my two cents, who knows maybe it helps with debugging.

**Comment by lehni** [comment]
I'm still hoping for this to get addressed soon. The editor is currently unusable on Safari on OSX 10.9

**Comment by lehni** [comment]
Oops, I just built the new version from the sources again, and the issue seemed to have since disappeared! This bug can probably be closed now.

**Comment by MikeW50** [comment]
No, it's still a problem running with OS/X 10.9.2 and Safari 7.0.2.

**Comment by sandersk** [comment]
Thanks, @MikeW50. We'll take another look at this issue.

Sanders

**Comment by zaremba** [comment]
Thanks to everyone for reporting on this issue. It has been corrected in the new version of Atlas (currently in beta). If you're still experiencing the problem with the current version of Atlas, please switch to a different browser for the time being--we suggest Firefox or Chrome.
