### ISSUE TITLE
Hebrew, Arabic, and Korean characters don't show up in PDF.

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#321]
Book: http://atlas.labs.oreilly.com/books/1234000000446 , ch08.asciidoc ; it looks great in Chimera, but the examples from Arabic, Hebrew, and Korean don't show up at all in the PDF. (Yes, I have fonts for all three installed.)

**Comment by adamwitwer** [comment]
Hi @jdeisenberg. The PDF build server has fallback fonts that should cover these glyphs, so it's just a matter of telling the stylesheets to use those fonts. I'll take a look at it tomorrow and update the stylesheet accordingly.

**Comment by adamwitwer** [comment]
Hi @jdeisenberg, this is fixed now. The fallback font is not a perfect match to the standard monospace font, but I think it looks okay but the characters that use the fallback are in consecutive order. But let me know if you disagree, and I can offer up some alternative options.
