### ISSUE TITLE
what on earth is the point of all those Latest Builds?

### ISSUE THREAD

**Issue by mattneub** [MakerPress/atlas-public-feedback#322]
I see 10 "Latest Build" listings. But I can only download the most recent one. So what is the point of all the others?

![screen shot 2013-11-22 at 3 57 40 pm](https://f.cloud.github.com/assets/838939/1605194/f0f6d6fa-53d1-11e3-94a6-6fa137162a71.png)

**Comment by sandersk** [comment]
Thanks for the feedback, @mattneub. You're correct that only the most recent build of each format type is accessible, so the other listings are somewhat extraneous. We include them simply to provide a log of what builds were run in the past and whether they succeeded or not.

The next release of Atlas (coming in early 2014) will include functionality in the Build list that will let you download the files from previous builds.

Best,
Sanders
