### ISSUE TITLE
Put the Build button at the top. THE TOP!

### ISSUE THREAD

**Issue by mattneub** [MakerPress/atlas-public-feedback#323]
I've got dozens of chapters. So every time I do a new PDF build I have to check PDF at the top of the page and then scroll scroll scroll to get to the bottom of the page where the actual Build button is. This is ridic. Put the Build button at the top, please - preferably right next to the PDF checkbox!

**Comment by ghost** [comment]
+1

**Comment by java-javascript** [comment]
+1

**Comment by sandersk** [comment]
Duly noted. We are revamping the UI for the Build page for the next release of Atlas (coming in early 2014), and the Build button will be accessible near the top of the page, without scrolling.

Best,
Sanders

**Comment by mattneub** [comment]
You closed this, but you haven't done it. I just got through writing a whole new book and the Build button is still at the bottom. Please reopen this issue, and don't close it until you've actually fixed this dreadful piece of interface.
