### ISSUE TITLE
Callouts within a literal block

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#324]
I'm trying to do callouts within a literal block that needs emphasis (see the \* in one of the lines below.  The backslashes were my attempt to get the callouts to work. Here's the markup I'm using:

```
====
[language="xml"]
[subs="specialcharacters,quotes"]
----
<filter id="drop-shadow">
    <feGaussianBlur in="SourceAlpha" stdDeviation="2" *result="blur"*>     \<1>
    <feOffset *in="blur"* dx="4" dy="4" *result="offsetBlur"*>    \<2>
    <feMerge>    \<3>
        <feMergeNode in="offsetBlur">
    </feMerge>
</filter>
----
====
<1> The +result+ attribute specifies stuff.
<2> The +<feOffset>+ primitive does stuff.
<3> The +<feMerge>+ primitive does even more stuff.
```

When I try to build, I get messages like this:

```
asciidoc: WARNING: ch10.asciidoc: line 117: no callouts refer to list item 1
asciidoc: WARNING: ch10.asciidoc: line 118: no callouts refer to list item 2
asciidoc: WARNING: ch10.asciidoc: line 119: no callouts refer to list item 3
```

I get the same messages without the backslashes.

(This is in ch10.asciidoc of http://atlas.labs.oreilly.com/books/1234000000446)

**Comment by sandersk** [comment]
Hi @jdeisenberg,

If you want callouts to be processed in addition to the emphasis markup, you can add "callouts" to the substitutions list, as in the following:

```
[[gaussian-blur-good-example]]
.Improved drop shadow filter
====
[language="xml"]
[subs="specialcharacters,callouts,quotes"]
----
<filter id="drop-shadow">
    <feGaussianBlur in="SourceAlpha" stdDeviation="2" *result="blur"*>     <1>
    <feOffset *in="blur"* dx="4" dy="4" *result="offsetBlur"*>    <2>
    <feMerge>    <3>
        <feMergeNode in="offsetBlur">
    <feMergeNode in="SourceGraphic"/>
    </feMerge>
</filter>
----
```

Order of the "subs" list matters, so please make sure to do "specialcharacters,callouts,quotes".

Hope this helps. Let us know if you run into further issues.

Thanks,
Sanders
