### ISSUE TITLE
PDF Job Failed - No space left on device

### ISSUE THREAD

**Issue by DanGitOreilly** [MakerPress/atlas-public-feedback#325]
Hello Good People,

I was contacted by an author this morning after he received the following error notice. The project he's working on lives here: 

http://ano-atlas2.herokuapp.com/books/1234000001610

I tried building a PDF and got the same message.

And this is the message:

Hi Dan,

I'm getting this:

PDFJob

Failed at 2013-12-03 13:36:07 UTC

Job failed

Full error:

No space left on device - /tmp/systemu_atlas-worker_18805_18808_0.4661019031343604_1

Please advise!

Foster

**Comment by adamwitwer** [comment]
Hi Dan,

Okay, I cleaned up a bit. We've got more space now.

```
# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/xvda1             75G   49G   24G  68% /
none                  996M  128K  996M   1% /dev
none                 1001M     0 1001M   0% /dev/shm
none                 1001M   40K 1001M   1% /var/run
none                 1001M     0 1001M   0% /var/lock
none                 1001M     0 1001M   0% /lib/init/rw
none                   75G   49G   24G  68% /var/lib/ureadahead/debugfs
```
