### ISSUE TITLE
Build error (relating to book.xml)

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#327]
I've got another build error -- not related to asciidoc syntax but something to do with the book.xml.

Link:
http://ano-atlas2.herokuapp.com/books/695/jobs/44862
## Error:

DCPS Error Log

/usr/local/app/worker/tmp/pdf/1234000001676/book.xml
== Error 1

/usr/local/app/worker/tmp/pdf/1234000001676/book.xml:10: parser error : Entity 'rsquo' not defined

---

<isbn></isbn><edition>2</edition><publisher><publishername>O&rsquo;Reilly Media, Inc.</publishername><address format="linespecific">

---

== Error 4

/usr/local/app/worker/tmp/pdf/1234000001676/book.xml:4677: parser error : Opening and ending tag mismatch: programlisting line 4646 and sect2

---

</sect2>

---

== Error 7

/usr/local/app/worker/tmp/pdf/1234000001676/book.xml:4719: parser error : Opening and ending tag mismatch: sect2 line 4643 and sect1

---

</sect1>

---

== Error 10

/usr/local/app/worker/tmp/pdf/1234000001676/book.xml:5371: parser error : Opening and ending tag mismatch: sect1 line 4637 and chapter

---

</chapter>

---

== Error 13

/usr/local/app/worker/tmp/pdf/1234000001676/book.xml:34804: parser error : Opening and ending tag mismatch: chapter line 3799 and book

---

</book>

---

== Error 16

/usr/local/app/worker/tmp/pdf/1234000001676/book.xml:34805: parser error : Premature end of data in tag book line 6

---

---

**Comment by sarahs** [comment]
Hey Brian. In ch04.asciidoc, the code block in the recipe " Counting the Days Since an Arbitrary Date" is missing a closing `</programlisting>` tag. If you add that, it should fix the build errors. Give me a shout if not.

**Comment by bandersonoreilly** [comment]
That fixed it -- thanks!
