### ISSUE TITLE
Backslashes in PHP code comments are nearly vertical

### ISSUE THREAD

**Issue by jhodgdon-drp** [MakerPress/atlas-public-feedback#328]
I am working on updating my book, Programming with Drupal, for Drupal 8.

Many of the code samples in the Drupal 8 version will have backslashes in them, because Drupal 8 makes extensive use of PHP namespaces, which use backslashes.

This is mostly coming out OK, but I'm finding that in the case of backslashes within comments in a code block, because the comment sections use italic formatting, the backslashes look more like vertical bars | instead of backslash \ -- which makes it pretty hard to read.

Here's an example:

```
[source,php]
----
  /**
   * The administrative label of the block.
   *
   * @var \Drupal\Core\Annotation\Translation
   */
  public $admin_label;
}

---
```

In the Atlas build PDF, this comes out looking like this image.
![verticalbackslash](https://f.cloud.github.com/assets/2294278/1695474/72dfc452-5eb2-11e3-8242-c37b83ac0f60.png)

I am not sure what it will look like in the finished print or e-book version, since I don't think the Drupal 7 (currently published) version of the book had any backslashes in its code samples, and most certainly not in comments... so it's possible this won't be a problem in print, but I imagine it will. Is there something that can be done about this?

**Comment by sandersk** [comment]
Hi @jhdrupal,

One potential solution that comes to mind is that we can turn off italicization of comments in the Web PDF of your book so that the backslashes will look better. The comments will still be highlighted in orange.

In print, this won't be an issue, because we don't have syntax highlighting turned on for the print version of 1-color-interior books.

Let me know what you think.

Thanks,
Sanders

**Comment by jhodgdon-drp** [comment]
Yes, that sounds like a good solution. You're right, in the print PDF the comments are not in italic script.

I haven't checked other e-book formats to see if it's a problem there, but if they are using italics for comments as well, then I think this fix would need to be applied to those formats as well.

**Comment by sandersk** [comment]
Hi @jhdrupal,

FYI, I've put into place a fix for the Web PDF so that comments are not italicized. I'll also be evaluating the EPUB and Mobi to see if changes are needed there as well.

Sanders
