### ISSUE TITLE
Suggestion: "snippets" support for external repos

### ISSUE THREAD

**Issue by ghost** [MakerPress/atlas-public-feedback#329]
The "snippet" mechanism seems to be set up only for the case where you have your book example code in the same repo as the book manuscript's asciidoc files. If you are documenting parts of an external repo (or two), you'd like to have an easy way to "symlink" these repos in to git, and also to ensure that they get pulled (or svn updated, or whatever) on the Atlas machine when you build the book.

This way, for example, if you fix a typo in your code example, it would show up in the next POD run for that book.

With the repo on Github, you could even use a GitHub web hook to cause the book to build when you committed to the repo, though it's probably not necessary.

**Comment by ghost** [comment]
As a further extension, it would be great if the "snippet" (code include) mechanism could generate HTTP links to an external repository, so we'd have the effect of:

.https://github.com/IanDarwin/javasrc/blob/master/src/main/java/javacomm/CommPortSimple.java[CommPortSimple.java]
 ====

---

// selected code here....

---

 ==== 

This would make all eBooks where an external repo is used, considerably more useful to our customers.

Implementation would need a tiny config file in the book's git repo for the snippet handler program to find the full path to the online repo, in the absense of which it doesn't try to output them as links.

**Comment by ghost** [comment]
After thinking about it a bit, I realize you won't want to include ANYTHING from a repo that you don't control, because you must have the entire book under your own source control, so I will just document what I plan to do and let others with this need copy it if they want.

Just have a shell script on your editing computer that copies the files with BEGIN markers from a checked-out-and-updated version of the external repo into the book repo. The utterly trivial shell script copyBEGINfiles does this:

cat ~/scripts/copyBEGINfiles
grep -lr //.BEGIN src | cpio -pd ~/book/jcb/

The workflow is thus (assuming the external source repo is in git):
- make changes to the code in the external repo, commit, pull to the local copy if needed.
- sh copyBEGINfiles
- cd to the book repo
- git commit -m "Sync from source repo" src
- if no errors, git push

Go to Atlas and start a build. 

Done

---

P.S. Still be nice to have the mechanism for generating HTTP links to the external repo e.g., githup, as in comment # 1

**Comment by sandersk** [comment]
Thanks for the feedback, @ghost, and for sharing your workflow for incorporating snippets into the book. We'll certainly evaluate implementing additional handling for autogenerating links to an external repository online.

Sanders
