### ISSUE TITLE
Eliminate requirement to construct book.asciidoc via Atlas Web UI?

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#33]
Tim Berglund from GitHub mentioned that as a power user, he would prefer that the book.asciidoc file not be auto-generated, but that he could supply his own:

"Maybe you could provide a template book.asciidoc file at the start of the project, or otherwise provide some very short-form documentation on what that file should contain, rather than auto-generating it."

I think part of his complaint here was largely based on an incomplete understanding of our current Web UI for constructing the book.asciidoc when triggering builds, but I do this he raises a good point that it doesn't necessarily make sense if you're doing all your work in a local repo to have to go back into the Atlas UI and construct the book.asciidoc file there. That said, I think this of feedback falls into the general bucket of "Why do I have to use the Atlas UI to do my builds?", and I know we've been discussing implementing post-commit hooks to do just that.

**Comment by runemadsen** [comment]
See my explanation in issue #32. It's true that we are auto-generating the
book.asciidoc, but this doesn't stop him from editing it on local. He can
easily edit the book.asciidoc on local, push it up, and that build order
will now be reflected in the build screen. This means that the only thing
he needs to use Atlas for is to press the "build" button, and this can
easily be ported to an atlas rubygem that works like the heroku gem (e.g.
`atlas build` from the command line).

He can also easily create a book.asciidoc in his local repo, and the web
app will not auto-generate it if it's already there.

On Mon, Jul 23, 2012 at 9:55 AM, Sanders Kleinfeld <
reply@reply.github.com
