### ISSUE TITLE
Suggestion: set default language for "snippets"

### ISSUE THREAD

**Issue by ghost** [MakerPress/atlas-public-feedback#330]
My book has several hundreds of code inserts, and all but a dozen are so in the same language.
Why should I have to repeat the language attribute on all of them? There should be a way to set
the default language for snippets on a per-book basis (though some authors would probably
prefer it on a per-chapter basis).

Thanks

**Comment by ghost** [comment]
Or, at least, default it from the filename extension? This is obvious, but your example doesn't imply that it works.

**Comment by sandersk** [comment]
Great feedback, @ghost. We'll look into the possibility of "inferring" language from file extension rather than making it an explicit attribute requirement. Will keep you posted on any updates on this.

Sanders
