### ISSUE TITLE
Suggestion: documentation

### ISSUE THREAD

**Issue by ghost** [MakerPress/atlas-public-feedback#331]
I missed the snippets feature (when it was added in Beta) through doing a quick search, rather than exhaustively reading the documentation a second time. Since we all know geeks don't read documentation (they grep it), you might change

Atlas now supports including “snippets” in your book content so that you can excerpt just a portion of a code listing from an external code file.

to

Atlas now supports "code insert" or "code include" “snippets” in your book content so that you can excerpt just a portion of a code listing from an external code file.

**Comment by zaremba** [comment]
Hi @ghost,

Thanks for the recommendation. We'll take another look at our documentation.

Thanks,
Adam
