### ISSUE TITLE
Suggestion: Snippets: Configurable delimiter

### ISSUE THREAD

**Issue by ghost** [MakerPress/atlas-public-feedback#332]
The snippets feature resembles something I wrote for Java Cookbook 1E back in 2001, but with different delimiters. I have 75 or so files market up already  to go, but they have "//+" instead of "// BEGIN" . Not to mention that BEGIN appears in two other
places, SQL transactions/stored procedures and in the middle of Java code generated/maintained by NetBeans. 

Thus it would be nice if there were a way to set the delimiter pair to something other than BEGIN and END.

Thanks

**Comment by sandersk** [comment]
Thanks for the feature request, @ghost. We'll look into adding config options for customizing the "BEGIN/END" delimiter text in future versions of the snippet library.

Sanders
