### ISSUE TITLE
Suggestion: "Snippet" - choice of exclude or include

### ISSUE THREAD

**Issue by ghost** [MakerPress/atlas-public-feedback#334]
The Snippet mechanism is nice, and I've been using it. 

One thing that would make it really rock would be the ability to exclude text,
instead of including it. Thus with

[filename="SomeFile.java", exclude="true", identifier="main", ...

then you could use lines like

```
  interesting stuff here
```

// BEGINEXCLUDE main
      boring stuff here that's not relevant to the example, e.g, Java setters/getters
// ENDEXCLUDE main
     more interestting stuff, or, even, the ending "}"

For an additional 20 points :-) add the ability to specify a comment to replace
the excluded stuff, eg., "// mundane setters/getters omitted..."
Either as an attribute to the [] block, or an // ELSEEXCLUDE region.

Thanks

**Comment by sandersk** [comment]
Thanks @androidcook, these are great suggestions that we'll definitely consider for future updates for the snippet functionality :)

Sanders
