### ISSUE TITLE
Image upload fails

### ISSUE THREAD

**Issue by mpresser-pivotal** [MakerPress/atlas-public-feedback#336]
Using Chrome Version 31.0.1650.63 on MacOS 10.6.8, I try to upload an image file from my local host using the media tab and getting a pop-up window.  It says "Uploading image" and just stays that way.  

Is this a bug?  How can I upload image files?

**Comment by zaremba** [comment]
Hi @mpresser-pivotal, sorry for the delayed response. Are you still having this problem?

I tested this and it seems to be working OK, but please reopen this ticket if you need further help.

Thanks,
Adam
