### ISSUE TITLE
Cannot change information on the cover page 

### ISSUE THREAD

**Issue by mpresser-pivotal** [MakerPress/atlas-public-feedback#337]
For book 1234000001919, I try to Edit Cover.  It allows me to make changes, which I can see visually on the cover page, but when I Save Cover, all the changes disappear.

**Comment by sandersk** [comment]
Hi @mepresser,

The cover editing functionality in Atlas is in beta right now, and is not Production-ready for creating custom covers, so please feel free to skip this step for now. When the book is ready to be released, someone on O'Reilly's Production team will handle getting the final cover loaded to the system.

Sorry for any confusion,
Sanders
