### ISSUE TITLE
Question: Comment on particular lines?

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#339]
Is there a way to select a couple of lines and comment on that in Atlas like Google Docs does? I have only been able to leave comments that apply to the entire doc. It'd be nice to be able to highlight the portion of the doc that the comment pertains to. Thanks in advance!

**Comment by sandersk** [comment]
Hi @markgrover,

At this time, it's not possible to add line- or paragraph-level comments directly in the Atlas editor (although paragraph-level commenting is a feature available in our Atlas reader app: http://chimera.labs.oreilly.com), but it is something we have on our roadmap for the future. 

Thanks for the suggestion, and we will keep Atlas users posted on enhancements related to commenting.

Best,
Sanders

**Comment by markgrover** [comment]
Thanks @sandersk. I will use this comment to share one more thing which you likely already know. The single biggest thing that is preventing us from using Chimera for getting feedback from external reviewers is the lack of resolve feature in Chimera. After we get a comment and we do something about it, we can't keep it around because that gets too confusing with comments that we haven't taken care of yet and I can't find a way to "resolve" the comment. So, the only solution we are left with is of deleting the comment after we have done something about it which I really don't like because it's losing information/context about the change. So, unless you have any better ideas on how to go about this (and if so, I'd really appreciate them), I think we are stuck with getting reviews on PDF files.

Thanks for your help, like always!

**Comment by sandersk** [comment]
Hi @markgrover,

Yes, completely understand where you're coming from here, and why Chimera doesn't meet your needs in terms of managing and resolving comments.

We're actually in the process of developing a new-and-improved collaboration suite built right into Atlas that is designed for the purpose of managing comments and tracking changes for editorial/technical reviews. Not sure it will be ready in time for your book (so small consolation there), but it's definitely something we plan to put in place for our authors.

Appreciate your understanding, and thank you again for your feedback, as it's helping us build a better system for future Atlas users.

Sanders
