### ISSUE TITLE
Create "templates" for authors to use when they click "New file" in Atlas

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#34]
Just had an idea when looking at Andrew's pull request to use more semantically descriptive labels for the heading buttons:

https://github.com/MakerPress/atlas/pull/114/

To take this one step further, I think collaborators would really like it if when they chose "New File" from the File Manager, in addition to entering the filename, they could also select a "template" from a dropdown list of book-component types, e.g.:

Preface
Chapter
Part
Appendix

And then when the collaborator is taken to the Write screen, instead of being presented with an empty editor window, they'd have skeleton text customized for the book-component type. For example, if they chose Chapter, they might get something like this:

```
== Enter Chapter title here

Start writing your first paragraph here 
```

I think this could be quite helpful to folks who are still getting up to speed on AsciiDoc markup, and might also prevent unexpected results in the ebook builds, as authors might be less likely to mix up Preface heading markup vs. Chapter heading markup, etc.

**Comment by MakerPress** [comment]
I like this idea a lot.  We could also do this (maybe?) as a button, since there's a framework alreaty in place for this to do.  So, maybe there would be a "Templates" section that had these 3 or 4 items beneath it.  So, you'd pick "Part" and it would plop in the template for you.  

Sanders, do you have proposed templates for each of these?

**Comment by sandersk** [comment]
Yup, below are my proposed templates. They just cover the basics, but I think that's what we want here.

I like the idea of sticking to some sort of convention for "replaceable" text that needs to be substituted with user-supplied values. Here, I've used ALL CAPS for that, but maybe that's too severe?

Sanders

Chapter:

```
== ADD YOUR CHAPTER TITLE HERE

START ENTERING BODY TEXT HERE...

=== HEADING 1 HERE

MORE BODY TEXT HERE...
```

Preface:

```
== Preface

Start entering body text here...

=== HEADING 1 HERE

More body text here...
```

Appendix:

```
[appendix]
== ADD YOUR APPENDIX TITLE HERE

Start entering body text here...

=== HEADING 1 HERE

More body text here...
```

Part:

```
= ENTER YOUR PART TITLE HERE

[partintro]
--
ENTER PART INTRO TEXT HERE
--
```

**Comment by runemadsen** [comment]
This is great!

**Comment by MakerPress** [comment]
We should also update the template for the source code block to capitalize "LANGUAGE" to follow Sanders' convention.

**Comment by sandersk** [comment]
Also, Dan mentioned to me today that it would be great to add some additional boilerplate sections to the Preface (like "Using Code Examples", "Safari Books Online", etc.), which we currently include in our Word template. I'll put together a new preface.asciidoc file that includes them.
