### ISSUE TITLE
Question: Does Atlas have spell checker?

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#340]
It would be really nice to have one!

**Comment by java-javascript** [comment]
Planned - see https://github.com/MakerPress/atlas-public-feedback/issues/302

**Comment by sandersk** [comment]
Hi @markgrover,

Yes, a spell checker is on the roadmap for the next release of Atlas--scheduled for early 2014 (likely February). Stay tuned!

Best,
Sanders
