### ISSUE TITLE
References in TOC appears as a small bulleted list item.

### ISSUE THREAD

**Issue by java-javascript** [MakerPress/atlas-public-feedback#341]
Nearing completion on:

http://ano-atlas2.herokuapp.com/books/1234000001559

Added a references page.  In PDF format, the page displays correctly inline, however, it is not formatted correctly in the table of contents (it appears as a small bulleted list item).

**Comment by sandersk** [comment]
Hi @java-javascript,

I fixed the issue here by formally retagging the References section as an appendix:

```
[[REFERENCES]]
[appendix]
== References ==
```

I also went back and did the same for the other two appendixes in your book.

Let us know if have any further questions, or encounter any other issues.

Best,
Sanders
