### ISSUE TITLE
Book Cover Cannot be Modified

### ISSUE THREAD

**Issue by java-javascript** [MakerPress/atlas-public-feedback#342]
Changes made to the cover cannot be persisted.  After clicking save, the cover reverts to previous state. 

http://ano-atlas2.herokuapp.com/books/1234000001559/versions/master/cover_creator

**Comment by sandersk** [comment]
Hi @java-javascript,

The cover editing functionality in Atlas is in beta right now, and is not Production-ready for creating custom covers, so please feel free to skip this step for now. When the book is ready to be released, someone on O'Reilly's Production team will handle getting the final cover loaded to the system.

Sorry for any confusion,
Sanders
