### ISSUE TITLE
Double underscores in xrefs interpreted as emphasis

### ISSUE THREAD

**Issue by dansanderson** [MakerPress/atlas-public-feedback#343]
I have a case where a section ID contains pairs of double-underscores. (The ID is generated from the section title by a tool.)  The AsciiDoc for a reference to this section is:

```
In <<Strings__Text__and_Blobs>>, we mentioned that text and blob values are not indexed...
```

This is converted by Atlas to:

```
<simpara>In <xref linkend="Strings<emphasis>Text</emphasis>and_Blobs"/>, we mentioned that text and blob values are not indexed...
```

Naturally, this is a parser error: `"Unescaped '<' not allowed in attributes values"`

At the very least, this should be a documented restriction of IDs.  Ideally, IDs would be read literally in all places where IDs can appear.

**Comment by dansanderson** [comment]
(This may be redundant with issue 266, but the specific case of parsing section IDs in limited contexts might be fixable, and desirable since IDs may be generated.)

**Comment by sandersk** [comment]
Hi Dan,

Yes, your assessment is right on: the AsciiDoc interpreter does indeed process inline markup characters within XREFs. In your particular case, you can indeed escape as follows (#266 has more context on escaping, as you noted):

```
In <<Strings\__Text__and_Blobs>>
```

I agree with you that this issue should at least be documented, and that it would be even better if ids in XREFs could be interpreted literally. This is something we will look into addressing in the longer term, as we're in the process of updating our AsciiDoc infrastructure right now for the next release of Atlas.

For now, I'd advise either escaping double-underscores in XREF id references, or just avoid using them in ids. I realize you're autogenerating the ids, so hope this isn't too much of an inconvenience.

Best,
Sanders
