### ISSUE TITLE
Add adoc extension support for asciidoc

### ISSUE THREAD

**Issue by gAmUssA** [MakerPress/atlas-public-feedback#344]
Hello,

Please, add *.adoc extension support for asciidoc document in atlas.

Thanks

**Comment by sandersk** [comment]
Hi @gAmUssA,

Great suggestion. Our next release of Atlas (coming in early 2014) will support the .adoc extension. For now, could you please stick with .asc or .asciidoc? If that's a problem for any reason, please let us know.

Thanks,
Sanders

**Comment by gAmUssA** [comment]
Ok, 
I renamed all our files back to asciidoc. 

Thanks!
