### ISSUE TITLE
Request to support language="c" in snippets

### ISSUE THREAD

**Issue by IanDarwin** [MakerPress/atlas-public-feedback#345]
While C is no longer the top language, it's still used. It'd be nice to not have to lie
and say "This C code is Java" :-)

Given that you have Java support it should be possible to get C going. There's only a few keywords in traditional C that aren't also keywords in Java, but some Java keywords are not C keywords...

Thanks if you can pull something together. For now I'm going with language="java" to stop get_snippet.py from whinging about it.

**Comment by sandersk** [comment]
Hi @IanDarwin,

Sure, that's no problem to do. However, question for you regarding the syntax of comments, as I'm not a C/C++ expert.

My Google research seems to tell me that standard comment syntax for C is:

``` c
/* This is a comment */
```

And for C++, it's:

``` c++
// This is a comment
```

But my research also tells me that some C compilers will also support C++-style // comments.

So two questions:
1. Is that summary correct?
2. Which style of comments are you using in _your_ book for C listings?

Thanks,
Sanders

**Comment by IanDarwin** [comment]
On Mon, Jan 06, 2014 at 05:44:09PM -0800, Sanders Kleinfeld wrote:

>    Hi [1]@IanDarwin,
> 
>    Sure, that's no problem to do. However, question for you regarding the
>    syntax of comments, as I'm not a C/C++ expert.
> 
>    My Google research seems to tell me that standard comment syntax for C
>    is:
> 
> /\* This is a comment */
> 
>    And for C++, it's:
> 
> // This is a comment
> 
>    But my research also tells me that some C compilers will also support
>    C++-style // comments.
> 
>    So two questions:
>     1. Is that summary correct?

That summary is correct. But multiline is OK as in Java:

/\* This is
- a
- comment
  */

I think C99 may mandate allowing the C++-style // comments as well,
but not sure.

> ```
> 2. Which style of comments are you using in your book for C listings?
> ```

Not even sure, but I generally favor the first style. 
You should probably accept both, since I might not be the only author
with a bit of C code here and there.

Thanks
Ian

**Comment by sandersk** [comment]
Great, thanks for the additional info, @IanDarwin.

I've gone ahead and added support for C snippet delimiters in the following form:

```
/* BEGIN snippetid */
...
/* END snippetid */
```

You can use whatever commenting style you like in the body of the code listings, but the snippet delimiters themselves should use the /\* ... */ style. 

Hope this is helpful,
Sanders
