### ISSUE TITLE
Several code constructs appear broken

### ISSUE THREAD

**Issue by deanwampler** [MakerPress/atlas-public-feedback#347]
In order to debug build failures, I created the following "toss.asciidoc" file and used the preview feature to see what works as described in the Getting Started With Atlas Guide and which don't seem to work. Here is the file:

```
[[TOSS]]

== Toss Chapter

Attempt to figure out how to get stuff to work.

----
case class Foo(s: String)
----

Got here.

[source,scala]
----
case class Boo(i: Int)
----

[filename="code-examples/prog-scala-2nd-ed/build.sbt", language="scala", identifier="CROSS_VERSIONS"]
snippet~~~~
Versions of Scala used to build and test the examples.ß
snippet~~~~

=== Include Test

Java code:

[source,java]
----
include::code-examples/prog-scala-2nd-ed/src/main/java/AppDesign/annotations/Pre.java[]
----

Java w/out the source,java head:

----
include::code-examples/prog-scala-2nd-ed/src/main/java/AppDesign/annotations/Pre.java[]
----

Source code:

[source,scala]
----
include::code-examples/prog-scala-2nd-ed/src/main/scala/TypeLess/shapes.scala[]
----

Without source,scala:

----
include::code-examples/prog-scala-2nd-ed/src/main/scala/TypeLess/shapes.scala[]
----

End of test.

```

This is the preview (as best I can reproduce it in this panel...):

_Toss Chapter_

Attempt to figure out how to get stuff to work.

`case class Foo(s: String)`

Got here.

snippet~~ Versions of Scala used to build and test the examples.ß snippet~~

Include Test
Java code:

(end of output)

So, only this appears to work, when I inline the code itself.

```
----
case class Foo(s: String)
----
```
1. What are the correct paths for the include and snippets directives?
2. Do the [source,xxx] work or not?

**Comment by sarahs** [comment]
Hi Dean,

The preview feature is intended to give a quick view of the formatting, but right now it doesn't support code blocks with `[source, <language>]` markup or included code files. However, that markup will render just fine in formats you generate via the Build tab. I just built a PDF that includes the toss.asciidoc file, and you can see in the result that the code constructs you've included in it are supported.

The only issue I noticed is a typo in the directory path in the last two include lines:

```
include::code-examples/prog-scala-2nd-ed/src/main/scala/TypeLess/shapes.scala[]
```

If you just change these to:

```
include::code-examples/prog-scala-2nd-ed/src/main/scala/TypeLessDoMore/shapes.scala[]
```

the code will render.

Please let us know if you run into any further issues.

Thanks,
Sarah

**Comment by deanwampler** [comment]
Thanks for letting me know. I won’t rely on the preview.

Catching the typo did me a big favor. Since the error feedback is completely opaque, I had no way of detecting it.

I noticed the book.asciidoc was changed to just use the temporary asciidoc file (which I’ve now deleted). I fixed it.

I could REALLY, REALLY use the temporary book.xml to diagnose these build failures. Can you at least mail the last one too me or just copy it to the repo?? I will happily delete old ones myself. On your server, the path to the last one is /usr/local/app/worker/tmp/epub/1234000001978/book.xml, that is assuming they aren’t deleted afterwards.

I’m kind of at my wits end on trying to get the book to build. I’m thinking of dusting off my own Asciidoc tools that I used for the 1st edition and just sending you guys docbook files. At least then I can debug my errors.

Dean

On Jan 7, 2014, at 9:10 AM, sarahs notifications@github.com wrote:

> Hi Dean,
> 
> The preview feature is intended to give a quick view of the formatting, but right now it doesn't support code blocks with [source, <language>] markup or included code files. However, that markup will render just fine in formats you generate via the Build tab. I just built a PDF that includes the toss.asciidoc file, and you can see in the result that the code constructs you've included in it are supported.
> 
> The only issue I noticed is a typo in the directory path in the last two include lines:
> 
> include::code-examples/prog-scala-2nd-ed/src/main/scala/TypeLess/shapes.scala[]
> If you just change these to:
> 
> include::code-examples/prog-scala-2nd-ed/src/main/scala/TypeLessDoMore/shapes.scala[]
> the code will render.
> 
> Please let us know if you run into any further issues.
> 
> Thanks,
> Sarah
> 
> —
> Reply to this email directly or view it on GitHub.

Dean Wampler
dean@deanwampler.com
@deanwampler

**Comment by sarahs** [comment]
Sure, I added the latest book.asciidoc.xml file to the repo, so you should be able to use it for debugging now.

As for the errors you're getting, I think the build will go through if you fix the following:

1) In ch01, there is a typo in the snippet delimiters in code-examples/prog-scala-2nd-ed/src/main/scala/IntroScala/upper1.sc, in that BEGIN UPPPER_METHOD and END UPPPER_METHOD should only have two "p"s if they are going to match the identifier noted in the chapter.

2) In ch02, in the code block under the sentence "Scala is like Java in that most variables are actually references to heap-allocated objects...", there is an opening `<console>` tag but no closing tag.

Let me know if you continue to get errors and I will take another look. Sorry you're running into trouble with the build. We are working to improve error reporting in the next release of Atlas, so hopefully the troubleshooting process won't be so frustrating in the future.

Sarah

**Comment by deanwampler** [comment]
Sarah,

Thank you, Thank you, Thank you!

Those <console> things are actual output from the Scala shell. I replaced them with &lt;console&gt; (and fixed the dumb “UPPPER” typo) and the PDF built!

I appreciate your attentive help very much. The xml file helped, too. If it’s an easy, temporary fix for the toolchain to simply copy those files into the repo somewhere, it would be a great help while you come up with more permanent improvements.

Yours,
Dean

On Jan 7, 2014, at 10:12 AM, sarahs notifications@github.com wrote:

> Sure, I added the latest book.asciidoc.xml file to the repo, so you should be able to use it for debugging now.
> 
> As for the errors you're getting, I think the build will go through if you fix the following:
> 
> 1) In ch01, there is a typo in the snippet delimiters in code-examples/prog-scala-2nd-ed/src/main/scala/IntroScala/upper1.sc, in that BEGIN UPPPER_METHOD and END UPPPER_METHOD should only have two "p"s if they are going to match the identifier noted in the chapter.
> 
> 2) In ch02, in the code block under the sentence "Scala is like Java in that most variables are actually references to heap-allocated objects...", there is an opening <console> tag but no closing tag.
> 
> Let me know if you continue to get errors and I will take another look. Sorry you're running into trouble with the build. We are working to improve error reporting in the next release of Atlas, so hopefully the troubleshooting process won't be so frustrating in the future.
> 
> Sarah
> 
> —
> Reply to this email directly or view it on GitHub.

Dean Wampler
dean@deanwampler.com
@deanwampler

**Comment by sarahs** [comment]
Great! Glad to hear the build is working. Please let us know if you run into further problems. There may be some workarounds we can try if errors continue to pose a problem.

Sarah

**Comment by deanwampler** [comment]
I need a copy of the current asciidoc.xml again, please. I can't resolve a
current breakage with the error messages alone. I've tried for the last
hour or so.

dean

On Tue, Jan 7, 2014 at 11:45 AM, sarahs notifications@github.com wrote:

> Great! Glad to hear the build is working. Please let us know if you run
> into further problems. There may be some workarounds we can try if errors
> continue to pose a problem.
> 
> Sarah
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MakerPress/atlas-public-feedback/issues/347#issuecomment-31760146
> .

## 

Dean Wampler, Ph.D.
Typesafe
"Functional Programming for Java Developers",
"Programming Scala", and
"Programming Hive" - all from O'Reilly
twitter: @deanwampler, @chicagoscala
http://typesafe.com
http://polyglotprogramming.com

**Comment by sarahs** [comment]
Sure thing. I added the latest book.asciidoc.xml file to the repo. Let us know if you need anything else.

Sarah

**Comment by deanwampler** [comment]
Thanks for giving me this. I know it was a holiday today ;)

It took a while to find the problem and it's not at all obvious why the
Asciidoc code doesn't work. The XML looks fine! I changed the markup to
something simpler and the pdf built again.

I'll post a bug for the problem.

Dean

On Mon, Jan 20, 2014 at 2:01 PM, sarahs notifications@github.com wrote:

> Sure thing. I added the latest book.asciidoc.xml file to the repo. Let us
> know if you need anything else.
> 
> Sarah
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MakerPress/atlas-public-feedback/issues/347#issuecomment-32792070
> .

## 

Dean Wampler, Ph.D.
Typesafe
"Functional Programming for Java Developers",
"Programming Scala", and
"Programming Hive" - all from O'Reilly
twitter: @deanwampler, @chicagoscala
http://typesafe.com
http://polyglotprogramming.com
