### ISSUE TITLE
Can't fix this build issue

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#348]
LINK:
http://ano-atlas2.herokuapp.com/books/656/jobs/47334
# 

DCPS Error Log

/usr/local/app/worker/tmp/pdf/1234000001637/book.xml
== Error 1

/usr/local/app/worker/tmp/pdf/1234000001637/book.xml:1242: parser error : Opening and ending tag mismatch: emphasis line 1242 and literal

---

The <emphasis role="strong">default value</emphasis> of the range input, if no value is set, is the minimum plus half the difference between the minimum and maximum (<literal>d = min + (max - min)<emphasis role="strong">.5</literal>). If the default min and max values are used, the default value is 50 (<literal>0 + (100-0)</emphasis>.5</literal>).

---

== Error 4

/usr/local/app/worker/tmp/pdf/1234000001637/book.xml:1242: parser error : Opening and ending tag mismatch: literal line 1242 and emphasis

---

The <emphasis role="strong">default value</emphasis> of the range input, if no value is set, is the minimum plus half the difference between the minimum and maximum (<literal>d = min + (max - min)<emphasis role="strong">.5</literal>). If the default min and max values are used, the default value is 50 (<literal>0 + (100-0)</emphasis>.5</literal>).

---

**Comment by sarahs** [comment]
Hi Brian. I think you can fix the errors if you change this markup in Chapter 3 (in the list right above EX3-16):

```
(+d = min + (max - min)*.5+)
```

to:

```
(+d = min + (max - min)\*.5+)
```

and this:

```
50 (+0 + (100-0)*.5+)
```

to:

```
50 (++0 + (100-0)*.5++)
```

Let me know if it doesn't work or if you run into any other trouble.

Sarah
