### ISSUE TITLE
Build issue: PDF version too low?

### ISSUE THREAD

**Issue by bmacdonald-editor** [MakerPress/atlas-public-feedback#349]
Link:

http://ano-atlas2.herokuapp.com/books/462/jobs/47323

Full error:

2014-01-13 15:59:40,185 INFO Input file: /usr/local/app/worker/tmp/pdf/1234000000782/book.xml.worker.316.xml
2014-01-13 15:59:40,186 INFO Output file: /usr/local/app/worker/tmp/pdf/1234000000782/book.xml.worker.316.xml.highlighted.xml
2014-01-13 15:59:40,262 INFO Pygmentizing 0 highlightable code listings, out of 32 total code listings
2014-01-13 15:59:40,265 INFO Outputting to /usr/local/app/worker/tmp/pdf/1234000000782/book.xml.worker.316.xml.highlighted.xml
AHFCmd : AH CSS Formatter V6.0 MR2 for Linux64 : 6.0.2.5372 (2012/05/16 18:26JST)
         Copyright (c) 1999-2012 Antenna House, Inc.

AHFCmd :FATAL: Error Level : 4
AHFCmd :FATAL: Error Code  : 16390 (4006)
AHFCmd :FATAL: PDF output error. (3335)
AHFCmd :FATAL: PDF version setting is lower than that of imported PDF.

AHFCmd :Formatting stopped by error

**Comment by sarahs** [comment]
Hi Brian,

This error has to do with three PDF images referenced in the book:

```
/images/binarysearch.pdf
/images/Fig%204-1.pdf
/images/Fig%204-2.pdf
```

These image files are PDF version 1.5 (you can find that out by opening them in Adobe Acrobat and clicking File->Properties). The Atlas toolchain can only handle PDF version 1.4 or lower. So, if you save the images down to 1.4 - or better yet, use PNG files instead - that should solve the problem.

Let me know if this doesn't work or if you have any other trouble.

Sarah

**Comment by bmacdonald-editor** [comment]
Hi, Sarah,

It makes sense that the figures would be the problem; thanks. However, the .png images are already in the project. How do I get rid of the PDF files?

--Brian

**Comment by sarahs** [comment]
Ah, you just need to change the references in the AsciiDoc files. So in searching.asciidoc, change this:

```
[[FIG2]]
.Binary search algorithm applied to guessing a number
image::images/binarysearch.pdf[]
```

to this:

```
[[FIG2]]
.Binary search algorithm applied to guessing a number
image::images/binarysearch.png[]
```

And same for the references to `images/Fig%204-1.pdf` and `images/Fig%204-2.pdf` in sorting.asciidoc.

Let me know if you have any trouble with this.

**Comment by bmacdonald-editor** [comment]
Good now, Sarah; thanks.
