### ISSUE TITLE
Switching to HTML View loses saved changes

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#35]
I made changes to the doc, saved them, made some more changes (including uploading and adding an image), then switched to the HTML view again, and lost all of my changes.

**Comment by odewahn** [comment]
Hi, Stafford.  There was a network outage the other day that might be behind some of the problem.  Can you send a link to your project and I'll check it out?

Andrew

----- Original Message -----
From: staffordvaughan reply@reply.github.com
To: Andrew Odewahn odewahn@oreilly.com
Sent: Wed, 01 Aug 2012 02:51:36 -0400 (EDT)
Subject: [atlas-public-feedback] Switching to HTML View loses saved changes (#35)

I made changes to the doc, saved them, made some more changes (including uploading and adding an image), then switched to the HTML view again, and lost all of my changes.

---

Reply to this email directly or view it on GitHub:
https://github.com/MakerPress/atlas-public-feedback/issues/35

## 

Andrew Odewahn
Chief Technology Officer
O'Reilly Media
617-460-6693

**Comment by staffordvaughan** [comment]
I've tested this a couple of times, actually. If I am editing a file and
add a word to the end of the page then don't save it before clicking "HTML
view", the HTML view will be generated based on the last saved version, and
going back to edit mode will also revert to the last saved version. When
you try to reproduce, is this not what you experience?

On Wed, Aug 1, 2012 at 7:41 AM, Andrew Odewahn <
reply@reply.github.com

**Comment by odewahn** [comment]
Hi, Stafford.  Yes -- this is a bug.  We need to save the page b/4 switching over to HTML preview.  Sorry for the inconvenience.

Andrew

----- Original Message -----

**Comment by josefprusa** [comment]
Happens to me too, its annoying :-/

**Comment by runemadsen** [comment]
This has been implemented now. If you try to navigate away from the editor with unsaved changes, you will get an alert box asking you to confirm. We're looking at making the HTML view just a tab, so the state in the editor will not change, but for now the "HTML View" is a new request reloading the window.
