### ISSUE TITLE
New Functionality Request:  Global View of Notes per chapter

### ISSUE THREAD

**Issue by java-javascript** [MakerPress/atlas-public-feedback#350]
Currently, the only way to see what notes editors have added for a given chapter is to either 
1)  go into Chimera, choose a chapter, and turn comments on or
2)  click on a chapter in Atlas, and view notes 

Request is for a global view for an entire book, ideally with drill-down.  

One idea:

[3 Notes]          Chapter 1  [View in Atlas] [View in Chimera]   

Clicking on "3 Notes" would lead to a list view of notes.
Clicking on "View in Atlas" would lead to the chapter in question in Atlas

**Comment by sarahs** [comment]
Thanks, @java-javascript, this is good feedback. We're currently hard at work on the next release of Atlas, and improving the collaboration tools and interface are high priority. Thanks for the suggestion, and we'll keep you posted.

Sarah
