### ISSUE TITLE
programlisting tag seems to produce valid XML, yet the build fails. 

### ISSUE THREAD

**Issue by deanwampler** [MakerPress/atlas-public-feedback#351]
This is for my Programming Scala book. The "++++<programlisting..." section starting at line 1350 in ch03-TypeLessDoMore.asciidoc causes the build errors I experienced today, but replacing it with simpler market resulted in a successful build.

This seems to produce valid XML (at least I saw no problems), yet the build fails (error message at the bottom of this post):

```
++++
<programlisting format="linespecific" language="scala"><code role="statement">scala&gt; <userinput>val s = "Programming Scala"</userinput>
s: String = Programming Scala

scala&gt; <userinput>s.reverse</userinput>
res0: String = alacS gnimmargorP

scala&gt; <userinput>s.capitalize</userinput>
res1: String = Programming Scala

scala&gt; <userinput>s.foreach(c =&gt; print(s"$c-"))</userinput>
P-r-o-g-r-a-m-m-i-n-g- -S-c-a-l-a-
</programlisting>
++++
```

This works:

```
[source,scala]
----
scala> val s = "Programming Scala"
s: String = Programming Scala

scala> s.reverse
res0: String = alacS gnimmargorP

scala> s.capitalize
res1: String = Programming Scala

scala> s.foreach(c => print(s"$c-"))
P-r-o-g-r-a-m-m-i-n-g- -S-c-a-l-a-
----
```

NOTE: for those last two lines, I tried using "," instead of "-", but it didn't matter.

Here is the error message that was reported:

```
DCPS Error Log

/usr/local/app/worker/tmp/pdf/1234000001978/book.xml
== Error 1

/usr/local/app/worker/tmp/pdf/1234000001978/book.xml:2836: parser error : Opening and ending tag mismatch: code line 2825 and programlisting


----
</programlisting>


----
== Error 4

/usr/local/app/worker/tmp/pdf/1234000001978/book.xml:2838: parser error : Opening and ending tag mismatch: programlisting line 2825 and sect2


----
</sect2>


----
== Error 7

/usr/local/app/worker/tmp/pdf/1234000001978/book.xml:2839: parser error : Opening and ending tag mismatch: sect2 line 2717 and sect1


----
</sect1>


----
== Error 10

/usr/local/app/worker/tmp/pdf/1234000001978/book.xml:3102: parser error : Opening and ending tag mismatch: sect1 line 2665 and chapter


----
</chapter>


----
== Error 13

/usr/local/app/worker/tmp/pdf/1234000001978/book.xml:17706: parser error : Opening and ending tag mismatch: chapter line 1336 and book


----
</book>


----
== Error 16

/usr/local/app/worker/tmp/pdf/1234000001978/book.xml:17707: parser error : Premature end of data in tag book line 6
----
```

**Comment by sandersk** [comment]
Hi @deanwampler,

The first part of that error message indicates the problem:

```
/usr/local/app/worker/tmp/pdf/1234000001978/book.xml:2836: parser error : Opening and ending tag mismatch: code line 2825 and programlisting
```

It's saying that the opening tag `<code>` doesn't have a corresponding closing tag `</code>`; the XML parser hits the closing tag for the whole code listing (`</programlisting>`) first. The problematic line is here:

```
++++
<programlisting format="linespecific" language="scala"><code role="statement">scala&gt; <userinput>val s = "Programming Scala"</userinput>
...
```

I'm assuming perhaps you intended to add a closing `</code>` tag to the end of the line, e.g.:

```
++++
<programlisting format="linespecific" language="scala"><code role="statement">scala&gt; <userinput>val s = "Programming Scala"</userinput></code>
...
```

Hope this helps,
Sanders

**Comment by deanwampler** [comment]
Ah. I missed the code tag. I edited the markup from the original book. The
extra pair of eyes helped. Thanks.

The error message was not clear, it complained about the </programlisting>
tag and didn't show me this particular line. It took me hours to
triangulate to this particular code in the asciidoc file. (It was over the
holiday weekend so I couldn't get someone to send me the XML file until
Monday night.)

The best thing the Atlas team could do for me (and other authors,
presumably) is to copy the built xml file into the git repo automatically.
Or, put a link on the error page to download it. That way, we can see the
lines around the XML error and locate them in the asciidoc files. Sometimes
the XML line shown in the message has meaningful information, but not when
it just says "</programlisting>" and the line number has no connection to
the source files.

dean

On Wed, Jan 22, 2014 at 5:11 PM, Sanders Kleinfeld <notifications@github.com

> wrote:
> 
> Hi @deanwampler https://github.com/deanwampler,
> 
> The first part of that error message indicates the problem:
> 
> /usr/local/app/worker/tmp/pdf/1234000001978/book.xml:2836: parser error : Opening and ending tag mismatch: code line 2825 and programlisting
> 
> It's saying that the opening tag <code> doesn't have a corresponding
> closing tag </code>; the XML parser hits the closing tag for the whole
> code listing (</programlisting>) first. The problematic line is here:
> 
> ++++
> <programlisting format="linespecific" language="scala"><code role="statement">scala&gt; <userinput>val s = "Programming Scala"</userinput>
> ...
> 
> I'm assuming perhaps you intended to add a closing </code> tag to the end
> of the line, e.g.:
> 
> ++++
> <programlisting format="linespecific" language="scala"><code role="statement">scala&gt; <userinput>val s = "Programming Scala"</userinput></code>
> ...
> 
> Hope this helps,
> Sanders
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MakerPress/atlas-public-feedback/issues/351#issuecomment-33079877
> .

## 

Dean Wampler, Ph.D.
Typesafe
"Functional Programming for Java Developers",
"Programming Scala", and
"Programming Hive" - all from O'Reilly
twitter: @deanwampler, @chicagoscala
http://typesafe.com
http://polyglotprogramming.com
