### ISSUE TITLE
Source code in a table cell

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#352]
I am trying to create a two-column table with plain text in the first column and a soure code example in the second column. I cannot seem to convince asciidoc to do this for me.

```
[options="header"]
|===============
|English|XSLT
|Process an +_element_+ element|
[source,xml]
----
<xsl:template match="element">
  <!-- output to produce -->
</xsl:template>
----
|===============
```

**Comment by chrishearse** [comment]
Hello,

To make everything in the right column appear literal (so you don't have to include the asciidoc code markup) you can put [cols="asciidoc,literal",options="header"] above the table. For example:

[cols="asciidoc,literal",options="header"]
|===============
|English|XSLT.... 

To include an actual code example with syntax highlighting you can use the following code by passing it through to DocBook (I don't think AsciiDoc wants to work well here):

+++
<programlisting language="xml">
    &lt;xsl:template match="_element_">
      &lt;!-- output to produce -->
    &lt;/xsl:template>
</programlisting>
+++

The +++ before and after the code will pass the code in between to DocBook. From there <programlisting language="xml"> makes sure that whatever is inside will be code with proper syntax highlighting. Lastly &lt; and &gt; are just the < and > symbols. It won't render properly if you use both < and > symbols  between the <programlisting>s.

Thanks,

Chris

**Comment by jdeisenberg** [comment]
Thanks; I think I can do without the highlighting (especially as the contrast on Chimera is really low and makes the examples hard to read).
