### ISSUE TITLE
Is there a way to add line numbers to code listing?

### ISSUE THREAD

**Issue by ramalho** [MakerPress/atlas-public-feedback#355]
I know about callouts, but in on particular instance I need line numbers

**Comment by sandersk** [comment]
Hi @ramalho,

It's not O'Reilly house style to add line numbers to code listings, and we generally don't use them in our titles, unless there's a compelling use case for them. 

If you want line numbers for cross-referencing purposes (e.g., so you can say things like "see line 24 of the above listing"), we'd recommend either using comments to annotate the code inline or using callouts (http://chimera.labs.oreilly.com/books/1230000000065/ch04.html#asc_callouts). The problem with using line numbers to cross-reference is that they can be especially fragile; if code listings are revised and lines are added/deleted, the line-number references can easily get out of sync.

If inline annotations or callouts don't meet your needs, can you please give us more details about your specific use cases, so we can figure out an appropriate solutions?

Thanks,
Sanders
