### ISSUE TITLE
Code blocks have different sized spaces

### ISSUE THREAD

**Issue by clintongormley** [MakerPress/atlas-public-feedback#356]
Have a look at: http://chimera.labs.oreilly.com/books/1230000000825/ch06.html

The comments in the right of the first code block on that page should be aligned. They're not, because your CSS is colliding.

You have a `<pre>` tag around the code block with font-size `0.9em`, then individual `<code>` tags within the `<pre>` tag which are ALSO font-size `0.9em`.  That means that the letters within the `<code>` tags are being rendered as `0.81em` while the spaces between the `<code>` tags are rendered as `0.9em`.

If you just set the code tags within the pre block to use `font-size: 1em`, then everything is aligned correctly.

**Comment by sandersk** [comment]
Hi @clintongormley,

Great catch! We'll review our CSS and get a fix in place. Will let you know when it's live.

Thanks,
Sanders

**Comment by nelliemckesson** [comment]
Thanks for the catch @clintongormley ! We just deployed your recommended fix, which seems to be doing the trick.

**Comment by clintongormley** [comment]
Looking good @nelliemckesson - thanks for sorting
