### ISSUE TITLE
snippet markup is too verbose

### ISSUE THREAD

**Issue by ramalho** [MakerPress/atlas-public-feedback#357]
the snippet functionality is excellent, but the markup to make it work is too verbose:

[filename="code/iterables/sentence_iter.py", language="py", identifier="SENTENCE_ITER"]
snippet~~~~
This should not be mandatory
snippet~~~~

Contrast with:

include::code/iterables/sentence_iter.py[]

Suggested simplifications (prioritized):
1) make the snippet~~~~ block optional
2) make "language" optional, default to whatever the file extension suggests
3) use "file" instead of "filename"
4) use "mark" instead of "identifier" (shorter and more descriptive)

IMHO, (1) is a deal breaker

**Comment by sandersk** [comment]
Thanks very much for your feedback, @ramalho. We will take it under consideration for future releases of the snippet library.

Best,
Sanders
