### ISSUE TITLE
Error 500 trying to upload an image

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#36]
After performing the steps in ticket 35, I then clicked "Images" and got an error saying "We're sorry, but something went wrong.". I assume that the 500 in top right of the message is a HTML status code 500. Trying to go back to the dashboard then opening the file again in the same browser session still produces the same error.

**Comment by staffordvaughan** [comment]
This bug still occurs after restarting my browser. The page is http://ano-atlas2.herokuapp.com/books/1230000000581/versions/master/editor/Chapter-1:-Introduction-to-Zendesk.asciidoc.

**Comment by runemadsen** [comment]
Thanks for the bug report. I'm looking into it right now, and will update you as soon as it's resolved.

**Comment by runemadsen** [comment]
This has been fixed now. The spaces in the image name were not being URL encoded, and that was causing the error. Let me know if you find anything else.

**Comment by staffordvaughan** [comment]
Thanks. I'm not getting the error 500 anymore, but the image isn't being embedded. My markdown looks like this:

---

After logging in as an administrator, you can open the product administration section directly by clicking the cog icon in the bottom-left corner of every screen. The icon looks like this:

## image::images/Screen Shot 2012-07-31 at 11.46.30 PM.png[scaledwidth="90%"]

Are the spaces causing problems again? Anything you can do about supporting spaces in a filename?

**Comment by staffordvaughan** [comment]
Moved this into another issue (#37).
