### ISSUE TITLE
callout numbering should be ascending in the numbered listing, not in the code listing

### ISSUE THREAD

**Issue by ramalho** [MakerPress/atlas-public-feedback#360]
The sequence of execution of source code is not always top down, but the explanation in the numbered listing following the source code is always meant to be read top down. However, currently Atlas is renumbering the callouts in the source code and when it does the same thing to the numbered listing it looks wrong. And the numbering may induce readers to read the numbered listing out of order.

The picture shows just part of a source code listing and the numbered items that follows it.

![callout-bug-2](https://f.cloud.github.com/assets/29944/2030251/2424c63e-88f4-11e3-9a9e-d8496ee5608e.png)

**Comment by zaremba** [comment]
Hi @ramalho, I think Chris responded to this one in #359. If you need further help, please let us know.

Thanks,
Adam
