### ISSUE TITLE
Chapter not updated; clicking on Changes tab produces error

### ISSUE THREAD

**Issue by MarcRochkind** [MakerPress/atlas-public-feedback#361]
I just pushed a lot of files, and when I build the chapter I get the old version. Clicking on the Changes tab gives a 500 error with the message "We're sorry, but something went wrong. If you think this is a bug, please report it".

**Comment by sandersk** [comment]
Hi @MarcRochkind,

Sorry that you're running into some difficulties here. We'd be happy to take a look. Can you tell us which title you're working on in the system?

Thanks,
Sanders

**Comment by MarcRochkind** [comment]
It's "Programming Chrome Apps"

**Comment by MarcRochkind** [comment]
It's working now.

**Comment by sandersk** [comment]
Oh great. Sometimes, if you're viewing the PDF in your browser, it may cache the old version of the file, and you may need to refresh to ensure you're getting the latest file.

Let us know if you encounter any further issues. 

Thanks,
Sanders

**Comment by MarcRochkind** [comment]
Building with the latest version isn't really the issue. The issue is that after a lot of pushes, I get a 500 error from the Changes tab. With just a few files pushed, it works OK. Probably some sort of capacity or timeout error while the report of so many changes is being compiled.
