### ISSUE TITLE
get snippets supported in offline asciidoc?

### ISSUE THREAD

**Issue by MarcRochkind** [MakerPress/atlas-public-feedback#363]
I use a local installation of asciidoc (on a Mac) for proofreading and getting my format right, but there's no support for snippets. Is there some plugin I can install locally?

**Comment by sandersk** [comment]
Hi @MarcRochkind,

Yes, we can assist with getting you a proper local config that you can use, along with the snippet plugin. Could you send mail to your editor with this request, and then our Tools group will assist.

Thanks,
Sanders
