### ISSUE TITLE
Converting .xml files for use in Atlas

### ISSUE THREAD

**Issue by ianmolynz** [MakerPress/atlas-public-feedback#364]
Hi, I have previously used the XMLMind editor to author book content so its fairly impractical to update existing content at the raw XML level. Is there any easy way to convert the existing .xml files to asciidoc so I can use the standard editor?

KR
Ian

**Comment by sandersk** [comment]
Hi @ianmolynz,

Is this for a new book project you're doing with O'Reilly? If so, let me know, as our Tools department can assist with this task.

Thanks,
Sanders

**Comment by ianmolynz** [comment]
Hi Sanders,

Many thanks for the response.
I am looking to create an updated edition of an existing book so any help you can provide would be much appreciated.

KR
Ian

**Comment by sandersk** [comment]
Sure thing, @ianmolynz. Can you pass on this request to your editor at O'Reilly? Then we can take it from there.

Thanks,
Sanders

**Comment by ianmolynz** [comment]
Will do and many thanks.
Andy, can you start the ball rolling on this?

KR
Ian
