### ISSUE TITLE
Need code to wrap to a new line

### ISSUE THREAD

**Issue by swartzrock** [MakerPress/atlas-public-feedback#367]
Hi folks, issue https://github.com/MakerPress/atlas-public-feedback/issues/134 raises the problem I'm having: when building a PDF from my asciidoc doc in atlas, certain source code blocks don't wrap and therefore continue right off the page.

What can I do to ensure the source blocks will wrap?

Here is an example source code block:

---

scala> @annotation.tailrec def power(x: Int, n: Int): Long = if (n >= 1) x \* power(x, n-1) else 1
<console>:8: error: could not optimize @tailrec annotated method power: it contains a recursive call not in tail position
##        @annotation.tailrec def power(x: Int, n: Int): Long = if (n >= 1) x \* power(x, n-1) else 1

Here is the result:
![image](https://f.cloud.github.com/assets/127138/2306952/4acf1448-a29d-11e3-948f-e98b85ac0ad1.png)

Thanks!

**Comment by chrishearse** [comment]
Hi Jason,

I can definitely add an override that makes all code wrap automatically, but it wraps at the end of the acceptable code length (around the rightmost side of the paragraph blocks - where "to let the Scala", "if it cannot be", and "not the last statement" is). 

Either you'd have to break the code yourself so it doesn't go past that right most side there or we can add an all around code wrapper. Let me know what you'd like - if you want the automatic code wrapping I'll need to add a file to the repo so feel free to push any changes you may have.

Thanks,
Chris

**Comment by swartzrock** [comment]
Hi Chris, what column is the official acceptable code length?

**Comment by chrishearse** [comment]
Hi Jason,

The allowed number of characters per line of code (code blocks) is about 84. 

So for the example source code block you mentioned the code on the first line should end at:

scala> @annotation.tailrec def power(x: Int, n: Int): Long = if (n >= 1) x \* pow

and the rest of the code after the "w" would continue to the next line. However, I know that doesn't read well at all :) , so I'd recommend breaking it by hand if you want it to very human readable.

(FYI: If we set up automatic code wrapping it would wrap at something like at the "w" in "power" or so I just mentioned for every code line that reaches the maximum word count.)

Thanks,

Chris
