### ISSUE TITLE
Chimera comments getting lost when commenter's device disconnects from the internet

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#368]
Say, I am on a laptop connected to the internet. I go to a page on Chimera to leave some comments. I leave a few, they get stored. At this point, let's say, the laptop disconnects from the internet for a few minutes and I keep leaving comments, not knowing about any such disconnect. Then, the internet connection resumes.

It looks like any comments I left during the internet disconnect would not be stored. If I were to refresh the page, the comments made during that time would all disappear. Can we please fix this? Atleast show an error message or disallow the comment from being visible on the web interface (exactly like all the stored comments) so commenters don't assume that their comment got posted.

**Comment by sandersk** [comment]
Thanks very much for the detailed bug report @markgrover. We're currently working on a new generation of collaboration/commenting tools for Atlas/Chimera, and we'll take these considerations related to offline usage into account.

Best,
Sanders
