### ISSUE TITLE
Spaces supported in filenames

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#37]
Further to issue 36, I'm having some trouble showing an image and suspect that spaces in the filename are the problem. Can you please confirm if the following syntax is valid?

image::images/Screen Shot 2012-07-31 at 11.46.30 PM.png[scaledwidth="90%"]

If spaces are not supported, any idea when they might be?

**Comment by runemadsen** [comment]
I'm fixing this right now. Spaces in file names on the web is generally not
a great idea, but we can support it by replacing spaces with %20. This
means that you can change your image embed to this and it will work:

image::images/Screen%20Shot%202012-07-31%20at%2011.46.30%20
PM.png[scaledwidth="90%"]

I'll make the image manager insert images with spaces like this. Give me
half an hour.

On Wed, Aug 1, 2012 at 11:33 AM, staffordvaughan <
reply@reply.github.com

**Comment by runemadsen** [comment]
This has been fixed now. Let me know if you run into more problems.

**Comment by sandersk** [comment]
I was taking a look at this as well, Rune, and something odd is happening with the builds; the PDF build appears to be being generated from a previous version of the content that doesn't reflect the author's latest commits.

In my latest PDF build, the text "(BUG IN ATLAS IS PREVENTING ME FROM UPLOADING A SCREENSHOT" is included, even though that was deleted from the source in a previous commit.

Also, image is still not showing up in EPUB/Mobi build, which I suspect is a worker-side issue that I can look into.

**Comment by runemadsen** [comment]
Hmm. Weird. I'm seeing the image in the PDF. Maybe it's a caching thing on
your machine? Or S3 was a little slow on updating to the newest PDF?

On Wed, Aug 1, 2012 at 12:36 PM, Sanders Kleinfeld <
reply@reply.github.com

**Comment by sandersk** [comment]
Ah, I'm seeing it now, too. Sorry for the unnecessary red flag there.

**Comment by staffordvaughan** [comment]
That might have been my fault as well - I was playing around with the
source code immediately after the change was made, so things might have
been out of sync. Thanks for fixing it, guys!

On Wed, Aug 1, 2012 at 10:03 AM, Sanders Kleinfeld <
reply@reply.github.com

**Comment by MakerPress** [comment]
Yep -- this is another bug.  We don't (yet) support spaces in filenames.  The way to fix this is to reupload the figure with a new name, or to use command line git (if you're a git person) to rename it.  Then change the image tage to reference to the new filename.

Sorry for the inconvenience, and keep the feedback coming!

Andrew

----- Original Message -----
From: staffordvaughan reply@reply.github.com
To: MakerPress makerpressadmin@oreilly.com
Sent: Wed, 01 Aug 2012 11:33:54 -0400 (EDT)
Subject: [atlas-public-feedback] Spaces supported in filenames (#37)

Further to issue 36, I'm having some trouble showing an image and suspect that spaces in the filename are the problem. Can you please confirm if the following syntax is valid?

image::images/Screen Shot 2012-07-31 at 11.46.30 PM.png[scaledwidth="90%"]

If spaces are not supported, any idea when they might be?

---

Reply to this email directly or view it on GitHub:
https://github.com/MakerPress/atlas-public-feedback/issues/37

## 

Andrew Odewahn
Chief Technology Officer
O'Reilly Media
617-460-6693

**Comment by adamwitwer** [comment]
Fixed here:

https://github.com/MakerPress/atlas-public-feedback/issues/26#issuecomment-7795437
