### ISSUE TITLE
Error for Titled Warning in "Getting Started with Atlas" Guide

### ISSUE THREAD

**Issue by aplimpton** [MakerPress/atlas-public-feedback#372]
In the guide: http://chimera.labs.oreilly.com/books/1230000000065/ch04.html#Admonitions

The sample for Titled Warning has [TIP] and not [WARNING] under the title. 
Shows as:
.Warning Title
# [TIP]
# Here's some text inside a warning.

**Comment by sandersk** [comment]
Thanks very much for catching this error, @aplimpton. I fixed the error in the sample markup, so the content is correct here now:

http://chimera.labs.oreilly.com/books/1230000000065/ch04.html#Admonitions

Sanders
