### ISSUE TITLE
Horizontal break after the first author name in Chimera

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#375]
In a book with multiple authors and the book-docinfo.xml reflecting so, Chimera seems to put a horizontal break right after the name of the first author and before the name of all other authors.

Now this is really bad, because often times (and you'd hope), no one author is any more or less important than the other and in such cases, it's rather a little too biasing to have the first author's name separated from the others. Can you please get rid of the horizontal break or suggest a workaround? A prompt action would be great appreciated!

My current workaround is to have the first author empty so all authors appear after the horizontal break but that looks ugly in the PDF format because now we get <blank space>, first author, second author, etc. on the title page.

Thanks so much!

**Comment by sandersk** [comment]
Thanks for reporting this issue, @markgrover. Will aim to get a CSS fix in place for this early next week, so that things will render properly without the markup workarounds that are causing issues in PDF output.

**Comment by markgrover** [comment]
Thankss @sandersk Looking forward to the fix!

**Comment by markgrover** [comment]
Any update on this @sandersk ?
Thanks in advance!

**Comment by sandersk** [comment]
Hi @markgrover,

Should be all set now. I also updated the template for PDF to be the correct design for your book. Let me know if you see any further issues.

Sanders

**Comment by markgrover** [comment]
Looks great, thanks @sandersk, appreciate the quick turnaround!
