### ISSUE TITLE
Table Headers Missing

### ISSUE THREAD

**Issue by MikeW50** [MakerPress/atlas-public-feedback#376]
Please take a look at http://ano-atlas2.herokuapp.com/books/1234000001734. This book is using the two-column Maker format for PDFs. In this format, all of my table headers are missing. Do I need to do something different to get table headers in this format?

**Comment by sandersk** [comment]
Hi @MikeW50,

Can you point us to an example of markup or a page in the PDF where table headers aren't rendering? I'm looking at the most recent PDF you generated now, for example, and I see headers in Table 4-4 on page 79.

Thanks,
Sanders

**Comment by MikeW50** [comment]
Hi @sandersk,

It appears someone stopped by and fixed the problem. I found this in my repository log:  

thead, thead tr, thead tr td, thead tr p {
color: cmyk(100%,0%,0%,20%); /\* background-color: 
cmyk(0%,0%,0%,0%);*/
}

The original code, from boilerplate that was supplied to me when I started the book, was:

thead, thead tr, thead tr td, thead tr p {
color: cmyk(100%,0%,0%,20%); background-color: cmyk(0%,0%,0%,0%);
}

The change was logged: Sarah Schneider commenting out table header background color so headers display in pdfs March 25, 2014, 11:47AM

This fixed the problem. Thanks, Sarah! And thanks for checking back on this, Sanders.

**Comment by sarahs** [comment]
Hi @MikeW50,

Yes, I was able to fix this in the oneoff, and apparently my response to you in this thread didn't go through - sorry about that! Glad to hear the headers are working now, though.

Sarah

**Comment by sandersk** [comment]
Thanks, @sarahs! :smile:
