### ISSUE TITLE
Atlas build page only allows top level files to be built

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#378]
On the build page, Atlas only allows to include pages from the top level book repository to be included in book.asciidoc. It would be nice to include other files from sub-directories via the GUI as well e.g. chapter-1/section1.asciidoc, chapter-1/section2.asciidoc

**Comment by markgrover** [comment]
This is worse than what I thought, BTW. Primarily, because Atlas overrides book.asciidoc whenever we update the build page on Atlas, clobbering any existing includes from the sub-directories. At the very least, I'd really really appreciate if Atlas didn't clobber any specific entries it didn't understand/support so we can manage and maintain the book.asciidoc file ourselves instead of Atlas.

**Comment by markgrover** [comment]
And, if anyone else is wondering the workaround here is to create another top level asciidoc file that includes files from sub-directories and include this top-level asciidoc file in book.asciidoc (via Atlas).

**Comment by sandersk** [comment]
Hi @markgrover,

Yes, that's the workaround we'd recommend as well. In our next release of Atlas, the UI will support builds of files in subdirectories, as we know this is a valuable feature.

Best,
Sanders

**Comment by markgrover** [comment]
Thanks @sandersk Do let us know when the next release of Atlas is out!
