### ISSUE TITLE
Question: What is the difference between atlas.labs and atlas?

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#380]
I can log in fine at http://atlas.labs.oreilly.com/ to edit books, but when I go to http://atlas.oreilly.com/ and try to sign in, it doesn't know that I exist. Given all the issues that I have seen closed lately, is the latter URL a later, better version?

**Comment by sandersk** [comment]
Hi @jdeisenberg,

Responded to you via email on this one, so we can discuss more specifically in relation to your project.

Sanders
