### ISSUE TITLE
Images too small

### ISSUE THREAD

**Issue by MikeW50** [MakerPress/atlas-public-feedback#382]
A small number of the images in http://ano-atlas2.herokuapp.com/books/1234000001734, Chapter 4 are showing up way smaller than the available column width. Search for the caption "Insert the four pins into the even numbered pin holes." to see one example; there are three more in the same area of the book.

What is the proper way to coax these images to be formatted to the full column width when building a PDF?

Thanks,

Mike

**Comment by DanGitOreilly** [comment]
Hi @MikeW50,

I took a look at the image files for a few of the images in chapter 4 that were not extending the full width of the column, and I noticed that the source images files were not as wide as many of the other images in your book. For example, the source image for Figure 4-79 is 1.6 inches wide at 300 dip, whereas a larger image, such as Figure 4-78, is 7 inches wide at 72 dpi. I think that if you resize the problematic images to a larger width, they will take up the full column width.
