### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by jezhumble** [MakerPress/atlas-public-feedback#384]
Chapter-4-01---Financial-Management.asciidoc in my project causes the PDF job to segfault.

**Comment by sarahs** [comment]
Hi @jezhumble,

It looks like the problem is occurring at the end of the sidebar "Financial Incentives with Positive Impact: The Case Of WestJet," specifically the three footnotes that are not appended to any text:

```
footnote:[http://www.westjet.com/pdf/greatWestJetJobs.pdf] footnote:[https://www.westjet.com/pdf/global-
reporting.pdf] footnote:[WestJet Management Discussion and Analysis of Financial Results 2013,
http://www.westjet.com/pdf/investorMedia/financialReports/WestJet2013-MDA.pdf]
```

If you move those footnotes up to the paragraph above, that should fix the error. Let us know if you run into any further trouble.

Thanks,
Sarah

**Comment by jezhumble** [comment]
Thanks very much! That fixes it.

On 8 April 2014 06:17, sarahs notifications@github.com wrote:

> Hi @jezhumble https://github.com/jezhumble,
> 
> It looks like the problem is occurring at the end of the sidebar
> "Financial Incentives with Positive Impact: The Case Of WestJet,"
> specifically the three footnotes that are not appended to any text:
> 
> footnote:[http://www.westjet.com/pdf/greatWestJetJobs.pdf] footnote:[https://www.westjet.com/pdf/global-
> reporting.pdf https://www.westjet.com/pdf/global-reporting.pdf] footnote:[WestJet Management Discussion and Analysis of Financial Results 2013,http://www.westjet.com/pdf/investorMedia/financialReports/WestJet2013-MDA.pdf]
> 
> If you move those footnotes up to the paragraph above, that should fix the
> error. Let us know if you run into any further trouble.
> 
> Thanks,
> Sarah
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MakerPress/atlas-public-feedback/issues/384#issuecomment-39845841
> .

## 

Jez Humble
Co-author, _Continuous Delivery http://continuousdelivery.com/_
http://continuousdelivery.com/
http://jezhumble.net/
