### ISSUE TITLE
atlas-server.oreilly.com/git not responding

### ISSUE THREAD

**Issue by MarkAYoder** [MakerPress/atlas-public-feedback#385]
I'm trying to do a _git pull_ on my book, but am getting no response.  Is it taking the weekend off?

--Mark

**Comment by sandersk** [comment]
Hi @MarkAYoder,

Sorry about that. We had an outage with our Git server, but it's just been fixed. Can you please try again now, and let us know if you still encounter any errors?

Thanks,
Sanders

**Comment by MarkAYoder** [comment]
It's back!  Thanks...

--Mark
