### ISSUE TITLE
linebreaks not always preserved in code listings in PDF generation

### ISSUE THREAD

**Issue by robe2** [MakerPress/atlas-public-feedback#386]
We are using docbook format for our book: PostgreSQL: Up and Running 2nd edition and using atlas. In some of our code listings, we are finding that the line breaks we have are not being preserved.  They get preserved fine in the chimera html output and 1st edition of our book (pdf done via old svn system) did preserve the line breaks for these specific examples.

http://atlas.labs.oreilly.com/books/1234000001776 

For example - our chapter 6 Example 6-8. Adding data to facts table.

Thanks,
Regina

**Comment by sandersk** [comment]
Hi Regina,

Would you be able to post a screenshot from the PDF illustrating the linebreaking problem? I took a look at the latest PDF generated in Atlas and compared the linebreaks in Example 6-8 in PDF against those in the source DocBook, and did not see any discrepancies, which makes me suspect it might be a font or PDF reader issue.

Thanks,
Sanders

**Comment by sandersk** [comment]
Oh, actually, please disregard my previous message. I was unaware another O'Reilly staffer is actively working on this. We'll follow up with you shortly.

Sanders

**Comment by zaremba** [comment]
Hi Regina,

We think we've fixed this issue now and your code listings should be breaking properly in the PDF.

Please let us know if you see any that haven't been corrected.

Thanks,
Adam
