### ISSUE TITLE
Index spanning a range appears to create two entries in Chimera 

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#387]
http://chimera.labs.oreilly.com/books/1234000000446/ix01.html ; see entries for "lineto (with path)" and "feSpecularLighting" as examples.

**Comment by zaremba** [comment]
Hi David,

Thanks for reporting this bug. We've confirmed it, and will work on getting a fix in place soon.

Thanks,
Adam

**Comment by sandersk** [comment]
Hi @jdeisenberg,

This should be fixed now. Let us know if you encounter any further issues.

Sanders
