### ISSUE TITLE
Disable hyphenation on code elements in ePub

### ISSUE THREAD

**Issue by clintongormley** [MakerPress/atlas-public-feedback#388]
Some text like this:

```
Avoid using <code class="literal">not_analyzed</code> fields in <code class="literal">multi_match</code> queries.
```

can render on ePub as:

Avoid using `not_analyzed` fields in `multi_-`
`match` queries.

Please disable hyphenation on `code` elements.

See https://github.com/elasticsearch/elasticsearch-definitive-guide/issues/49

**Comment by sandersk** [comment]
Hi @clintongormley,

Thanks for the feedback regarding hyphenation in EPUB output.  I'll pass this along to our design team so they can review our CSS and adjust if feasible. Please note that different EPUB ereading systems may have different behaviors around linebreaks and hyphenation, which may or may not be possible for us to override in CSS, but we will do our best to optimize as much as we can.

Best,
Sanders
