### ISSUE TITLE
PDF chapter footer mislabeled on some pages

### ISSUE THREAD

**Issue by robe2** [MakerPress/atlas-public-feedback#389]
We are using DocBook format on Atlas: http://atlas.labs.oreilly.com/books/1234000001776

and just noticed this issue so not sure if its a new issue or old one we never noticed before.  In the PDF generation, the chapter footer that shows from Page 8 (Chapter 1 thru Chapter 6) shows Chapter 7 and then on it seems right again.  Not sure if something we are doing wrong.

See snapshot:
![chapterfooter_mislabeled](https://cloud.githubusercontent.com/assets/4734450/2785370/02fd2d88-cb53-11e3-98c7-39ab1abd656a.png)

**Comment by sandersk** [comment]
Hi @robe2,

Thanks for letting us know. I took a look, and you're not doing anything wrong. The footer numbering issues are related to a bug in our PDF rendering software. 

For now, you can safely ignore. We will make sure this issue is corrected when the book is in Production.

Best,
Sanders
