### ISSUE TITLE
Can't scale images

### ISSUE THREAD

**Issue by josefprusa** [MakerPress/atlas-public-feedback#39]
I'm not able to scale images. They are always 100% wide, causing tall images to be gigantic. I tried width and scalewidth properties, but no luck.

Look here https://dl.dropbox.com/u/8967423/fail.png

**Comment by adamwitwer** [comment]
Thanks for the report. We're looking at adding better handling for images with the scaledwidth attribute.

For now, if you need to override an image width, you can use an absolute value in inches, e.g.,

```
images::filename.png[width="2in"]
```

**Comment by adamwitwer** [comment]
We've implemented this. Please reopen if you have problems.
