### ISSUE TITLE
Images not being displayed

### ISSUE THREAD

**Issue by clintongormley** [MakerPress/atlas-public-feedback#390]
Hiya

Images which were being displayed previously, are no longer showing up on Chimera. eg http://chimera.labs.oreilly.com/books/1230000000825/ch04.html#_how_primary_and_replica_shards_interact

**Comment by zaremba** [comment]
Hi @clintongormley, Chimera requires that your images be stored in a folder called images/, so if you change your directory from png/ to images/ and update your references accordingly, it should work.

Please let me know if this doesn't fix your problem!

Thanks,
Adam
