### ISSUE TITLE
Can't push git changes

### ISSUE THREAD

**Issue by aantonop** [MakerPress/atlas-public-feedback#391]
Trying to push my changes to Atlas and I'm getting a hangup without any error message or information as to why it is crashing:

```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v atlas master:master 
Pushing to https://andreas%40antonopoulos.com@atlas-server.oreilly.com/git/1234000001802.git
POST git-receive-pack (chunked)
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
Completed with errors, see above
```

**Comment by zaremba** [comment]
Hi @aantonop,

Please check out the second FAQ here:
http://chimera.labs.oreilly.com/books/1230000000065

I think increasing your HTTP POST buffer will solve this problem.

Please let us know if this doesn't work for you.

Thanks,
adam
