### ISSUE TITLE
It would be nice to automatically kick off a build whenever the git repo gets updated

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#393]
We clone the git repo and update it and then push our commit to the Atlas hosted remote git repo. However, it's rather cumbersome to then go to Atlas and issue a HTML5 build every time we do so. What's worse is some times we forget to do and so Chimera is out of sync with the asciidoc content in our repo.

What would be really nice for us is to have, say a checkbox, in Atlas somewhere we can enable an automatic kick off a Chimera build every time we push a change to the git repo. Is there something like that already?

**Comment by zaremba** [comment]
Hi @markgrover,

Thanks for the feedback. We've created functionality to trigger builds remotely for the newest version of Atlas (currently in beta). We expect it to become available later this year.

Thanks,
Adam
