### ISSUE TITLE
Images not displaying in build

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#394]
Hello -

In this project:

http://ano-atlas2.herokuapp.com/books/1234000002083

The images are not building correctly. See for example Page 7 of the PDF build.

This markup is not displaying the image correctly for some reason:

"""
image::images/right-implementation-quote.png["With the right implementation, a website can be both Responsive and Fast"]
"""

File located here:
http://ano-atlas2.herokuapp.com/books/1234000002083/versions/master/editor/Perf-And-RWD.asciidoc

There are several images that are not building correctly.

Thanks!

**Comment by christopappas** [comment]
Hi @bandersonoreilly,

I cloned down your repo and looked at the pdf and asciidoc files.  

I believe the image rendering issues in the pdf are a result of image files being referenced that are not in the /images directory.  The one image that did render in the pdf referenced an image file that <i>is</i> living in /images (the others image references in your asciidoc refer to images that are not in the repo).

I think a solution is to add to the /images directory any image files you wish to reference in your asciidoc files.  

Hope this helps,
Chris

**Comment by bandersonoreilly** [comment]
Thank you, Chris!
