### ISSUE TITLE
Syntax highlighting not showing up -- markup issue

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#396]
The code examples in this book are not getting highlighted; I'm sure it's an error in the markup but I can't figure it out.

Here's an example file:

http://ano-atlas2.herokuapp.com/books/1234000002083/versions/master/editor/Image-Over-Downloading.asciidoc

The offending markup:

"""
# .An example of using _srcset_
## [source,HTML]

<img src="banner.jpg" alt="Banner Ad" 
     srcset="banner-HD.jpg 2x, 
             banner-phone.jpg 100w, 
##              banner-phone-HD.jpg 100w 2x">
# 

"""

In the PDF build, the above code example is not getting highlighted.

**Comment by christopappas** [comment]
Hi @bandersonoreilly 

I believe the language name for HTML needs to be lowercase. 
Instead of:
`[source,HTML]`
Try:
`[source,html]`

Let me know if that doesn't fix it.

Thanks,
Chris

**Comment by bandersonoreilly** [comment]
Thanks Chris, I've forwarded to author.
