### ISSUE TITLE
commit messages and diff is missing öäüß .. and any other utf8 chars id atlas web

### ISSUE THREAD

**Issue by kaystrobach** [MakerPress/atlas-public-feedback#397]

**Comment by zaremba** [comment]
Hi @kaystrobach, can you give me the URL for the project where you're experiencing this?

**Comment by kaystrobach** [comment]
it's the non public system called atlas used by o`reilly
![image](https://cloud.githubusercontent.com/assets/1185776/3170837/afddade0-ebbd-11e3-8199-4cf3e19afc0f.png)

you will find some examples of missing special german umlauts in the screenshot attached

the uri scheme looks like that:

```
http://<hostname>/books/<booknumber>/versions/master/changes
```

**Comment by zaremba** [comment]
Hi @kaystrobach,

Thanks for the feedback here. We'll take a look at this and make sure we have broader support for UTF8 characters in future versions of Atlas.

Best,
Adam

**Comment by kaystrobach** [comment]
:thumbsup:
