### ISSUE TITLE
Corner asciidoc cases.

### ISSUE THREAD

**Issue by lookfwd** [MakerPress/atlas-public-feedback#398]
Hello, there are some chapters that I haven't processed for a while. They used to compile to bad pdf... now they look way better... I remember me and my editor tried quite a bit to get the .asciidoc to give the right output and still I can see some thing that are still unclear for me if they are right or not...

for  +process_item()+ , I get: process_item() instead of process_item() 
for _MONGODB_HOST_OR_IP_ I get: MONGODB_HOST_OR _IP instead of MONGODB_HOST_OR _IP
for _+X.X.X.X+_ I get: +X.X.X.X+ instead of X.X.X.X
for +__init__\+ I get:  **init__ instead of __init**

I mean what I see clearly is that probably when I have _ inside other markup - I should use just _ instead. For _MONGODB_HOST_OR_IP_ I have no clue what would be the right way to do it. The X.X. ... looks like _ and + markup can't be nested. Then **init** is just a mystery - I have no theory about it. 

Could you clarify what's the right format in the above cases?

Thanks a lot in advance.

**Comment by christopappas** [comment]
Hello @lookfwd,

Thanks for writing. If you could point me to where your project lives, I'd be happy to take a look for you to see what's going on.

Thanks,
Chris

**Comment by lookfwd** [comment]
Hello Chris,

my example comes from project 1230000000289, The-****il.asciidoc

Thanks a lot, 
Dimitris

**Comment by christopappas** [comment]
Hello @lookfwd,

Sorry for the delay. I'm fairly certain I've located the issues you are describing in your original post, please let me know if this isn't the case!

For the case of _+X.X.X.X+ , this example is the one just following a url, right? If so, to get the X.X.X.X to render in monospace and italics, you can use the following syntax in asciidoc:

```
_++X.X.X.X++_
```

For the case of __ init __, if you can use double '$' on each side of the string to render it as a text literal. In your case, you might use this in your asciidoc: 

```
$$__init__()$$
```

For the case of MONGODB_HOST_OR_IP with IP in italics and a space before it, I would do something like the following in the asciidoc code:

```
MONGODB_HOST_OR _IP_
```

For the case of process_item(), I wasn't sure I found an issue here. When I removed the escape "\" before the underscore in once instance of process_item(), it seemed to render in monospace normally.  

I would check out these two links if you get a chance. Lots of good info here:
http://www.methods.co.nz/asciidoc/userguide.html#X51
http://www.methods.co.nz/asciidoc/userguide.html#X77

Let me know if you have any other questions/if I didn't answer the ones you already asked.

Thanks,
Chris
