### ISSUE TITLE
Multiple paragraphs in callouts

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#399]
I am attempting to have more than one paragraph in the description of a callout, but asciidoc doesn't like me, even when I use + to indicate a new line. Is there an easy solution for this?

```
<1>This is part of the explanation of callout one.
+
And this is more of it
```

**Comment by christopappas** [comment]
Hi @jdeisenberg 

Thanks for writing. If you could point me to where your project lives, I'd be happy to take a look for you to see what's going on.

Thanks,
Chris

**Comment by jdeisenberg** [comment]
http://atlas.labs.oreilly.com/books/1234000000446 , ch10.asciidoc, approximately line 800.

**Comment by christopappas** [comment]
Hello @jdeisenberg 

Adding an extra line of whitespace after "Or maybe even a third one."  should do the trick. Should look something like this:

```
+
This is where a second paragraph would go.
+
Or maybe even a third one.

<10> The...
```

With the above syntax I was able to generate the pdf with the numbered list continuing at 10. 

Let me know if you have any other questions.
Thanks,
Chris

**Comment by jdeisenberg** [comment]
On Thu, Jun 5, 2014 at 2:36 PM, christopappas notifications@github.com
wrote:

> Hello @jdeisenberg https://github.com/jdeisenberg
> 
> Adding an extra line of whitespace after "Or maybe even a third one."
> should do the trick. Should look something like this:
> 
> +
> This is where a second paragraph would go.
> +
> Or maybe even a third one.
> 
> <10> The...
> 
> With the above syntax I was able to generate the pdf with the numbered
> list continuing at 10.
> 
> Let me know if you have any other questions.

Thanks; I'll give it a try and see how it works.

Thanks,
