### ISSUE TITLE
Builds seem to use old content

### ISSUE THREAD

**Issue by JohnGarbutt** [MakerPress/atlas-public-feedback#40]
If I save a change and press build within the next few mins, it seems to build using the older revision of my changes.

After waiting an hour, it certainly picks up the new changes.

**Comment by sandersk** [comment]
Hi John,

I suspect that your browser may be caching the older PDF file. Could you try hitting Refresh when accessing the PDF URL, and let me know whether that solves the problem?

Thanks,
Sanders

**Comment by JohnGarbutt** [comment]
Hi it seems to be working now. I didn't realize the URL didn't change between builds, and the builds page seems to reflect that better now. I know S3 doesn't always guarantee that you get the latest copy of an object, so it could have been partly that too.

**Comment by sandersk** [comment]
Great, glad to hear you're able to get the latest files now. I'll close this ticket, but please let us know if you encounter any further issues.

Best,
Sanders
