### ISSUE TITLE
Printed book vs. e-book ability to generate

### ISSUE THREAD

**Issue by robe2** [MakerPress/atlas-public-feedback#401]
In the old subversion model we had the ability to generate two PDF versions.  One used for the printed book and one used for online viewing.  With differences like the printed book had hyperlinks displayed and the site titles italicized.  Is there such a thing in atlas version.  I presume when it goes to final print we will see the hyperlinks etc. listed as we did in first edition of our book?

**Comment by zaremba** [comment]
Hi @robe2 

Yes, both versions will still be produced. Your production editor will be able to provide them to you for review once your book has entered production.

Thanks,
Adam
