### ISSUE TITLE
Stuck builds on Getting Started with Sensors

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#402]
Hi,

Could you have a look at http://ano-atlas2.herokuapp.com/books/1234000000778? The authors have been trying to build, but none of the builds are completing.

Thanks,

Brian

**Comment by zaremba** [comment]
Hi @bjepson,

Thanks for letting us know. It looks like the v1 drive filled up over the weekend. We've fixed that problem, but it looks like there are some invalidities in the files that need to be cleaned up:
http://ano-atlas2.herokuapp.com/books/461/jobs/60415

If you fix those, you should be able to generate successfully.

Thanks,
Adam
