### ISSUE TITLE
Did the Git URLs change overnight?

### ISSUE THREAD

**Issue by patrickdijusto** [MakerPress/atlas-public-feedback#404]
As of this morning, I'm getting a 443 error when I try to push or pull changes. Did something in Atlas change overnight?

**Comment by sandersk** [comment]
Hi @patrickdijusto,

Can you point us to the URL of the book you're working on. We'll take a look.
Sanders

**Comment by patrickdijusto** [comment]
Thank you!

All of these URLs were working yesterday.  Today, they all return 443
errors, whether pulling or pushing:

https://patrick%40dijusto.com@atlas-server.oreilly.com/git/1234000000318.git

https://patrick%40dijusto.com@atlas-server.oreilly.com/git/1234000002061.git

https://patrick%40dijusto.com@atlas-server.oreilly.com/git/1230000000897.git

https://patrick%40dijusto.com@atlas-server.oreilly.com/git/1230000000465.git

https://patrick%40dijusto.com@atlas-server.oreilly.com/git/1234000002102.git

https://patrick%40dijusto.com@atlas-server.oreilly.com/git/1234000000118.git

**Comment by zaremba** [comment]
Hi @patrickdijusto,

Can you post the whole error you see when you try to push or pull? I'm able to clone these down without problem.

Thanks,
Adam

**Comment by patrickdijusto** [comment]
It seems to be fixed now.  I have no idea what changed.

**Comment by zaremba** [comment]
OK; great. Let us know if you run into this problem again.

Thanks,
Adam
