### ISSUE TITLE
book.asciidoc not persisted on build failure

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#405]
If I update book.asciidoc file via the web interface but say, don't remember to click any of the 4 checkboxes (PDF, HTML5, etc.), I am going to get an error stating that I should select one of them, which is fine. The sad part is that my changes to book.asciidoc disappear and it reverts back to it's original state. If these changes were non-trivial, it's very painful to drag and drop again, just because I forgot to click a checkbox.

**Comment by zaremba** [comment]
Hi @markgrover 

Thanks for this feedback. We're working on implementing a "save settings" check for the new version of Atlas, which will hopefully fix this problem.

Thanks,
Adam
