### ISSUE TITLE
Consider having default selection for "New Build" checkboxes

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#406]
There are checkboxes for PDF, HTML5, etc. when building. However, by default, they are all unchecked. It would be great to have something by default there. Few options that I can think of at the top of my head, but I will let you folks make the call:
1. Have hard-coded defaults, e.g. PDF is always checked.
2. Pre-check what was used in the last build.
3. Have a feature that allows users to set up a default build "profile". Profile just being a fancy word for what outputs to build.

**Comment by zaremba** [comment]
Hi @markgrover,

Thanks for this feedback! I'll bring this up with the team and see what's possible. I think option 2 is the most likely.

Thanks,
Adam
