### ISSUE TITLE
Getting 500 error on generting html version

### ISSUE THREAD

**Issue by robe2** [MakerPress/atlas-public-feedback#407]
Just tried to generate an html version of our docbook on atlas and got this error:

Error 
  java.io.IOException: Server returned HTTP response code: 500 for URL:

  http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd

Transformation failed: Run-time errors were reported

That file does seem to be accessible so perhaps is a sub doc.  It might be an oasis issue though since I was starting to get docbook errors on a non-O'Reilly project I was working on today.

**Comment by simonstl** [comment]
Same issue here!

**Comment by jonlives** [comment]
I'm also seeing this issue

**Comment by robe2** [comment]
Yah I'm pretty sure it's because OASIS site is broken.  I looked at the other error I was getting on my other project that uses docbook it couldn't download the dtd and went to the link:
( ticketed here: http://trac.osgeo.org/postgis/ticket/2792 )

and gave
"The service is temporarily unavailable. Please try again later."

As a work-around for that one I had to disable the validation step (xmllint call).  

I think there is a way for it to use a local dtd (since our project's debian bot is not having this problem so must be using its own local dtd), but couldn't figure that out. So I presume the better fix is to use a local dtd (espciecially if oasis throws an error) rather than pulling from oasis all the time.

**Comment by sandersk** [comment]
Hi all,

Apologies for the inconvience. Yes, I just tested, and HTML builds are back up and running on Atlas now, as the OASIS site is back up. To avoid these sorts of issues in the future, we'll update our build system to use local catalogs and eliminate dependencies on the OASIS site.

Sanders
