### ISSUE TITLE
MOBI not building; SVG doesn't display in EPUB

### ISSUE THREAD

**Issue by jezhumble** [MakerPress/atlas-public-feedback#409]
Hi there.
I am trying to publish a new draft of my book: http://ano-atlas2.herokuapp.com/books/1234000001599 including vector images this time. SVG looks good in pdf format, but it won't display in epub, and mobi is not building at all (also, nothing is building at all just at the moment because it appears the server ran out of disk space)
Is svg the best vector format to use? I can produce eps if that's preferred. I'm using Omnigraffle for documents.

**Comment by zaremba** [comment]
Hi @jezhumble,

Thanks for letting us know about this. We've cleaned up the disk and builds should be working again.

Vector images aren't well supported across EPUB and Mobi readers; our policy at O'Reilly is to use high resolution png or jpeg files. Are you able to output your images in these formats?

Thanks,
Adam

**Comment by jezhumble** [comment]
I am. What are your recommendations for size / resolution?

On 7 July 2014 11:57, zaremba-oreilly notifications@github.com wrote:

> Hi @jezhumble https://github.com/jezhumble,
> 
> Thanks for letting us know about this. We've cleaned up the disk and
> builds should be working again.
> 
> Vector images aren't well supported across EPUB and Mobi readers; our
> policy at O'Reilly is to use high resolution png or jpeg files. Are you
> able to output your images in these formats?
> 
> Thanks,
> Adam
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MakerPress/atlas-public-feedback/issues/409#issuecomment-48224179
> .

## 

Jez Humble
Co-author, _Continuous Delivery http://continuousdelivery.com/_
http://continuousdelivery.com/
http://jezhumble.net/

**Comment by zaremba** [comment]
Hi @jezhumble,

From the illustrators:
For the Lean series, a minimum dpi of 150 and a preferred dpi of 326 for drawings, and 4.5x7 inches maximum artboard.
