### ISSUE TITLE
Not able to access a book as contributor

### ISSUE THREAD

**Issue by myarbrough** [MakerPress/atlas-public-feedback#41]
Hello!

I'm the production editor on Surviving Orbit the DIY Way, but I get an error when trying to access the files. 

Thanks,
Melanie Yarbrough

**Comment by sandersk** [comment]
Hi Melanie,

Sorry, we've been experiencing some technical difficulties with Atlas this morning. We're looking at this issue right now, and I'll let you know as soon as it's back up.

Sanders

**Comment by staffordvaughan** [comment]
I'm having problems on my book http://ano-atlas2.herokuapp.com/books/1230000000581 as well. Getting an error 500.

**Comment by sandersk** [comment]
Hi Melanie and Stafford,

Atlas is back up now, but we're still debugging some intermittent connectivity issues that we've been experiencing this morning. Please let me know if you encounter any further problems.

Thanks for your patience,
Sanders

**Comment by staffordvaughan** [comment]
Working a lot better for me now. Thanks!
