### ISSUE TITLE
Another failed build

### ISSUE THREAD

**Issue by bandersonoreilly** [MakerPress/atlas-public-feedback#411]
This book:

http://ano-atlas2.herokuapp.com/books/1234000001849

Fails to build (with this error):

http://ano-atlas2.herokuapp.com/books/869/jobs/62131

Is it trivial to clean up? I can ask the author to make some changes, if that helps.

**Comment by christopappas** [comment]
Hello @bandersonoreilly 

The table at line 679 of ch02.asciidoc is the culprit. The bottom table delimiter, at line 687, has an extra space after the `|====`.

Removing the space should resolve the issue. Let me know if there are any other questions.

Thanks,
Chris

**Comment by bandersonoreilly** [comment]
Thanks Chris!

On Thu, Jul 10, 2014 at 5:12 PM, christopappas notifications@github.com
wrote:

> Hello @bandersonoreilly https://github.com/bandersonoreilly
> 
> The table at line 679 of ch02.asciidoc is the culprit. The bottom table
> delimiter, at line 687, has an extra space after the |====.
> 
> Removing the space should resolve the issue. Let me know if there are any
> other questions.
> 
> Thanks,
> Chris
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MakerPress/atlas-public-feedback/issues/411#issuecomment-48665155
> .

## 

Brian Anderson
Development Editor
O'Reilly Media, Inc.
@branderlog
