### ISSUE TITLE
PDF build failing: No space left on device error

### ISSUE THREAD

**Issue by tcoffeen** [MakerPress/atlas-public-feedback#412]
Hello,

Thanks for taking a look.

Best,

Tom

Project: https://ano-atlas2.herokuapp.com/books/1234000002048

PDFJob
Failed at 2014-07-11 02:44:47 UTC

Job failed
Full error:

No space left on device - /tmp/systemu_atlas-worker_7021_7024_0.26559061087870417_1

**Comment by harishreedharan** [comment]
HTML builds are failing too: 

No space left on device - /tmp/systemu_atlas-worker_15482_15485_0.9841603098854182_1

**Comment by zaremba** [comment]
Hi @tcoffeen and @harishreedharan,

Thanks for reporting this and sorry for the inconvenience. We believe we've fixed the issue and builds should be working again, but please let us know if you experience any further problems.

Thanks,
Adam
