### ISSUE TITLE
Conflict in epub: literal vs. emphasis in CSS

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#413]
This asciidoc:

```
+_Constant width italic_+:: Is used for replaceable elements in code examples
```

Expands to this HTML in the epub document:

```
<dt><span class="term">
<span class="emphasis"><em><code class="literal">Constant width italic</code></em></span>
</span></dt><dd>
Is used for replaceable elements in code examples.
```

The core.css file gives this definition:

```
dt span.term code.literal {
  font-style: normal; 
  font-weight: normal; 
}
```

the  `font-style: normal`means that the words "Constant width italic" don't show up in italic in an ePub reader.

**Comment by sandersk** [comment]
Thanks for reporting this bug, @jdeisenberg. We'll take a look and make sure we get it fixed.

Sanders

**Comment by slynchoreilly** [comment]
I've added in handling for the literal class that is supposed to be italic.

em code.literal {
  font-style: italic;
}

Once we merge this change, it should work
