### ISSUE TITLE
Forced line breaks go away during build.

### ISSUE THREAD

**Issue by jdeisenberg** [MakerPress/atlas-public-feedback#414]
The following markup:

```
*Properties:* +
+unitType+: one of the constants defining allowed units; +
+value+: the length in user units; +
+valueInSpecifiedUnits+: the length in +unitType+ units; +
+valueAsString+: the value and units together as a string.
```

shows each of the properties on a separate line when I use a standalone version of asciidoc on my computer at home. When I build it in Atlas (http://atlas.labs.oreilly.com/books/1234000002157) the line breaks go away.  This happens whether the markup is inside a table,where it belongs, or outside, where I moved it just to test if it was a "table thing."

**Comment by christopappas** [comment]
Hello @jdeisenberg 

Thanks for writing. Unfortunately, we do not support Asciidoc's native linebreaking mechanism. In fact, we ask that you not worry about hard linebreaks at all, as they are taken care of later in production.

That said, it seems like what you are trying to achieve here is a variable list (general reference found here: http://chimera.labs.oreilly.com/books/1230000000065/ch04.html#Lists). To achieve this type of layout in a table though, you need to use special table settings:

```
[cols="default, default, asciidoc",options="header"]
```

Your variable list would be in the third column, which has the "asciidoc" style, which allows the variable list markup to be processed in that column. See http://www.methods.co.nz/asciidoc/userguide.html#X71 for more information.

You will also need to add an extra blank line wherever paragraph breaks are desired.

For example, your table markup might look something like:

```
[cols="default, default, asciidoc",options="header"]
|=================
|Object Name |Description          |Properties and Methods
|+SVGLength+ |A length with units.

The units are defined as constants of the form +SVGLength.SVG_LENGTHTYPE__\_unit__+, where _unit_ is one of +NUMBER+ (for user units), +PERCENTAGE+, +EMS+ (em units), +EXS+ (ex units), +PX+, +CM+, +MM+, +IN+, +PT+, +PC+. 

|*Properties*:

+unitType+:: One of the constants defining allowed units.
+value+:: The length in user units.
+valueInSpecifiedUnits+:: The length in +unitType+ units.
+valueAsString+:: The value and units together as a string.

*Methods:*

+newValueSpecifiedUnits( _unitType_, _valueInSpecifiedUnits_)+:: Sets the value and the units.
+convertToSpecifiedUnits( _unitType_ )+:: Change the unit type, while maintaining the same value in user units.
|=================
```

This will produce a table with the variable list in the third column to display the terms/definitions you have included above. I'm attaching a screenshot that shows a preview of the rendering.
![variable_list_table](https://cloud.githubusercontent.com/assets/7385292/3630500/e2220f42-0eab-11e4-8564-2914828fbeb1.png)

Let me know if you have any questions.

Thanks,
Chris
