### ISSUE TITLE
Cannot login into new Atlas

### ISSUE THREAD

**Issue by harishreedharan** [MakerPress/atlas-public-feedback#415]
The Atlas online interface shows that my files have been moved to the new Atlas, but I cannot seem to login using the email id I used with the old atlas. On trying to reset password, I get a message that the email id was not found.

**Comment by zaremba** [comment]
Hi @harishreedharan,

The credential and authentication systems are completely separate for the newer version of Atlas, so you'll need to create a new account in the new version, though you can use the same email/password if you like.

Can you tell me what book you were looking for that has been moved?

Thanks,
Adam

**Comment by christopappas** [comment]
Hello @harishreedharan 

Your book has entered production and is in the process of being moved over to the newer version of Atlas. We'll circle back with you in the next day or so to give you access to the new project, as well as how to log in. 

Thank you for your patience,
Chris

**Comment by harishreedharan** [comment]
@zaremba-oreilly @christopappas Thanks!

**Comment by harishreedharan** [comment]
How do I get a login for the new Atlas and to the book on that?
