### ISSUE TITLE
Images served over https are not in build when using Markdown

### ISSUE THREAD

**Issue by kartben** [MakerPress/atlas-public-feedback#418]
In a .md file, if you have the following:

```
![https](https://www.google.com/images/srpr/logo11w.png)
![http](http://www.google.com/images/srpr/logo11w.png)
```

Only the http version of the image shows up in the PDF and EPUB builds

However, the MOBI build fails altogether, which makes me wonder if maybe external images aren't supported, in the end – which would sort of make sense to make sure book repos are self-contained.

```
ERROR Unable to copy file logo11w.png into EPUB: [Errno 2] No such file or directory: 'https://www.google.com/images/srpr/logo11w.png'
ERROR Unable to copy file logo11w.png into EPUB: [Errno 2] No such file or directory: 'http://www.google.com/images/srpr/logo11w.png'
```

**Comment by zaremba** [comment]
Hi @kartben,

You're right that Atlas does not support the use of external images in book projects. The illustration department requires that all resources be loaded to the project, so please load any images you wish to use to the repo.

Thanks,
Adam
