### ISSUE TITLE
Atlas editor overwrites without warning

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#419]
Something really bad happened to us. One of the authors was editing something on Atlas's online editor for a long time. In the meantime, another author edited the file locally and committed & pushed his changes to the atlas git repo. When the first author saved his changes, Atlas did a very aggressive merge and essentially overwrote a bunch of changes from the second author's commit.

There needs to be a good merge framework for Atlas editor, I think that is a non-starter for using the editor for any projects involving multiple people editing the same file at the same time.

**Comment by zaremba** [comment]
Hi @markgrover,

Sorry to hear about your difficulty here. We have a newer beta version of Atlas with collaboration features built in that we hope will help address issues like this one. However, it's still best practice for project collaborators to coordinate their work to minimize potential conflicts.

Thanks,
Adam

**Comment by markgrover** [comment]
Thanks Adam. I respectfully disagree. I think on a project with multiple people contributing at the same time, it's almost impractical to coordinate when commits go in. And, I think, that's rather the point of having a version control system and a distributed one like git, so people don't have to.

In any case, I am, and I am sure other Atlas users are, looking forward to the newer beta release! However, I still think the auto merge policy of the current Atlas version is very aggressive and should be re-considered, if possible, regardless of what the new Atlas beta contains.

**Comment by sandersk** [comment]
Hi @markgrover,

We are not doing any further development work on the current version of Atlas that you are using. If you and your co-authors are interested in moving your project over to the new Atlas beta, which has support for distributed version control built into the Web UI, please let us know, and we'll check with Editorial/Production on whether it will be feasible to port your project over.

Best,
Sanders

**Comment by markgrover** [comment]
Thanks Sanders. We have moved to not using the Atlas built-in editor for now and that's working well. So, we are fine for now but will let you know if anything changes. Thanks again.
