### ISSUE TITLE
Build failed due to suspected Git checkout problem

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#42]
See the full email correspondence below for details on how the bug manifested and was resolved, but here's the quick summary:

PDF, EPUB, and Mobi Builds for 1230000000485 were stuck on "Pending" permanently, and checkouts in the /tmp dirs on gotham were not updating. Blowing away the checkouts in the /tmp dirs and then retriggering the builds resulted in fresh /tmp checkouts on gotham and successful ebook builds. This leads us to believe the issue here was something to do with the Git API.
## EMAIL THREAD BEGINS HERE

Was able to sort this one out with Adam. I noticed when queueing up a build that when I looked at the resque queue, the workers here weren't registering a new job for PDF, EPUB, or Mobi. So I went onto gotham and looked at the tmp checkouts for the book, and noticed they weren't getting updated either (even though file permissions looked totally fine). So I renamed the tmp directories, and then triggered a build again. This time, fresh checkouts were created on Gotham, and the builds succeeded.

So, Adam and I think there was something wrong with the Git API piece that was preventing the checkouts from being updating, and halting the Build from even starting. I figured we'd probably want to look into this further, so I preserved a couple of the bum checkouts that couldn't be updated here:

/home-local/worker/tmp/pdf/1230000000485_debug
/home-local/worker/tmp/mobi/1230000000485_debug

I'm going to file a formal Atlas ticket for this, so we can address, but the good news is that the immediate problem with 1230000000485 is now fixed.

Thanks,
Sanders

On Aug 8, 2012, at 4:11 PM, Adam Witwer wrote:

Hey, it's not at all urgent, but when you guys get a chance, can you take a quick look at this project?

http://ano-atlas2.herokuapp.com/books/1230000000485

The builds are failing on a single chapter (Prelude.asciidoc), and the file is completely vanilla. When I try to build a PDF on gotham, it works perfectly fine with no problems. I don't get why the Atlas builds are failing and I feel like I must be missing something really obvious.

**Comment by sandersk** [comment]
We now suspect the author's hacks to work on different branches of the book (he's modifying the atlas URLs to sub in the branch name instead of master) may be the culprit with the Git API checkout update problem. More context from Adam:

"""
Not sure what he's doing, but I think it's something to do with the branching. The git checkout in the workers get themselves in a twist and they won't build and return a PDF. I was able to fix the PDF build by logging onto gotham and deleting this dir entirely:

/home-local/tmp/pdf/1230000000485

When I rebuilt, the dir was cloned down and built successfully: http://atlas.labs.oreilly.com/books/1230000000485

But the HTML worker is exhibiting the same problem. This is the second time it has happened to this author, so I'd thought I'd call it out for you guys.
"""

**Comment by runemadsen** [comment]
Thanks guys, I'll look into this. Are we seeing this on other books than this book? I'm getting these errors for the book in the resque que:

`From atlas-admin.oreilly.com:1230000000485 63a437c..405c618 master -> origin/master *** Please tell me who you are. Run git config --global user.email "you@example.com" git config --global user.name "Your Name" to set your account's default identity. Omit --global to set the identity only in this repository. fatal: empty ident <worker@html-worker.(none)> not allowed`

It seems like some of the errors in the book is git not knowing the identity of the user.

**Comment by runemadsen** [comment]
Were you seeing this on all the builds, or just on the HTML worker? Because
I haven't deployed the new code to the other workers yet, so it's only the
HTML worker that is actually doing the "git checkout". I'm looking into the
logs right now, but whatever you can tell me about the problem, I'd be
happy to read :-)

On Sun, Aug 19, 2012 at 8:19 AM, Sanders Kleinfeld <notifications@github.com

**Comment by adamwitwer** [comment]
Hi Rune,

This was happening on the PDF and HTML worker. I fixed the problem with the PDF worker by nuking the checkout within the worker and rebuilding. This happened twice on the PDF worker, and for this book ONLY. I haven't seen this happen for any other project.

**Comment by runemadsen** [comment]
Thanks Adam, that's good to know. I SSH'ed into the HTML-WORKER machine, and tried to do a git pull. I got this again:

```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident  <worker@html-worker.(none)> not allowed
```

I added a default user and email to the worker machine, and the git pull was successful. I'm not sure whether this was the problem, but at least it fixed the errors I'm seeing in the logs. Otherwise I can't see anything weird with the repo, so let me know if this comes up again.
