### ISSUE TITLE
Single-quote / apostrophe handling

### ISSUE THREAD

**Issue by ramalho** [MakerPress/atlas-public-feedback#424]
Atlas cannot presently handle the following paragraph (ignore the ######):
###### 

The book Beautiful Code (O'Reilly) has a chapter titled "Python s Dictionary Implementation: Being All Things to All People" with a detailed explanation of the inner workings of the Python `dict`, written by A. M. Kuchling -- a Python core contributor and author of many pages of the official Python docs and how-tos. Also, there are lots of comments in the source code of the CPython http://hg.python.org/cpython/file/tip/Objects/dictobject.c[`dictobject.c` module]. Brandon Craig Rhodes' presentation http://pyvideo.org/video/276/the-mighty-dictionary-55[The Mighty Dictionary] is excellent and shows how hash tables work by using lots of slides with... tables!
###### 

The problem seems to be related to some evil interaction between the AsciiDoc parser and code that changes some ASCII characters into fancier left/right single quotations marks. I've tried to rewrite the first sentence of that paragraph multiple times using variations of the characters below without success. 

' 39 U+0027 APOSTROPHE
` 96 U+0060 GRAVE ACCENT
´ 180 U+00b4 ACUTE ACCENT
‘ 8216 U+002018 LEFT SINGLE QUOTATION MARK
’ 8217 U+002019 RIGHT SINGLE QUOTATION MARK

Full error message:

PDFJob

Failed at 2014-10-13 16:22:38 UTC
Job failed

Full error:

DCPS Error Log

/usr/local/app/worker/tmp/pdf/1234000001884/book.xml
== Error 1

/usr/local/app/worker/tmp/pdf/1234000001884/book.xml:4350: parser error : Opening and ending tag mismatch: ulink line 4350 and literal

---

<simpara>The book Beautiful Code (O&#8217;Reilly) has a chapter titled "Python s Dictionary Implementation: Being All Things to All People" with a detailed explanation of the inner workings of the Python &#8216;dict<literal>, written by A. M. Kuchling&#8201;&#8212;&#8201;a Python core contributor and author of many pages of the official Python docs and how-tos. Also, there are lots of comments in the source code of the CPython <ulink url="http://hg.python.org/cpython/file/tip/Objects/dictobject.c"></literal>dictobject.c` module</ulink>. Brandon Craig Rhodes&#8217; presentation <ulink url="http://pyvideo.org/video/276/the-mighty-dictionary-55">The Mighty Dictionary</ulink> is excellent and shows how hash tables work by using lots of slides with&#8230; tables!</simpara>

---

== Error 4

/usr/local/app/worker/tmp/pdf/1234000001884/book.xml:4350: parser error : Opening and ending tag mismatch: literal line 4350 and ulink

---

<simpara>The book Beautiful Code (O&#8217;Reilly) has a chapter titled "Python s Dictionary Implementation: Being All Things to All People" with a detailed explanation of the inner workings of the Python &#8216;dict<literal>, written by A. M. Kuchling&#8201;&#8212;&#8201;a Python core contributor and author of many pages of the official Python docs and how-tos. Also, there are lots of comments in the source code of the CPython <ulink url="http://hg.python.org/cpython/file/tip/Objects/dictobject.c"></literal>dictobject.c` module</ulink>. Brandon Craig Rhodes&#8217; presentation <ulink url="http://pyvideo.org/video/276/the-mighty-dictionary-55">The Mighty Dictionary</ulink> is excellent and shows how hash tables work by using lots of slides with&#8230; tables!</simpara>

---

**Comment by christopappas** [comment]
I'm working with @ramalho via RT, so I'm closing this issue.
