### ISSUE TITLE
Atlas HTML build failing with oasis-open.org related exceptions

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#425]
Our build job this morning failed with the following error:
HTMLJob
Failed at 2014-11-04 15:55:24 UTC

Job failed
Full error:

Error 
  java.net.UnknownHostException: www.oasis-open.org
Transformation failed: Run-time errors were reported

ping www.oasis-open.org from my box seems to be passing though.

**Comment by markgrover** [comment]
This has happened more than once, btw.

**Comment by runemadsen** [comment]
Mark, have you tried adding `http://` to that URL?

**Comment by sandersk** [comment]
Hi @markgrover,

Sorry for the inconvenience. Builds are succeeding now. There was an outage earlier of the OASIS site, which our build system depends on.

Let us know if you encounter further issues.

Thanks,
Sanders
