### ISSUE TITLE
BUILD tool doesn't build the specific asciidoc files I feed it

### ISSUE THREAD

**Issue by mifga** [MakerPress/atlas-public-feedback#426]
Please warn me if I'm overlooking something, but this process has changed for me suddenly from what I experienced before. 

when I add multiple asciidoc files (each at the == chapter level) to build from my project, when I check back the version I create for chimera or for PDF features the wrong chapter! (And an early version of a chapter that I've already pulled from the repo.)

Is there an admin console or similar I should be checking that is logging errors to let me know what is happening?

thanks!
matt

**Comment by christopappas** [comment]
Hello @mifga 

Could you point me to your project? I can have a look to help figure out what's going on.

Thanks,
Chris
