### ISSUE TITLE
Support git submodules

### ISSUE THREAD

**Issue by lorin** [MakerPress/atlas-public-feedback#427]
I have some source files in a separate (public) git repository I'd like to include. For example, I have a repository at  http://github.com/lorin/ansible-mezzanine. I tried to create a git submodule that points to this, and then include a source file like this:

```
.mezzanine.yml
====
----
include::ansible-mezzanine/mezzanine.yml[]
----
====
```

Unfortunately, that doesn't seem to work.

**Comment by sandersk** [comment]
Thanks for the suggestion, @lorin. At present, we don't support submodules for book projects, but that's something we are evaluating for the future.

For now, we would recommend keeping a copy of the source files in your Atlas project and keeping them in sync with the files on GitHub.
