### ISSUE TITLE
Add functionality to link to a particular commit in Atlas

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#429]
Currently we have the functionality to display changes (i.e. commits to the git repo) in Atlas:
http://ano-atlas2.herokuapp.com/books/<book_id>/versions/master/changes

However, we can't link to a particular change, just a link to all changes.

Github, for example, allows you to link to a particular commit:
https://github.com/apache/hadoop-common/commit/42a61a4fbc88303913c4681f0d40ffcc737e70b5

Can we add something similar to Atlas please?

And, on a related note, given that the book is stored in a git repo, why not expose the repo on a custom internal O'Reilly github instance?

**Comment by sandersk** [comment]
Thanks for the feedback and suggestions, @markgrover. Regarding change links, I'll pass your feedback along to the development team, as we're in the process of updating the version-history functionality in the new Atlas app.

Regarding your second suggestion, we have our own custom Git server for Atlas content, and do not have any plans at this time to expose Atlas repos on an internal GitHub instance. However, authors can certainly  push/pull their projects to their own GitHub repos if they'd like to sync their content to GitHub.

Hope this info is helpful,
Sanders
