### ISSUE TITLE
Delete files and images

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#43]
I created a file that I'm not going to be using anymore. Is there any way to delete it? I also have some image attachments that are redundant and I'd like to get rid of them.

**Comment by sandersk** [comment]
Hi Stafford,

Sorry, at this time, we don't have a mechanism in the Atlas Web UI to delete images that have been uploaded. But we're currently working on some enhancements to our image handling, and will add this request to the list.

In the meantime, having extraneous images uploaded shouldn't cause any problems in your ebook builds. As long as the extra images are not referenced in the text files, they won't be displayed in the ebook files.

Best,
Sanders

**Comment by adamwitwer** [comment]
Just wanted to add that you can delete files via git.

**Comment by nelliemckesson** [comment]
:+1:
