### ISSUE TITLE
Images not being displayed when built

### ISSUE THREAD

**Issue by stevenpoitras** [MakerPress/atlas-public-feedback#430]
Hi --

When I build my .PDF or epub the images aren't being rendered.. In the preview everything looks fine and the images are there.  Any thoughts?  (Just started using this today)

![image](https://cloud.githubusercontent.com/assets/8264175/5639628/b5249aa0-95ce-11e4-976f-ab4d94209e64.png)

**Comment by sarahs** [comment]
Hi @stevenpoitras,

Would you mind pointing me to your project? I'll take a look and see what's going on with the images.

Thanks,
Sarah

**Comment by stevenpoitras** [comment]
Hey @sarahs ,

Here's the link to my project: https://atlas.oreilly.com/spoitras/the-nutanix-bible/

**Comment by stevenpoitras** [comment]
Figured out the issues the src for some images had "/images/..." instead of "images/..." which works in the editor but not for the build.

Thanks!
