### ISSUE TITLE
Per-author git Branches on Repositories

### ISSUE THREAD

**Issue by holdenweb** [MakerPress/atlas-public-feedback#431]
##### One Author's Build Overwrites Another's

It would be useful if, when my co-author built her chapters, that didn't change my build too. At present it seems we have to drag chapters around a bit if someone else has been working on the book (as, I imagine, do they).

Given that Atlas is based on git, could we perhaps find some way of retaining at least a branch-per-author in the repository. This will also allow more effective use of distributed version control. Then I can happily build from my branch, my co-authors can build from theirs, and we can trade pull requests to incrementally improve our materials.

**Comment by zaremba** [comment]
Hi @holdenweb,

Thanks for this feedback. We're in the process of building out a newer version of Atlas that allows users to create branches and configure/kick off builds on that branch without affecting the settings of master or other branches.

Thanks,
Adam
