### ISSUE TITLE
BUILD page improvements

### ISSUE THREAD

**Issue by aleaxit** [MakerPress/atlas-public-feedback#432]
The BUILD page (on my Chrome browser) keeps a turning "pending" indication 'forever'; i.e, I need to keep manually refreshing the page to see when the formatting is finished.  An AJAX trick to refresh that indication would be much more handy to have -- "death to polling"!-)

The BUILD page indicates timing of latest builds as "about XX [minutes|hours] ago".  It would be VERY helpful to _also_ have a specific timestamp there in whatever format -- ISO 8601-ish would be fine, e.g 2015-01-18T18:31:50Z or whatever (no need for complication with timezones, AM/PM, &c).  TWO timestamps, one each for START and END of build (once the build is done or errored out) would be gravy and VERY welcome!-)

**Comment by sandersk** [comment]
Thanks for the feedback, @aleaxit. We've indeed implemented Ajax automatic status indicator updates in our new Atlas beta. If you're interested in switching the book to use the beta version, please let your editor know, and we can discuss further.

I'll pass your suggestions regarding timestamps to our product team, so that we can consider them for future releases of Atlas.

Sanders

**Comment by aleaxit** [comment]
On Mon, Jan 19, 2015 at 3:16 PM, Sanders Kleinfeld <notifications@github.com

> wrote:
> 
> Thanks for the feedback, @aleaxit https://github.com/aleaxit. We've
> indeed implemented Ajax automatic status indicator updates in our new Atlas
> beta. If you're interested in switching the book to use the beta version,
> please let your editor know, and we can discuss further.

Thanks, CC'ing said editor (and my two co-authors in case they're not that
enthusiastic about a beta, they clearly get veto rights:-) to further the
discussion.

> I'll pass your suggestions regarding timestamps to our product team, so
> that we can consider them for future releases of Atlas.
> 
> I'd better explain WHY I'd find timestamps useful.  Now I start a "new
> build" and then of course go on to other tabs to while away the formatting
> time.  When I get back to the browser tab with Atlas, what good is it to me
> to see a time shown as, say, "5 minutes ago"?  Five minutes back from
> WHEN?  No clue -- I have no trace of when exactly I left that browser
> window to go do something else during the build!  Therefore, the current
> time indications are nearly information-free -- "X minutes ago" back from
> an unknown point in time... indications of _absolute_ time would be useful
> no matter how long ago I last refreshed the Atlas tab.

Thanks,

Alex

**Comment by aleaxit** [comment]
Just a quick comment to say I support the authors working in whichever
Atlas they choose :-)

Meg

On Tue, Jan 20, 2015 at 12:07 AM, Alex Martelli aleaxit@gmail.com wrote:

> On Mon, Jan 19, 2015 at 3:16 PM, Sanders Kleinfeld <
> notifications@github.com> wrote:
> 
> > Thanks for the feedback, @aleaxit https://github.com/aleaxit. We've
> > indeed implemented Ajax automatic status indicator updates in our new Atlas
> > beta. If you're interested in switching the book to use the beta version,
> > please let your editor know, and we can discuss further.
> 
> Thanks, CC'ing said editor (and my two co-authors in case they're not that
> enthusiastic about a beta, they clearly get veto rights:-) to further the
> discussion.
> 
> > I'll pass your suggestions regarding timestamps to our product team, so
> > that we can consider them for future releases of Atlas.
> > 
> > I'd better explain WHY I'd find timestamps useful.  Now I start a "new
> > build" and then of course go on to other tabs to while away the formatting
> > time.  When I get back to the browser tab with Atlas, what good is it to me
> > to see a time shown as, say, "5 minutes ago"?  Five minutes back from
> > WHEN?  No clue -- I have no trace of when exactly I left that browser
> > window to go do something else during the build!  Therefore, the current
> > time indications are nearly information-free -- "X minutes ago" back from
> > an unknown point in time... indications of _absolute_ time would be useful
> > no matter how long ago I last refreshed the Atlas tab.
> 
> Thanks,
> 
> Alex
> 
> > Sanders
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MakerPress/atlas-public-feedback/issues/432#issuecomment-70578070
> > .

## 

Meg Blanchette
Editor | O'Reilly Media Inc.
(617)499-7573
Fax: (617) 661-1116
