### ISSUE TITLE
Builds are stalled on Atlas

### ISSUE THREAD

**Issue by markgrover** [MakerPress/atlas-public-feedback#433]
It's been at least 40 minutes that our builds (repo number: 1234000001990) are stalled. This is the case for both PDF as well as HTML builds. They have been going on for the last 40 minutes and still haven't finished. The checked to see if it's only an Atlas UI problem where chimera actually being updated and it's not.

**Comment by zaremba** [comment]
Hi @markgrover,

Thanks for pointing this out. We believe the issue is now corrected. Please let us know if you see any further problems, and apologies for the inconvenience.

Thanks,
Adam
