### ISSUE TITLE
I think I broke Atlas

### ISSUE THREAD

**Issue by patrickdijusto** [MakerPress/atlas-public-feedback#434]
When I tried to compile two chapters of Make: Bicycles (1234000002223), this is the error I got: 

Full error:

No space left on device - /tmp/systemu_atlas-worker_24216_24219_0.5866053044094476_1

What did I break?

**Comment by sandersk** [comment]
Hi @patrickdijusto,

Sorry, we had a disk outage on Atlas earlier this afternoon, which we've rectified. You should be able to build again now. Let us know if you encounter any further errors.

Thanks,
Sanders
