### ISSUE TITLE
Poorly formatted PDF

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#45]
If you look at the PDF build at http://ano-atlas2.herokuapp.com/books/1230000000581/builds, the last TIP block of "Call Center Configuration" overlaps with the heading in the next section.

**Comment by sandersk** [comment]
Hi Stafford,

Thanks for reporting this rendering problem. This is actually a known bug with the PDF rendering software we use, which occasionally affects whitespace around Tip/Warning notes. We're currently debugging this issue, and will make sure to have a solution in place before your book goes to press.

Apologies for any inconvenience here.

Thanks,
Sanders

**Comment by staffordvaughan** [comment]
Hi Sanders,

I should probably mention that the estimated completion date for my manuscript is September 7, just so you have a date to work to for this bug.

Thanks,
Stafford

**Comment by sandersk** [comment]
Thanks, Stafford. We're aiming to get a fix in place in the next few weeks, so that timing should be fine.

Sanders

**Comment by sandersk** [comment]
The issues with whitespace around note elements was dealt with for this book and rectified in our PDF-rendering toolchain. Closing this ticket.
