### ISSUE TITLE
Is Atlas down?

### ISSUE THREAD

**Issue by katehartman** [MakerPress/atlas-public-feedback#46]
I'm suddenly getting a 500 error when trying to access my book...

**Comment by runemadsen** [comment]
Looking at it right now...

**Comment by runemadsen** [comment]
Should be working now. I'm investigating what's causing this.

On Mon, Aug 13, 2012 at 5:27 PM, Rune Skjoldborg Madsen <rune@runemadsen.com

> wrote:
> 
> Looking at it right now...
>
