### ISSUE TITLE
Support authoring in branches other than master via the UI

### ISSUE THREAD

**Issue by adamwitwer** [MakerPress/atlas-public-feedback#47]
Author request:

> Atlas seems to support authoring in branches other than master, but
> only by hacking the URLs to include the branch name in place of
> "master".  Some UI controls for this would be helpful.

**Comment by adamwitwer** [comment]
Another comment on the same topic:

> I can create a build off of a branch by hacking the URL, but
> submitting the "Build" button will always trigger a build off master.
> Building from the branches becomes important, especially when we
> consider that the HTML viewer doesn't support source highlighting.

**Comment by runemadsen** [comment]
Yes, the framework for working on branches already exist, but there's no UI
for it when building. I think we only need 3 things for this to work:
1. A "Create Branch" button in Atlas
2. A way to switch branches without manually changing branch name in URL
3. A way to select branch when building

**Comment by adamwitwer** [comment]
I'll add a +1 here since I just had another author request this exact same enhancement.
