### ISSUE TITLE
Add spell-checking to the editor

### ISSUE THREAD

**Issue by adamwitwer** [MakerPress/atlas-public-feedback#49]
Author request. Maybe ACE has a plug-in of some kind.

> Spell-checking in the editor would be great.  Or at the very least,
> don't disable the spell-checker that's a default in the browser.

**Comment by ehewitt** [comment]
+1

**Comment by courtneynash** [comment]
+2

**Comment by bjepson** [comment]
I'd really like to see this too. One of the reasons I like using git with an editor of my choice (first TextMate, now MacVim) is the live spellchecking.

**Comment by strangerstudios** [comment]
+1 I was told to post my support for a built in spell checker here. Chrome doesn't recognize the editor as a text field ans so doesn't provide spell checking. Maybe there is a work around.

**Comment by strangerstudios** [comment]
Would it be as easy as adding contenteditable="true" and spellcheck="true" as attributes to the divs in the text area? Seems to work on any element in Chrome: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_global_spellcheck

(Though this might not work with ACE or break other features I'm sure.)

**Comment by runemadsen** [comment]
Hi! I'm afraid it's not going to be that simple. The ace editor splits each line, word and cursor into multiple div's, so this probably won't work. However, I know some very smart people are working on it (Ace contributors), so we're following that pretty closely.

**Comment by shelleyp** [comment]
Without spellcheck, I wouldn't bank on a lot of success as an online editor.

**Comment by sandersk** [comment]
@shelleyp Yes, we agree. Spellcheck is at the top of our list of editor features to add in the next release of Atlas. We'll keep you posted.

**Comment by jack-krupansky-BT** [comment]
+1,000,000

II haate tto admmit itt, buut mmy texxt dessperately neeeds ann auutomated spelll checkk - annd corrrector.

Heelllpppp!

**Comment by strangerstudios** [comment]
FWIW, I've found that my spelling has improved as I've been using Atlas without the aid of a spell checker.

**Comment by shelleyp** [comment]
Typos are not uncommon in writing, especially when you're on a deadline. A spellcheck tool can frequently help us catch these. 

I understand that spellcheck is on the to-do list, and look forward to seeing its implementation.
