### ISSUE TITLE
Create 1 page cheatsheet

### ISSUE THREAD

**Issue by MakerPress** [MakerPress/atlas-public-feedback#5]
Common commands in git, Asciidoc, and github commands.   all in one page

commit w/message
push
pull

**Comment by adamwitwer** [comment]
Let's add "Cheat Sheet" as a tab, between Feedback and Logout and present it as straight HTML. I can write it.

**Comment by mikehatora** [comment]
[ ]  Quick Guide - AsciiDoc
[ ]  Quick Guide - Git
[ ]  Quick Guide - TextMate and command line operations

At the time we create a project, prompt the editor to check these and then populate the new project.  Not all need the same things.  And giving authors too much, means they won't read anything.
