### ISSUE TITLE
Filename in the change log

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#50]
When my editor makes a change and customizes the comment, I sometimes can't find the file that he modified. Can you include the filename in each change log entry please?

**Comment by staffordvaughan** [comment]
I'd also love to see a timestamp in the change log for each change.

**Comment by sandersk** [comment]
Hi @staffordvaughan 

Just an FYI that we added both of these features to the Changes tab in a recent Atlas release; filenames are now showed in the change log entries, as well as a timestamp. Let us know if you see any problems or have any other feature requests.

Best,
Sanders
