### ISSUE TITLE
500 Something went wrong accessing Atlas book

### ISSUE THREAD

**Issue by toddllm** [MakerPress/atlas-public-feedback#51]
500
We're sorry, but something went wrong.
If you think this is a bug, please report it

trying to get to:
http://ano-atlas2.herokuapp.com/books/1230000000605

**Comment by sandersk** [comment]
Hi Todd,

Were you logged into Atlas when you tried to access the URL below? You will get a 500 error if you are not logged in prior to accessing a book URL directly.

I was able to access the URL below without problems after logging in, so I don't believe there are any network problems here. Please let me know if you're still unable to access the book page when logged in.

Thanks very much,
Sanders

**Comment by toddllm** [comment]
Excellent. That worked. That was the only link I had. Thanks! 

I should have thought to try going to the server itself.
