### ISSUE TITLE
Outage?

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#53]
I'm getting an error 500 on http://ano-atlas2.herokuapp.com/books/1230000000581.

**Comment by estelle** [comment]
i am gettin 500 errors as well, on invitation, book link, etc.

**Comment by MakerPress** [comment]
Hi.  Sorry about the outage -- it's fixed now.

**Comment by mrflip** [comment]
Still seeing it, 5:48 CST

**Comment by adamwitwer** [comment]
We're back now. Apologies for the downtime.

**Comment by runemadsen** [comment]
I'm working on fixing the bug that kills the git server, so hopefully we won't see these downtimes again.

**Comment by staffordvaughan** [comment]
Seems to be working now. Thanks.

**Comment by mrflip** [comment]
It's still breaking for me, and I'm worried that my pushes are the thing
bringing it down. My repo is also pushed as

```
git://github.com/mrflip/big_data_for_chimps.wiki.git
```

Any chance you can try pulling it in at your end?

At this point you'll need to do a `git push --force` to work

**Comment by runemadsen** [comment]
Thanks Philip. I'll take a look at it.

**Comment by runemadsen** [comment]
Philip, can you send the link that is causing you problems? I'm not having problems with browsing or opening your book in the editor.

**Comment by mrflip** [comment]
Moving to a separate issue.
