### ISSUE TITLE
Add Build button to top of Build page as well

### ISSUE THREAD

**Issue by nelliemckesson** [MakerPress/atlas-public-feedback#54]
For easier usability, would be nice to have the build button duplicated at the top of the Build page as well, especially for books with a lot of chapters, when you know that all the chapters are in the right order, etc.

**Comment by jhodgdon-drp** [comment]
And vice versa -- it would be nice to have a link from the Build page to the completed Builds page, and a button on the completed Builds page to launch a build using your last parameters (maybe called "rebuild last build" or something to that effect?).
