### ISSUE TITLE
"RPC failed; result=22, HTTP code = 502" pushing to 1230000000073.git

### ISSUE THREAD

**Issue by mrflip** [MakerPress/atlas-public-feedback#55]
My book is /1230000000073.git -- I'm getting "RPC failed; result=22, HTTP code = 502" when I try to push (and have been since last night).

This is what happens when I push the code:

```
    worblehat ~/ics/book/big_data_for_chimps$ git push oreilly master --force
    Counting objects: 903, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (396/396), done.
    Writing objects: 100% (903/903), 1.33 MiB | 225 KiB/s, done.
    Total 903 (delta 500), reused 804 (delta 451)
    error: RPC failed; result=22, HTTP code = 502
    fatal: The remote end hung up unexpectedly
    fatal: The remote end hung up unexpectedly
    Everything up-to-date
```

Even when I do it on a branch that shares history (i.e. don't need to say git push --force) it breaks

```
    worblehat ~/ics/book/big_data_for_chimps$ git push oreilly foo:master
    Counting objects: 848, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (338/338), done.
    Writing objects: 100% (802/802), 1.04 MiB | 183 KiB/s, done.
    Total 802 (delta 474), reused 691 (delta 414)
    error: RPC failed; result=22, HTTP code = 502
    fatal: The remote end hung up unexpectedly
    fatal: The remote end hung up unexpectedly
    Everything up-to-date
```

An up-to-date version of the code is at git://github.com/mrflip/big_data_for_chimps.wiki.git 

Can you do a `git push --force` of the github copy to the Atlas repo? That would take one part of the complication away.

**Comment by sandersk** [comment]
Hi Philip,

The error you're getting below looks like an HTTP buffer error. Could you try running the following command prior to doing your "git push":

$ git config http.postBuffer 524288000

That should increase the HTTP buffer size, which I'm hoping will solve the problem. Let me know if not.

Thanks,
Sanders

**Comment by mrflip** [comment]
Worked like a charm. thanks @sandersk

**Comment by mrflip** [comment]
Don't know if this is related, but my book isn't building -- PDF spinning for 30 min, another build spinning for 10 min.

**Comment by MakerPress** [comment]
Hey, flip.  I think the force merge broke the cache.  I just reset it -- git the build another shot.

----- Original Message -----

**Comment by adamwitwer** [comment]
Hey guys. I'm closing this for now. @mrflip, please reopen if this is still happening.
