### ISSUE TITLE
Post getting started guide, sample chapter, and cheat sheet on GitHub

### ISSUE THREAD

**Issue by MakerPress** [MakerPress/atlas-public-feedback#6]
We need to make the docs more accessible so that authors can find them.  Maybe we post all this stuff on GiutHub?  That way people can get them easily and the ones who want to can fork them and experiment...

**Comment by smayzak** [comment]
It would be nice to have a tutorial built inside Atlas itself, in maybe a read only mode.  Video's are great too.  Github is a fine place for storage and will work for now but as this tool gets closer to release, a couple of video walkthroughs would be great.

**Comment by adamwitwer** [comment]
We published there here for now:

http://cdn.oreilly.com/atlas_docs.zip

Created in Atlas! The source is also on GitHub, and we'll make it public at some point.

More resources here: http://atlas.labs.oreilly.com/getting_started
