### ISSUE TITLE
Saving bookdocinfo.xml name gets changed to bookdocinfo.xml.asciidoc

### ISSUE THREAD

**Issue by raywilson007** [MakerPress/atlas-public-feedback#64]
Saving bookdocinfo.xml name gets changed to bookdocinfo.xml.asciidoc by Atlas.

**Comment by runemadsen** [comment]
Hey Ray

When did this happen? I just tested it by clicking "New File", adding
"bookdocinfo.xml"
to the title, and saving. Atlas kept the name and did not append the
.asciidoc attribute.

Can you send me a link to the file in Atlas?

**Comment by raywilson007** [comment]
Hi

It was when I noticed that I had put a dash in the name somehow and tried
to change it by changing the name in the interface.
Here is an image of what I mean. I think that when I first entered it
through the "add file" path it worked.

I'm not sure how to send you the link to the file but if you tell me how
I'll be happy to.

Thanks for getting back to me so quickly. Let me say that I find using the
Atlas interface very comfortable and that it works really well.
A cool addition would be to allow people to set up key-combinations like
CTRL-Y to delete lines etc but as is it's totally cool.
I wrote a content management system for US Bank's merchant interface a few
years ago and I know it's very challenging. Really nice job.

Ray

**Comment by runemadsen** [comment]
Thanks Ray! Really appreciate it.

Another way of going about it: What's the name of your book?

When you click on the file in Atlas to edit it, I think you can just change
the name, hit save and go back to "dashboard". Then the file should be
renamed.

**Comment by raywilson007** [comment]
Hi

The name of the book is:

Make: Analog Synthesizers
Electronic Sounds the Synth-DIY Way

ISBN: 1230000000653

Shawn Wallace is the editor.

I just started on this as it got approved only recently.

I tried again to rename the file as suggested and Atlas added  ".asciidoc"
to the end of it. This is not a show stopper for me.
It would be nice if you could remove images and files. If there is a way to
do that I have missed it thus far.

Getting started with Atlas mentions that you should use bookdocinfo.xml for
meta data and that even though you don't
include it in the "build" it will be found by the build code which will add
the contained information to the proper area of the book.
I have not tried a book build as of yet. I have only started on the book
and have chapters one and two underway.

I'm very hazy on how to do a book build using Atlas but I'll try it one of
these days.

If you need more info let me know.

Cheers

Ray

**Comment by runemadsen** [comment]
I'm sorry. You were right, there was a small bug there. It's fixed now and
I renamed you file already.

Let me know if you're having trouble building your book.
- Rune

**Comment by raywilson007** [comment]
Awesome! Thanks Rune.

**Comment by raywilson007** [comment]
Hi Rune

Question?

I included an image to illustrate the point.

The code below results in the image caption being butted up against the
following heading in HTML view. Is there a way to cause a bit of space to
occur ahead of the heading "==== Triggers" for example. If a paragraph
follows the image it also buts up against the captioned image's bottom
(same question on that).

[[gatedesc]]
.Keyboard Controller Gate Signal
image::images/keyboardcontrollergate.png[scaledwidth="90%"]

==== Triggers

A trigger pulse is emitted from the keyboard controller any time a key is
initially pressed and any time the note is changed (as in legato style
playing). A trigger pulse can also cause an envelope generator to spring
into action but with slightly different results which we'll detail below.
I'll be referring to gates and triggers below and now at least you'll know
what I'm talking about.

[[trigdesc]]
.Keyboard Controller Trigger Signal
image::images/keyboardcontrollertrigger.png[scaledwidth="90%"]

Any help appreciated and again not a show stopper.

Ray

**Comment by sandersk** [comment]
Hi Ray,

The HTML View is intended to give a quick preview of the book, so you can spot-check the content without the markup. We're working on refining the rendering of content in HTML View so it's more WYSIWYG, but right now, it's not intended to reflect the formatting and layout of the actual ebooks files that you can generate on the Build tab. The ebook builds are much more refined, and images/captions are set off from the rest of the text appropriately.

When you get a chance, perhaps generate a PDF, EPUB, and/or Mobi on the Build tab, take a look, and see what you think? If you have any feedback on the formatting in the ebook builds, we'd love to hear that, too.

Best,
Sanders

**Comment by raywilson007** [comment]
Thanks. I tried the PDF and the MOBI format and both built fine.
They both look great! Keep up the awesome work.
I'll build from time to time to make sure I'm on track.

Cheers

Ray

On Thu, Aug 23, 2012 at 7:24 PM, Sanders Kleinfeld <notifications@github.com

**Comment by sandersk** [comment]
Super, glad to hear you're happy with the results, Ray!
