### ISSUE TITLE
Not sure how to delete a file

### ISSUE THREAD

**Issue by JohnGarbutt** [MakerPress/atlas-public-feedback#67]
It doesn't seem clear how I can delete (or rename) a file in the system, but I may have missed something.

**Comment by sandersk** [comment]
Hi John,

You can rename a file in Atlas when you have it open for editing. All you need to do is change the filename listed in the field directly below the "Editor"/"HTML View" buttons, and then click Save.

Unfortunately, right now, we don't have a mechanism in the Web interface for deleting files, but it's on our list of future enhancements, and we're tracking this task here:

https://github.com/MakerPress/atlas-public-feedback/issues/43

You can, however, delete files by making a local Git checkout, deleting the files, and committing/pushing back to the repo. Instructions for using a local Git checkout can be found in Chapter 6 of our Atlas docs, which are available here:

http://cdn.oreilly.com/atlas_docs.zip

Hope this helps. Let us know if you have any further questions.

Best,
Sanders
