### ISSUE TITLE
Ideas for enhancement of the "Your Books" list

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#68]
Was talking to Dan earlier today, and he mentioned that a nice feature for the future would be to allow people more control over how the books in the Your Books list are organized. He made a great point that as editors and Production staff work on more and more Atlas titles, the Your Books list may start to become a little bit unwieldy. Some ideas:
- Allow people to sort the Your Books list alphabetically, as well as by when they were added to the project
- Allow people to make a Favorites list of titles, so they can bookmark specific titles that they will be working on regularly
- Allow some sort of search capability so that if someone is a collaborator on, say, 50+ books, they could just search by title to find the book they want to work on.

**Comment by courtneynash** [comment]
+1. I'm already at 12 books going in Atlas and it is going to start to get messy pretty soon...

**Comment by simonstl** [comment]
Agreed completely.  I'd also like some kind of list that shows how recently changes/builds have happened, and an option for marking projects as off my radar.  (They may still have activity, like authors updating after release, but I don't need to manage them actively.)

Also, because I'm an editor/author hybrid, it would be nice to have a way to separate "books I'm writing" from "books I'm editing".

Thanks!

**Comment by runemadsen** [comment]
This has been implemented now. You can sort by a number of values, and do a "quick search" to find your book by title. Let me know how that works, and if there are other parameters you would like to sort by.

**Comment by adamwitwer** [comment]
The gods bless you, man! This is so helpful.

**Comment by odewahn** [comment]
Forbløffende!

----- Original Message -----

**Comment by runemadsen** [comment]
He he.... Det er virkelig forbløffende.

**Comment by odewahn** [comment]
This look would also be amazing for the chimera books page, especially as we start gathering more stats there.  (So, you could have most read, most commented, last read, and so forth).

Andrew

----- Original Message -----

**Comment by sandersk** [comment]
Det er fremragende, Rune! Tak!
