### ISSUE TITLE
Last page of PDF file says "Chapter 0"

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#69]
I noticed this when I started writing. The PDF export from my book at http://ano-atlas2.herokuapp.com/books/1230000000581/builds says "Chapter 0: Forums" in the footer of the last page, but only on the last page. It obviously only happens when the book finishes on an even page, which it might not right now.

**Comment by sandersk** [comment]
Hi Stafford,

Thanks for flagging this issue for us. This is another known bug with the PDF rendering software we use, which we have reported to the software vendor. The issue will be fixed when the book enters production, as adding the usual backmatter pages will fix the "Chapter 0" problem on the last page of Chapter 9. 

So, rest assured, we have this one covered :)

Thanks,
Sanders
