### ISSUE TITLE
Check ins not being displayed

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#71]
If you take a look at the list of updates on http://ano-atlas2.herokuapp.com/books/1230000000581/versions/master/changes, only one minor changes is listed from Andy. But the file Chapter-4:-User-Management.asciidoc was definitely edited by him, amongst many others. Can you try to identify from the logs why many of the submissions weren't logged? This is a huge problem for me, because I'm using Atlas instead of Git and relying on the change history to sync up on Andy's changes.

**Comment by runemadsen** [comment]
Hey again. You're right. The changes tab is currently not showing multiple
files in a commit. Let me try to fix this and get back to you.

On Thu, Aug 30, 2012 at 12:31 PM, Stafford Vaughan <notifications@github.com

**Comment by runemadsen** [comment]
Almost there. Give me 15 minutes more.

**Comment by runemadsen** [comment]
Okay, take a look again. All the files should be there!

**Comment by staffordvaughan** [comment]
Perfect! I love that it's listed historically as well, so I can go back and
see if there were any other issues. I also like that you implemented my
feature request in
https://github.com/MakerPress/atlas-public-feedback/issues/50 (though the
timestamp would also be fantastic).

**Comment by runemadsen** [comment]
Cool. I can do that. The timestamp kind of relies on the computers own
clock, so it's not completely reliable, but I'll look at it.

**Comment by adamwitwer** [comment]
Rune, while you're looking at this -- another thing we might tweak about the Changes tab is how changes to binary files are tracked. See here, for example:

http://atlas.labs.oreilly.com/books/1230000000065/versions/master/changes

Sorry, not trying to highjack the request. Just thought it'd be useful to have features requests to the Changes tabs tracked in a single issue.

Adam

**Comment by runemadsen** [comment]
I actually fixed that 3 months ago, but we just haven't deployed it on the
git server yet, as it requires installing a dependencies. I was waiting
until we make the switch to the new git server, but if it's needed now I
can restart the git server tonight.

**Comment by adamwitwer** [comment]
Oh great, I've no problem waiting. No need to restart tonight!
