### ISSUE TITLE
Restoring files

### ISSUE THREAD

**Issue by michaeljamesfitzgerald** [MakerPress/atlas-public-feedback#72]
I accidentally overwrote a file. How do I restore the overwritten file from the interface? Or do I have to use a git client?

**Comment by sandersk** [comment]
Hi Michael,

We don't currently have a mechanism in the Atlas Web Interface for restoring older versions of files; however, you can use a Git client to revert to a previous version. 

If you'd like, I'd be happy to help restore the old version of the file for you. Just let me know what book it is, what file, and the time in the version history you want to revert back to.

Best,
Sanders

**Comment by michaeljamesfitzgerald** [comment]
Sanders, If you could restore Introducing Regular Expressions, ch03.asciidoc, August. 29 version. Thank you, Mike

**Comment by sandersk** [comment]
Hi Mike,

Sure thing, I restored the version of ch03.asciidoc from this commit:

commit 632939d209afaee2b2488f8d4287dfcd004d7d80
Author:  <null>
Date:   Thu Aug 30 15:37:23 2012 -0700

:100644 000000 d072dd6... 0000000... D  ch02.asciidoc

Which was the commit right before ch03 was modified on 8/30. I'm guessing that's the correct revision, but let me know if you need another version of the file.

Thanks,
Sanders

**Comment by michaeljamesfitzgerald** [comment]
That's correct. Great. Thank you much.
