### ISSUE TITLE
"book.asciidoc missing" error when doing a Build

### ISSUE THREAD

**Issue by sandersk** [MakerPress/atlas-public-feedback#75]
Just a minor bug that's not a big deal, and may not even come up again, but wanted to file a ticket for the record so we could address when convenient:

On of the editors on the Radar team was trying to do a build earlier today, and it failed with a "book.asciidoc missing" error:

asciidoc: FAILED: input file
/home-local/worker/tmp/pdf/1230000000749/book.asciidoc missing

Upon further troubleshooting with him, it turned out that he had not dragged any files over to the "Files to Build" panel, hence the missing book.asciidoc file. 

Normally, if you fail to drag any files over to "Files to Build", you get an error that says "Please select at least one file to build". But this doesn't appear to happen if you've never built before. Instead, it lets the build go through with the "book.asciidoc missing" error.

**Comment by runemadsen** [comment]
Ah, thanks. I'll fix that right away!

**Comment by runemadsen** [comment]
This has been fixed now. It was jus a little controller logic that needed to be rearranged.

**Comment by runemadsen** [comment]
Also, the checks are now being made on server side instead of on JS side.
