### ISSUE TITLE
latexmath filter causes text to disappear in PDF

### ISSUE THREAD

**Issue by swenson** [MakerPress/atlas-public-feedback#77]
I was under the impression that the latexmath filter was supposed to translate into MathML, which would then be correctly formatted in the PDF.

**Comment by adamwitwer** [comment]
Hi Chris. Thank you for checking on this feature. We have a plan to implement support for the latexmath macro, but it's queued up by some plumbing and sysadmin stuff we're attending to now. We expect to have the latexmath macro working within about a month from now. You can continue to use it and we'll have it ready in plenty of time time for your book, although I know that nothing actually shows up in the PDF builds at this time. 

Adam

**Comment by nelliemckesson** [comment]
Hey @adamwitwer ,

Is LaTex supported in Atlas yet? Cathy O'Neil, author of the upcoming "Doing Data Science", sent a ticket to the tools queue asking about implementation.

**Comment by adamwitwer** [comment]
Not yet, but several authors are using the `latexmath:[]` macro in AsciiDoc, and we're planning to support it. All the books that are using it are publishing in 2013, so we haven't made it a high priority, but we'll get to it. Cathy can use LaTeX via the macros for the equations, but we have no plans for full LaTeX support.

**Comment by sandersk** [comment]
Hi @swenson,

Just wanted to let you know that LaTeX support is now in place for the EPUB, Mobi, and PDF builds in our toolchain (not available in the HTML preview at this time). Both block and inline LaTeX equations are supported. Here are some additional syntax details: 

For block-level equations, the equation goes in a latexmath passthrough like this:

```
[latexmath]
++++
\begin{equation}
{x = \frac{{ - b \pm \sqrt {b^2 - 4ac} }}{{2a}}}
\end{equation}
++++
```

Where you can replace the content between the two ++++ delimiters with any valid LaTeX equation markup you like. Optionally, 
you can add a title for the equation below the [latexmath] line as follows:

```
[latexmath]
.The quadratic formula
++++
\begin{equation}
{x = \frac{{ - b \pm \sqrt {b^2 - 4ac} }}{{2a}}}
\end{equation}
++++
```

For inline equations, use a latexmath:[] macro as follows:

```
The Pythogorean Theorem is latexmath:[$a^2 + b^2 = c^2$]
```

Where you can replace the content between the [] delimiters with any valid single-line LaTeX equation markup you like.

Please let me know if you have any questions or encounter any problems, and I'm happy to assist further.

Thanks,
Sanders
