### ISSUE TITLE
Images in sidebars not rendering well in PDF

### ISSUE THREAD

**Issue by staffordvaughan** [MakerPress/atlas-public-feedback#78]
If you take a look at the latest PDF of http://ano-atlas2.herokuapp.com/books/1230000000581/builds, you'll notice that whenever images are included in a sidebar, the border around the sidebar doesn't render properly. An example is the "Formatting Options" sidebar around page 113. I have a couple of sidebars in which I'd like to include screenshots, so can you try to fix this, if it's not going to be fixed during the production process?

**Comment by adamwitwer** [comment]
Hi Stafford. Images with captions don't normally appear in sidebars, so the stylesheets weren't set up to handle them. That's okay, though. I added a customization to your book so that a border isn't added when an image appears in a sidebar. Let me know if that looks okay.

**Comment by staffordvaughan** [comment]
I checked the PDF and I think it looks fine like that.

By the way, why is there padding between the regular images and the black
border around them? I think it would look significantly better if the
border hugged the image that was uploaded.

**Comment by sandersk** [comment]
Hi Stafford,

Sorry, realized we never responded to your second question here. You're referring to the standard Figure boxes, like the ones on pages 131-132, correct? If so, it's a longstanding design convention of the books in our Animal series to have some padding between the border boxes and the images within. This isn't something we plan on changing.

Best,
Sanders

**Comment by sandersk** [comment]
Closing this ticket, as the Zendesk book has gone to press, and I believe prior to that we've clarified and/or resolved all the issues cited here. Stafford, please reopen if you have any further questions or see any additional problems with PDF builds.
