### ISSUE TITLE
Atlas doesn't deal with directories

### ISSUE THREAD

**Issue by jimwebber** [MakerPress/atlas-public-feedback#80]
I just pushed my book repo which I had been storing on github. It has a shallow directory structure, like this:

```
root
  |
  +- book.asciidoc
  |
  +- Chapter 1
  |     |
  |     +- Chapter1.asciidoc
  |     |
  |     +-figures
  |          |
  |          +- fig1.png
  |          |
  |          +- fig2.png
  |
  +- Chapter 2
          |
          +- Chapter1.asciidoc
          |
          +-figures
               |
               +- fig3.png
```

Etc.

However none of the subdirectories are visible to Atlas, even though they are present in the git repo (which I cloned to make sure). 

This means I can't build my book directly since I can't add the asciidoc files from those subdirectories.  Instead I have to flatten my repo which is kinda lame.

**Comment by sandersk** [comment]
Hi Jim,

You're correct that at the present time, Atlas requires all AsciiDoc files to be at the root level of the repository in order to do builds. Apologies if this organization is not ideal for your specific book project. We will be looking at adding support for subdirectories in future versions of the application, and will keep Atlas users posted on this. 

You can, however, use subdirectories for graphics files, as you've done above.

Hope this helps clarify. Let me know if you have any questions or run into any issues.

Best,
Sanders

**Comment by davidsklar** [comment]
I am also running in to this issue; my primary method of interfacing with the repo is via git (just using the atlas web UI builds and other admin tasks), so I have a nice directory structure with chapters in "chapters/", various tools in "tools/" and so forth. 

Perhaps useful shortcut would be to make the "book.asciidoc" file in the root dir visible via the web UI and then it could reference (within subdirectories) files that need to be built?

**Comment by xdbr** [comment]
I just ran into the same issue. I would really like to see support for directories in a future version of atlas, exactly the way the OP describes (`chapters/` and the like) . Big vote for subdirectory-support here.

Thanks/dbrx

**Comment by xdbr** [comment]
BTW: Is there any solution to amend this situation for the moment or an intermediate workaround path to take? Ideas?

**Comment by runemadsen** [comment]
Thanks @xdbr. I'm working on this as we speak, and the next major upgrade to Atlas will have support for subdirs, and a ton of other stuff. It's not something we can easily put in the current version of Atlas, but stay tuned. I promise it'll be worth the wait.

**Comment by xdbr** [comment]
Thanks for the heads-up @runemadsen, that sounds awesome!

Can you share an estimate on when you guys plan on pushing out the next version of Atlas?

There is a list of feature requests/enhancements/bugs that I have found and which I will file by-and-by, maybe some of them will make it into the next version...

Anyways, can't wait to see the next iteration and Atlas already rocks :)

**Comment by runemadsen** [comment]
Great. Yes, please keep the issues coming. I look at this feed every day and will incorporate them as they are posted. The timeline is still a bit up in the air, as we're redoing a bunch of things based on what we learned in the first version. I'll ping you when I know more.

**Comment by xdbr** [comment]
Ok, great, thanks very much Rune
