### ISSUE TITLE
Warning if you leave a page with unsaved changes

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#82]
Could we get a warning up if you try to navigate away from a page with unsaved changes? I've had authors lose work because they forgot they hadn't saved.

**Comment by runemadsen** [comment]
This has been implemented now. If you try to navigate away from the editor with unsaved changes, you will get an alert box asking you to confirm.

**Comment by adamwitwer** [comment]
Nice. Working well for me, Rune!
