### ISSUE TITLE
Indexer feedback

### ISSUE THREAD

**Issue by DanGitOreilly** [MakerPress/atlas-public-feedback#83]
I'd like to pass along feedback that I've received from an indexer working in Atlas.
1. She reported that the site is very slow on IE8, but much faster in Safari. I know that's got nothing to do with indexing, but wanted to report it.
2. Indexers sometimes insert ranges. For example, when an entry is discussed over multiple pages, she would write the index in such a way that a page range would appear in the index. In the Atlas UI, she couldn't find a way to determine where page breaks would fall. She could cut a pdf each time, but that would make for a terrible indexing workflow. 

If there could be a way of having a visual indication of a page break, that would be very helpful for indexers.

**Comment by sandersk** [comment]
Hi Dan,

This is great feedback. Thanks very much for passing it along. With respect to Point 1, I've made a note for us to do some further Atlas speed testing in different browsers, and see if further speed improvements are possible in IE.

Regarding Point 2, this isn't really an issue specific to Atlas, as it's true for indexing in DocBook with XMLMind, too. With InDesign, indexers are working in a WYSIWYG page layout program and can see where page breaks fall; with ASC/DB, page layout is done on the fly when a PDF build is triggered. As such, the editor used to insert index markers (whether the Atlas UI or an editor like TextMate) doesn't "know" where the pagebreaks are going to fall in PDF.

We could potentially do pagebreak "estimates" in the Atlas editor, potentially adding a dashed horizontal line to indicate a pagebreak every 50 lines or so, but I'd be concerned that that would give other folks (authors, editors) using Atlas a false impression of where pagebreaks were actually going to fall.

Does an indexer really need to see page breaks to make a good judgment whether a range was needed? Or could we just give a general rule of thumb that they could follow? For example, we could say that if there were more than 10 paragraphs of text separating the "start" and "end" entry, then a range should be used.

Thanks,
Sanders

**Comment by DanGitOreilly** [comment]
Thanks Sanders,

Your explanation and comparison to indexers working in Docbook makes perfect sense. This feedback comes from an Indexer that is used to InDesign, just as you suggest.

I like your idea about coming up with a rule of thumb about a number of paras. I'll suggest that to her and keep it in mind for other indexers.

Dan
