### ISSUE TITLE
Index feedback (2)

### ISSUE THREAD

**Issue by DanGitOreilly** [MakerPress/atlas-public-feedback#84]
This is a good one. An indexer asked for help with terms that weren't generating, and I found that it was because she was trying to insert asciidoc indexing macros into portions of the text that were asciidoc passthroughs. 

Part of the solution to this is indexer training, but I mention it here in case this could be made more obvious to them. Perhaps and "indexer view" that highlights passthroughs in such as way to make it clear that they should switch to docbook index tags, or skip those sections.

**Comment by sandersk** [comment]
Hi Dan,

Wow, that is a good one, and an issue I hadn't anticipated. I could see how it could be confusing to an indexer that they'd have to switch to DocBook markup if the indexterm is in a DocBook passthrough.

Indexer training might help, as might some sort of highlighting to better distinguish passthroughs from standard AsciiDoc. We're working on having highlighting of the AsciiDoc markup in place in the Atlas editor very soon.

I'm going to keep thinking if there's even a better way to help indexers in this situation, as it's a lot to ask of them to be thinking about whether they need to switch back and forth between two different markup types when adding index markers.

Sanders
