### ISSUE TITLE
Resolving "no tracking information for the current branch" error?

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#87]
Hi,

I tried switching my server with:

`git remote rm origin`
`git remote add origin [url from metadata]`

but now I get this error:

There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

`git pull <remote> <branch>`

If you wish to set tracking information for this branch you can do so with:

`git branch --set-upstream master origin/<branch>`

What should I do to resolve this?

Thanks,

Brian

**Comment by bjepson** [comment]
Never mind, I specified the wrong repo.

**Comment by bjepson** [comment]
Ooops, spoke to soon. It happens even when I set the origin to the correct repo.

**Comment by bjepson** [comment]
I think this is correct, but I want to leave this open until someone smarter than me can check it:'

`git branch --set-upstream master origin/master`

**Comment by bjepson** [comment]
That was probably wrong, since a fresh checkout shows the following for `git branch --all`:

`* master`
`remotes/origin/HEAD -> origin/master`
`remotes/origin/master`

But after setting the upstream master manually, I see:

`* master`
`remotes/origin/master`

**Comment by runemadsen** [comment]
Hey Brian

Are you just trying to pull from master? Does a `git pull origin master` work?

**Comment by bjepson** [comment]
Thanks, Rune. I'm trying to pull from master. After a fresh checkout of a repo, `git pull` pulls from master. `git pull origin master` works after I do `--set-upstream` on my old checkout, but I'd like to set it up so I don't have to remember the `origin master` part.

**Comment by runemadsen** [comment]
Ah, I see. You should be able to run these two commands from your repo root, and then you don't need the `origin master` when you pull.

`git config branch.master.remote origin`
`git config branch.master.merge refs/heads/master`

Let me know if that works.

**Comment by bjepson** [comment]
Thanks! I'm still seeing different values for a fresh clone. After I run the git config commands you suggested:

`bcjpro:1230000000237 bjepson$ git branch --all`
`* master`
`remotes/origin/master`

After a fresh checkout:

`bcjpro:1230000000237 bjepson$ git branch --all`
`* master`
`remotes/origin/HEAD -> origin/master`
`remotes/origin/master`

Will that cause a problem? I'm wondering why the HEAD reference is missing.

**Comment by runemadsen** [comment]
Sorry, I didn't get the follow up emails on this issue. I don't think this will be a problem. I don't have the remotes/origin/HEAD in my other repos when running the command.

Are you seeing problems or are you just worried about "HEAD" not showing up?
- Rune

**Comment by bjepson** [comment]
I was concerned about HEAD not showing up, but it sounds like things will be fine. Thanks!

**Comment by runemadsen** [comment]
Ok, great. Let me know if anything comes up.
