### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by adamwitwer** [MakerPress/atlas-public-feedback#88]
Melanie asked me about a build error:

http://atlas.labs.oreilly.com/books/168/jobs/10964

My suspicion is that there is a build error and that Atlas isn't passing the error back correctly. But that's just a guess. I'm cloning the files so that I can run pdfrenderer independently of Atlas to identify the error. It's taking FOREVER to clone because the repo is so large.

**Comment by adamwitwer** [comment]
Here's the error:

```
Traceback (most recent call last):
  File "/usr/local/app/worker/atlas-workers/workers/err.py", line 19, in <module>
    print "%s\n" % linecache.getline(xml_source,int(fields[1]))
ValueError: invalid literal for int() with base 10: 'rated for 0.1&mu;F at 50V. Center'
```

Still waiting for files to download....

**Comment by runemadsen** [comment]
Thanks Adam. Adam/Sanders do you know what that error is?

**Comment by odewahn** [comment]
Thanks, Adam.  Looks like this is some weird handling of the literal in the code that parses the asciidoc error log.  Looking into is...

Andrew

ps -- weird that it's taking you so long to download.  Is it done?  We've noticed that the new atlas-admin seems to slap requests into the "denyhosts" bucket pretty quickly. If it's not done soon let me know and I'll check it out.  It could just be that it's a huge file that's taking a while...

----- Original Message -----

**Comment by adamwitwer** [comment]
Still going! It's our old friend, the Encyclopedia of Electronic Components. Only 43% of the way there....

$ git clone https://adam%40oreilly.com@atlas-server.oreilly.com/git/1230000000669.git encyc_elec_comp
Initialized empty Git repository in /mnt/work/work/tools/adam/books/encyc_elec_comp/.git/
Password: 
remote: Counting objects: 4133, done.
remote: Compressing objects: 100% (4000/4000), done.
Receiving objects:  43% (1803/4133), 1.27 GiB | 678 KiB/s

**Comment by odewahn** [comment]
The plot thickens. It looks like there are some entities ( &Omega; and &mu;) being used in the xml that the xml parser doesn't like.  Here are a few examples from the error logs of the worker:

/usr/local/app/worker/tmp/pdf/1230000000669/book.xml:2528: parser error : Entity 'Omega' not defined
asis>. In these examples, each has an arbitrary rated resistance of 4,700&Omega;
                                                                               ^
/usr/local/app/worker/tmp/pdf/1230000000669/book.xml:2812: parser error : Entity 'mu' not defined
ITOR_CERAMIC_GENERIC"><title>Generic ceramic capacitors. Left: rated for 0.1&mu;

There's still a problem with the code that's parsing the error log, but this is the underlying problem it's trying to report.

----- Original Message -----

**Comment by runemadsen** [comment]
Yes, I want to take a stab at making sure we always bubble these errors back to Atlas. That also means never to have an eternal "pending" job. 

Man, that's a biiiiig book.

**Comment by adamwitwer** [comment]
Okay, so the book-docinfo.xml (used for book metadata and copyright page stuff) was very, very badly formed. I fixed that. Builds still failing, but I'm getting closer. I think the entity errors were bogus, caused by the badly formed book-docinfo.xml file.

**Comment by adamwitwer** [comment]
Okay, PDFs are building again. In this case, there was no way for a user working strictly in Atlas to locate and fix the errors. 

Also, I noticed that this book had some less severe validity errors. Because we're using the --invalid-ok option, the user is not aware of the validity errors, and a book could potentially make it's way through production as invalid XML, which will cause problems down the line. We should think about a adding build warnings to Atlas, which would list validity errors, even when a build doesn't fail.
