### ISSUE TITLE
Merging with git pull on new URL

### ISSUE THREAD

**Issue by mrichardson23** [MakerPress/atlas-public-feedback#89]
I followed the instructions in the email to change the git repo and now when I do a 'git pull' I get:

```
172-29-131-161:GSWRPi matt$ git pull
Password for 'atlas-server.oreilly.com': 
You asked me to pull without telling me which branch you
want to merge with, and 'branch.master.merge' in
your configuration file does not tell me, either. Please
specify which branch you want to use on the command line and
try again (e.g. 'git pull <repository> <refspec>').
See git-pull(1) for details.

If you often merge with the same branch, you may want to
use something like the following in your configuration file:
    [branch "master"]
    remote = <nickname>
    merge = <remote-ref>

    [remote "<nickname>"]
    url = <url>
    fetch = <refspec>

See git-config(1) for details.
```

I went into the config file, but it's not as straightforward as I hoped. Can you let me know how to set this up so that a git pull merges into my working files?

**Comment by runemadsen** [comment]
Hey Matt

Try `git pull origin master`. 

Or if you don't want to specify `origin master` run these two commands:

`git config branch.master.remote origin`
`git config branch.master.merge refs/heads/master`

and then you should be able to:

`git pull`

**Comment by mrichardson23** [comment]
Works great now. Thanks.

**Comment by runemadsen** [comment]
Great!

**Comment by mifga** [comment]
Totally helpful -- this is exactly what I was looking for today as well.
