### ISSUE TITLE
Changes tab is super slow

### ISSUE THREAD

**Issue by MakerPress** [MakerPress/atlas-public-feedback#91]
I've noticed that the "Changes" tab is really slow for projects that have a lot of histroy.  For exameple, click on changes for "Surviving Orbit":

http://atlas.labs.oreilly.com/books/1230000000337

We might want to look at how we can speed this process up, maybe by paging result sets, for example.

**Comment by runemadsen** [comment]
The reason for this is that the git-api somehow doesn't recognize binary
files, and show them in the changes tabs. I thought this was fixed, but
I'll check it again.

**Comment by MakerPress** [comment]
Ah, that makes good sense.  Maybe we need a whitelist of allowed file extension that will appear in the changes tab.  Or, maybe it will only show diffs if the original file is below a given threshold, under the tehory that even epic chapters will only be a few 1000s of K, while even the crappiest binary will be over 500K.  (Or whatever.  You get the idea: text = small, binary = large)

**Comment by runemadsen** [comment]
The way Github solves it is by using the Charlock Holmes gem and check if
the file is binary. This is what I thought I did already, but I'll check
again. A whitelist would also work.

**Comment by sandersk** [comment]
We've now suppressed binary files from the Changes tab, so I'm assuming that the speed problems are now basically resolved as well, and will close this ticket. Please reopen if I'm wrong about that, Andrew.

Thanks,
Sanders
