### ISSUE TITLE
Stuck build? (PDF)

### ISSUE THREAD

**Issue by bjepson** [MakerPress/atlas-public-feedback#92]
Hi,

I think I have a stuck build on http://ano-atlas2.herokuapp.com/books/1230000000237. It says:

39 minutes ago
 PDF pending

Thanks,

Brian

**Comment by runemadsen** [comment]
Thanks Brian. I'll check it out right now. The error I'm seeing is this: "invalid byte sequence in US-ASCII". 

I'll get back to you in a second.

**Comment by runemadsen** [comment]
Okay, I'm not sure why it's not reporting back the error. I'm looking at that right now. But this is the error:

asciidoc: ERROR: ch06.asciidoc: line 233: illegal style name: “How’d it go? Ready to make something?”

I think that the quote signs may be messing things up. @adamwitwer @sandersk any idea?

**Comment by runemadsen** [comment]
I'm debugging it right now, so hold on. That error might not be what is causing it.

**Comment by sandersk** [comment]
Hi Brian,

Rune and I tag-teamed this one. I looked into the markup issue, which was line 632 of ch06.asciidoc:

[“How’d it go? Ready to make something?”]

AsciiDoc interprets lines that start with an [ and end with a ] as macros, and thus threw an error when it couldn't find a macro matching the text above.

I put the text in an inline passthrough, and that solved the problem:

+++[“How’d it go? Ready to make something?”]+++

PDF is building successfully now, if you want to download it from the dashboard.

Let us know if you run into any more issues,
Sanders

**Comment by runemadsen** [comment]
Thanks Sanders! I'm looking into why it's not reporting back this error. I'll update this ticket when I know more.

**Comment by odewahn** [comment]
That's weird -- here's the AsciiDoc error from the pdf.log.  It clearly picked it up as an error, but I guess it never threw is as a problem:

asciidoc: ERROR: ch06.asciidoc: line 233: illegal style name: ?~@~\How?~@~Yd it go? Ready to make something??~@~]

----- Original Message -----

**Comment by MakerPress** [comment]
One more piece of the puzzle: at first I thought maybe asciidoc wasn't reporting an error code, but earlier in the log it looks like it clearly is:

E, [2012-09-25T19:24:47.842392 #17128] ERROR -- : $asciidoc -f /usr/local/app/worker/atlas-workers/workers/html_worker/config/orm.docbook.conf -f /usr/local/app/worker/atlas-workers/workers/html_worker/config/interactive.conf -a docinfo -b docbook -d book /usr/local/app/worker/tmp/html/1230000000237/book.asciidoc[status: pid 17180 exit 1]

So, it's returning a non-zero code, so "sh" should have passed it along.

----- Original Message -----

**Comment by runemadsen** [comment]
I fixed it now. The problem was that the internal Ruby string encoding was set to binary, not utf-8. This caused the communication back to Atlas to fail when strings had newlines at the end of the error message. Should be good now.

**Comment by bjepson** [comment]
Looks good, thanks!

**Comment by MakerPress** [comment]
I love the spare way you destroy my theories on what's wrong... 

Nice work.  That seems like an ugly thing to dig you. 

----- Original Message -----
