### ISSUE TITLE
error adding photos in Atlas

### ISSUE THREAD

**Issue by jcarrott** [MakerPress/atlas-public-feedback#93]
I'm unable to upload photos to add to my book.  I keep getting an error message that directs me to report a bug.  Is anyone else having this problem?  I've had the same issue with small, medium, and large files in multiple different chapters.  Please advise.  Thanks!

**Comment by runemadsen** [comment]
Hey @jcarrott 

What book is it? I just tested file uploads on a couple of cooks, and it works fine for me. Send me a link and I'll fix it.

**Comment by jcarrott** [comment]
Hi Rune,

It's Vintage Tomorrows: http://ano-atlas2.herokuapp.com/books/1230000000285

Thanks!

James

James H. Carrott
jcarrott@me.com
206.351.2690
@culthistorian
culthistorian.com

On 27 Sep 2012, at 4:32 AM, Rune Skjoldborg Madsen notifications@github.com wrote:

Hey @jcarrott

What book is it? I just tested file uploads on a couple of cooks, and it works fine for me. Send me a link and I'll fix it.

**Comment by runemadsen** [comment]
Hey James

I just uploaded an image in your book, and it worked fine. Can you try to send me the image you're having problems with?
- Rune

**Comment by jcarrott** [comment]
I've had trouble with a few images.  Let me give them another shot and I'll send you what I have problems with.

On 27 Sep 2012, at 10:51 AM, Rune Skjoldborg Madsen notifications@github.com wrote:

Hey James

I just uploaded an image in your book, and it worked fine. Can you try to send me the image you're having problems with?

Rune

**Comment by jcarrott** [comment]
I clicked the image button and gives me a selection of pre-uploaded images but won't let me upload a new one.   Am I approaching this incorrectly somehow?

On 27 Sep 2012, at 10:52 AM, James Carrott jcarrott@me.com wrote:

I've had trouble with a few images.  Let me give them another shot and I'll send you what I have problems with.

On 27 Sep 2012, at 10:51 AM, Rune Skjoldborg Madsen notifications@github.com wrote:

Hey James

I just uploaded an image in your book, and it worked fine. Can you try to send me the image you're having problems with?

Rune

**Comment by runemadsen** [comment]
How exactly is it now allowing you to upload a new image? Are you not seeing the upload form? Is it giving you and error once you press the form?

**Comment by jcarrott** [comment]
The latter.  I press "images" and get this:

Then I click "upload" and get this:

James H. Carrott
jcarrott@me.com
206.351.2690
@culthistorian
culthistorian.com

On 27 Sep 2012, at 11:08 AM, Rune Skjoldborg Madsen notifications@github.com wrote:

How exactly is it now allowing you to upload a new image? Are you not seeing the upload form? Is it giving you and error once you press the form?

**Comment by runemadsen** [comment]
Sorry, I can't see those images. Can you email them to rune@runemadsen.com?
