### ISSUE TITLE
Change User Photo on Account Page

### ISSUE THREAD

**Issue by ehewitt** [MakerPress/atlas-public-feedback#97]
If I recall correctly, some users have a photo associated with their Atlas user account. But I don't see any way I can change my user image. There is no 'upload an image for this user account' section of the Account profile page. http://ano-atlas2.herokuapp.com/users/edit. Maybe I am missing it?

**Comment by odewahn** [comment]
Hey, Eben.   We're using gravatars to handle the images.  You can set one up at:

https://en.gravatar.com/

Andrew

(We'll add a link on the user page, as well, to make it clearer.)
----- Original Message -----

**Comment by ehewitt** [comment]
Got it now. Thanks Andrew. I suppose I could RTFM (page 7). :) 
But it would be good to have the link in the UI.
