### ISSUE TITLE
Minor Typos in Atlas Docs 20120820

### ISSUE THREAD

**Issue by ehewitt** [MakerPress/atlas-public-feedback#98]
The documentation PDF called atlas_docs_20120820 is really good, but has a couple of minor typos: 
page 10: "timeby" --> "time by"
page 12: "when your connected" --> "when you're connected"

**Comment by sandersk** [comment]
Thanks very much, Eben. I've fixed these two typos in the source files for the Atlas docs. Adam, would you be able to assist me in posting updated versions to the CDN?

Sanders

**Comment by adamwitwer** [comment]
Sure thing, Sanders. We're due for an update anyway. I'll take care of it tomorrow (or I can show you how, if you want).

And thanks for the feedback, Eben!

**Comment by adamwitwer** [comment]
New version released! Typos fixed, and some new info was added.

http://cdn.oreilly.com/atlas_docs.zip
