### ISSUE TITLE
Upload Word Files, Convert WordML to AsciiDoc

### ISSUE THREAD

**Issue by ehewitt** [MakerPress/atlas-public-feedback#99]
Enhancement: Have you considered adding the ability to convert from WordML (.docx) to Asciidoc usable by Atlas? In the event that an author has already written files in Word, or just wants to write in Word, he or she should be able to upload them to Atlas, where they'll get transformed into Asciidoc, instead of having to write natively in Asciidoc. The author can then review them following the transformation to ensure that everything looks okay and make changes. 

I understand it's rather difficult dealing with WordML's markup. But while this might be a convenience feature for many technical users, this would be much more inviting to a broader, more business-oriented audience--especially if the tag line is "write how you want".

**Comment by sandersk** [comment]
Hi Eben,

Yes, Russell Jones has been working on a Word->AsciiDoc converter, written in VB, which he's currently testing on some Word documents. If you'd like to see the code, it's in GitHub here:

https://github.com/oreillymedia/word2asciidoc

I'll need to get you access to view it though. Could you email me the GitHub account you'd like to use?

Sanders

**Comment by ehewitt** [comment]
Thanks, Sanders. Thats great. I don't need to see the code, but happy to hear that's in the works!
